### ISSUE TITLE
Export README lacks line breaks in some readers

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#1002]
The README that comes with the export does not show line breaks when opened with Notepad on Windows. Linebreaks are understood by TextEdit on Macs and SublimeText on Windows.

**Comment by kerchner** [comment]
Test this on a Windows VM.   We should be able to get these via Apporto.   From John Tai:
```
Via web browser, go to https://desktops.at.gwu.edu, then
click on “VMware Horizon HTML Access”, login with your NetID.

Once login, you should see “LAI Staff Pool”.  Click on it,
it should launch the Windows VM for you.
```

**Comment by lwrubel** [comment]
As @somanath304 discovered in his research, this is a problem with how Notepad interprets line-endings in file created by Linux/Mac systems. Microsoft addressed this in a Windows 10 update in 2018: https://devblogs.microsoft.com/commandline/extended-eol-in-notepad/

**Comment by kerchner** [comment]
Suggest adding this known issue to https://sfm.readthedocs.io/en/latest/limitations.html
