### ISSUE TITLE
Accessibility updates to login and home pages

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#1025]
login pages:
- Remove text from top of login page, since it repeats the text on the right. Check the order in which things would be read by a screen reader to make sure it makes sense. 
- Make signup.html page (templates/account/signup/html) match the login page's text as above. Don't have link text "here". 

home page:
- Aria roles for analytics controls. Add to the div with role="group" an aria-label="filter by time" (or something like that)

For further accessibility details see #1004 .

**Comment by kerchner** [comment]
As per item 2 in #1023 , change `role` property from `alert` to `status` in alerts that are below `error` or `danger` level.  This appears to affect two pages that related to this ticket:
- `account/snippets/already_logged_in.html`
- `account/password_reset_done.html`

**Comment by lwrubel** [comment]
The home page also needs a top-level heading. Any thoughts on "Collection Set Analytics", @kerchner and @dsmith? 

<img width="1401" alt="Screen Shot 2020-04-27 at 1 41 29 PM" src="https://user-images.githubusercontent.com/1619369/80407377-83bd1b00-8893-11ea-8aec-b6770387ecf4.png">

**Comment by kerchner** [comment]
That heading seems good, and it also makes me think there is potential for displaying more collection-set level analytics on each collection (# of tweets, files, storage size, etc.).  I believe this was the intent of #1007.

**Comment by lwrubel** [comment]
Great, that heading gives us room to grow, then.
