### ISSUE TITLE
Export permissions error in 2.3.0

### ISSUE THREAD

**Issue by Geoffsc** [gwu-libraries/sfm-ui#1054]
Hi, we recently upgraded to sfm-docker 2.3.0 using local storage and migrated our data over from 2.1.0 (which was using docker storage). We're currently getting a permissions error when we try to export any crawls. The error from the docker log is pasted below. Any help is much appreciated!

twitterrestexporter_1           | Traceback (most recent call last):
twitterrestexporter_1           |   File "/usr/local/lib/python3.6/shutil.py", line 544, in move
twitterrestexporter_1           |     os.rename(src, real_dst)
twitterrestexporter_1           | PermissionError: [Errno 13] Permission denied: '/sfm-data/containers/991b488d8b10/tmp' -> '/sfm-data/export/946bd53e7ad845349187e2db0884b5ad'
twitterrestexporter_1           |
twitterrestexporter_1           | During handling of the above exception, another exception occurred:
twitterrestexporter_1           |
twitterrestexporter_1           | Traceback (most recent call last):
twitterrestexporter_1           |   File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 623, in _receive_callback
twitterrestexporter_1           |     return on_m(message) if on_m else self.receive(decoded, message)
twitterrestexporter_1           |   File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 589, in receive
twitterrestexporter_1           |     [callback(body, message) for callback in callbacks]
twitterrestexporter_1           |   File "/usr/local/lib/python3.6/site-packages/kombu/messaging.py", line 589, in <listcomp>
twitterrestexporter_1           |     [callback(body, message) for callback in callbacks]
twitterrestexporter_1           |   File "/usr/local/lib/python3.6/site-packages/sfmutils/consumer.py", line 111, in _callback
twitterrestexporter_1           |     self.on_message()
twitterrestexporter_1           |   File "/usr/local/lib/python3.6/site-packages/sfmutils/exporter.py", line 137, in on_message
twitterrestexporter_1           |     shutil.move(temp_path, export_path)
twitterrestexporter_1           |   File "/usr/local/lib/python3.6/shutil.py", line 555, in move
twitterrestexporter_1           |     symlinks=True)
twitterrestexporter_1           |   File "/usr/local/lib/python3.6/shutil.py", line 315, in copytree
twitterrestexporter_1           |     os.makedirs(dst)
twitterrestexporter_1           |   File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
twitterrestexporter_1           |     mkdir(name, mode)
twitterrestexporter_1           | PermissionError: [Errno 13] Permission denied: '/sfm-data/export/946bd53e7ad845349187e2db0884b5ad'

**Comment by lwrubel** [comment]
Hi @Geoffsc, sorry to hear your exports aren't working since the shift, and thanks for the log snippet. I'm assuming you saw this, but just in case: we have recommended steps for [moving from a Docker internal volume to a linked volume](https://sfm.readthedocs.io/en/stable/storage.html#moving-from-a-docker-internal-volume-to-a-linked-volume)

If it's still not working it might be helpful to see what you have set for the `DATA_VOLUME` parameter in your `.env` and possibly what the current permissions are on the sfm-data directory and subdirectories. If you prefer to email any info, you can reach us at sfm@gwu.edu.

**Comment by Geoffsc** [comment]
@lwrubel thanks for your reply -- we actually didn't see that part of the documentation. I think the chown command on sfm-data may be exactly what we need. We will try this as soon as we can and update the Github issue. Thanks much!

**Comment by Geoffsc** [comment]
The chown command was exactly what we needed, exports are working now. Thanks so much for your help!

**Comment by lwrubel** [comment]
Glad to hear that worked!
