### ISSUE TITLE
BaseHarvester unit tests

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#107]
Currently BaseHarvester is tested indirectly by unit tests in the harvesters.  It needs its own unit tests directly in sfm-utils.

**Comment by justinlittman** [comment]
Must test that harvest start and harvest end are valid iso format dates.

**Comment by justinlittman** [comment]
Silly me.  There are already plenty of unit tests.

https://github.com/gwu-libraries/sfm-utils/pull/4 is for testing valid iso format dates.

**Comment by kerchner** [comment]
Closing; fixed by https://github.com/gwu-libraries/sfm-utils/pull/4
