### ISSUE TITLE
Upgrade Django in sfm-ui to 2.2.27+

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#1098]

**Comment by dolsysmith** [comment]
I think we need to upgrade to at least Django 3.2. The 2.2 LTS reached its [end of life](https://www.djangoproject.com/download/#supported-versions) in April 2022.

**Comment by dolsysmith** [comment]
Suggest focusing this effort on the major release upgrade of Django and moving to a dedicated sprint.

**Comment by kerchner** [comment]
Django 2.2 is no longer supported.   Closing this ticket in favor of #1126
