### ISSUE TITLE
Add label to limit field in Search/Academic Search seed form

### ISSUE THREAD

**Issue by dolsysmith** [gwu-libraries/sfm-ui#1120]
Because of Twarc 2's implementation of the limits, users may enter a limit in a multiple of 100 but get back more Tweets: e.g., entering a limit of 500 may yield up to 599 results.

Let's add a UI label to the limit field with the following text: "Limits are approximate; actual results may exceed the limit slightly."

**Comment by dolsysmith** [comment]
@adhithyakiran I think maybe just an info message (blue), so as not to detract from the warning about the start_time and end_time limits. And yes, it should appear on both forms.

**Comment by adhithyakiran** [comment]
Changes are done!
