### ISSUE TITLE
v2 credential label updates

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#1121]
Twitter now refers to the consumer key and secret as "API key" and "API key secret."  Let's change the labeling in the UI and documentation to match.

**Comment by adhithyakiran** [comment]
![image](https://user-images.githubusercontent.com/76047988/184973539-7a6eea55-ee77-40dd-a378-dd73e52624c9.png)

**Comment by adhithyakiran** [comment]
I'm able harvest tweets after the ui changes in the twitterV2 credential form.
![image](https://user-images.githubusercontent.com/76047988/185479186-5c16a185-9681-4fe4-8887-d31cf3a88415.png)
