### ISSUE TITLE
Twitter search version 2 (non-academic) seed UI form should not display Start/End times

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#1129]
Start/End times are only available as part of the academic search API, but not the non-academic, v2 search API.

However, the seed form for `Twitter search version 2` includes parameters for Start time and End time. Using these without an Academic Researcher credential returns a 400 error from the harvest.  Start and End times should be removed from the `Twitter search version 2` seed form.

**Comment by dolsysmith** [comment]
Actually, it *is* possible to use start/end times with the regular search on v.2. For instance, I am able to create a search for the query `soccer` and set the date to one day ago, and it returns Tweets from the corresponding interval. A start time set outside the bounds of seven days should now automatically be adjusted, preventing an error from the API. Let me know if you can't replicate, but the changes are on the [t1103-twitter-2-exporter](https://github.com/gwu-libraries/sfm-docker/tree/t1103-twitter-2-exporter) branch of `sfm-twitter-harvester`.

**Comment by kerchner** [comment]
+1 I will retest

**Comment by kerchner** [comment]
@dolsysmith The search runs without returning an error, but how will the user know that the start time was adjusted?

**Comment by dolsysmith** [comment]
Would it address the issue to add some helper text to say "Start and end dates must be within the previous 7 days. A start date outside of that time period will be ignored."

**Comment by kerchner** [comment]
@dolsysmith Yes

**Comment by dolsysmith** [comment]
I pushed an update with the additional text to the `duplicate-seed` branch on `sfm-ui`.
