### ISSUE TITLE
Bulk Add Seeds is crashing for Twitter user timeline v2

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#1130]
When I create a new (or access an old) Twitter user timeline v2 collection, and I edit the seed list using the Bulk edit button, the UI throws the following error:

```
AttributeError at /ui/seeds/bulk/25

module 'ui.forms' has no attribute 'BulkSeedTwitterUserTimeline2Form'

Request Method: 	GET
Request URL: 	http://gwdev-kerchner-14.wrlc.org:8080/ui/seeds/bulk/25
Django Version: 	2.2.24
Exception Type: 	AttributeError
Exception Value: 	

module 'ui.forms' has no attribute 'BulkSeedTwitterUserTimeline2Form'

Exception Location: 	/opt/sfm-ui/sfm/ui/views.py in _form_class, line 679
Python Executable: 	/usr/local/bin/python
Python Version: 	3.8.12
Python Path: 	

['/opt/sfm-ui/sfm',
 '/usr/local/lib/python38.zip',
 '/usr/local/lib/python3.8',
 '/usr/local/lib/python3.8/lib-dynload',
 '/usr/local/lib/python3.8/site-packages',
 '/opt/sfm-utils']

Server time: 	Wed, 23 Nov 2022 10:57:26 -0500
```

This is occurring with sfm_ui on either the master branch (as of https://github.com/gwu-libraries/sfm-ui/commit/7e161b8d0e13ec53d38420738acb5d2e7c5a1634 ) or the [duplicate_seed ](https://github.com/gwu-libraries/sfm-ui/tree/duplicate_seed) branch, and with sfm_twitter_harvester on [`t1103-exporter-v2`](https://github.com/gwu-libraries/sfm-twitter-harvester/tree/t1103-exporter-v2)

**Comment by dolsysmith** [comment]
I pushed a commit to the duplicate_seed branch that should fix this one. Thanks for catching it! (I definitely forgot to test the Bulk Add feature!)

**Comment by kerchner** [comment]
Fixed in https://github.com/gwu-libraries/sfm-ui/pull/1128/commits/74a27915ca57a855b06f5d668fadf5510fb926b0
