### ISSUE TITLE
Enhance recording of harvest status message

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#117]
* Create harvest model instance when harvest start message is sent and record request date.
* Record/update harvest model instance when harvest status message is received with status, start date, end date, informational messages, warning messages, errors, summary, warc count, and warc bytes.
* Also from harvest status message, update seeds based on uids and token updates.  Log entries should be created for these changes.

**Comment by kerchner** [comment]
Closed by #120
