### ISSUE TITLE
Update Twitter Harvester to use twarc.filter

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#119]
https://github.com/edsu/twarc/releases/tag/v0.5.0 will allow us to exercise the statuses/filter Twitter API call with the more full set of parameters.  Currently we are limited by twarc 0.4 to using just `track`, but 0.5.0 will allow us to use `follow` and `locations`.  These are available in social-feed-manager so it would be best not to lose this functionality.  We would need to switch https://github.com/gwu-libraries/sfm-twitter-harvester/blob/0.1.1/twitter_harvester.py#L61 to use `.filter` rather than `.stream` as well as provide for the messaging to pass the additional parameters.

**Comment by justinlittman** [comment]
@kerchner This is done in https://github.com/gwu-libraries/sfm-twitter-harvester/pull/6

**Comment by kerchner** [comment]
Closing in line with comment above.
