### ISSUE TITLE
Create initial export manifest

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#123]
Followon to #67.  Create initial infrastructure to generate an export manifest, to include basic metadata generated from WARCs and/or from app logs.

**Comment by kerchner** [comment]
Discuss with broader project team to assess current work and current thinking on export manifest.

**Comment by lwrubel** [comment]
Depends on work by Chris Prom exploring needs and use cases, and consideration by archivists.

**Comment by justinlittman** [comment]
Depends on #532 to allow writing to /sfm-data from sfm ui.

**Comment by justinlittman** [comment]
TODO:  Add to documentation.

**Comment by justinlittman** [comment]
Also, need to remove RO from /sfm-processing in sfm ui container.

**Comment by justinlittman** [comment]
Depends on #532.

**Comment by lwrubel** [comment]
Agreed to go with a basic export manifest of collection / collection set metadata, in the form of a README as created for the elections dataset, and request feedback before further development.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-docker/commit/844e6356919aff3bc93d5d40a9e464841e67e178 removed RO from /sfm-processing.

**Comment by kerchner** [comment]
PR is https://github.com/gwu-libraries/sfm-ui/pull/591
