### ISSUE TITLE
Handle streaming jobs

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#129]
As noted in the [messaging spec](http://sfm.readthedocs.org/en/latest/messaging_spec.html#flow), streaming harvests have a different flow than REST harvests.  Streaming harvests require that start and stop messages be sent.

This ticket is for adding support for this to SFM UI.

**Comment by kerchner** [comment]
Ref. #129.   Pause/Record button on SeedSet could be the UI control that triggers start/stop messages to a streaming harvest.
