### ISSUE TITLE
Credential UI

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#133]
- Designs for UI
- Create tickets for UI work

**Comment by kerchner** [comment]
This will entail:

- #146 for screen designs.
- dev work in this ticket.

As per discussion, a credential set will still be persisted as a JSON object.  Create/update screen will list a set of keys, where the user enters the values for those keys.

**Comment by rajatvij** [comment]
@justinlittman Can you confirm on the fields we need for various platform tokens? Is it just 'key' and 'secret' like flickr or do we need different fields for different platforms?

**Comment by justinlittman** [comment]
Different fields for different platforms.  See https://github.com/gwu-libraries/sfm-flickr-harvester#authentication and https://github.com/gwu-libraries/sfm-twitter-harvester#authentication.

**Comment by kerchner** [comment]
For 0.5, do twitter, flicker, weibo.   Leave tumblr for a separate, future ticket.
