### ISSUE TITLE
Is active flag ignored when scheduling harvests

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#138]
When scheduling a harvest (sched.schedule_harvest), the harvest should only be scheduled if the seedset is active.  Otherwise, it should be unscheduled.

When executing a harvest (jobs.seedset_harvest), a harvest request message should only be sent if there are active seeds.

**Comment by rajatvij** [comment]
Need a quick confirmation. This ticket means that we should ignore harvesting objects which are not active(ie., Is Active = False) during our harvests?
Our harvests are at seed set level so i am not sure if we will be able to work with Is Active Flag at seed level. Or if there is any way that we can implement it without modifying underlying harvest job.

**Comment by rajatvij** [comment]
Ignore my above doubt on implementing Is Active flag at seed level
@justinlittman I am getting an error when i am trying to update a seedset from UI. I tried to do the same using admin interface, but am unable to see the logs that i want to see.

**Comment by justinlittman** [comment]
It means that we should not add jobs to the scheduler in which active =
False.

Also, when we execute a scheduled job, we should take active = False on
seeds when deciding what seeds to include in harvest start message (or
whether to send a harvest start message at all).

**Comment by kerchner** [comment]
We need to talk through the behavior of the jobs when the Collection is updated to `is_active = False`

**Comment by kerchner** [comment]
As discussed, remove Collection.is_active from model,
