### ISSUE TITLE
Update libpq-dev version in requirements.apt

### ISSUE THREAD

**Issue by rajatvij** [gwu-libraries/sfm-ui#139]
Change libpq-dev version in requirements.apt to 9.3.11-0ubuntu0.14.04

**Comment by kerchner** [comment]
Previous version (9.3.10-0ubuntu0.14.04) was resulting in:
```Version '9.3.10-0ubuntu0.14.04' for 'libpq-dev' was not found```
It has apparently been superseded by 9.3.11-0ubuntu0.14.04
