### ISSUE TITLE
Use package wildcarding

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#141]
refs #29.

As it turns out, when a new version is added to an apt repo, the old version is removed.  This is causing the docker image build to break on a regular basis.

A solution is to use package wildcarding (`/*`) to pin package with less specifity (e.g., to the minor, rather than the patch).

**Comment by kerchner** [comment]
The Debian policy manual describes the version numbering scheme here:  https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

It appears that packages vary in terms of their _debian_revision_ numbering scheme.  The numbering appears to be "semantic style" but can have anywhere from simply a major debian revision version number (e.g. -1ubuntu3) to many segments after the major version (e.g. -4ubuntu2.1.14.04.2).  Thus it's not entirely clear for a particular package whether the last segment is truly being used to describe a patch number.

I would advocate in favor of, for now, being conservative (/sparing) about use of wildcarding unless we see specific packages that seem to change frequently, or where we're able to better ascertain that incrementing the last segment is truly limited to patch type changes.

**Comment by kerchner** [comment]
In implementing #165, I reviewed package notes (located at https://launchpad.net/ubuntu/trusty/+source/<PACKAGE NAME>/+changelog for each package ) to get a sense for the nature of the changes with each subsequent release.
