### ISSUE TITLE
Reconsider approach to Docker storage

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#144]
Due to recent changes in Docker, a different strategy may be preferable.

See https://kvaes.wordpress.com/2016/02/11/docker-storage-patterns-for-persistence/?mkt_tok=3RkMMJWWfF9wsRonuqTMZKXonjHpfsX57uUoXqOxlMI%2F0ER3fOvrPUfGjI4DSsprI%2BSLDwEYGJlv6SgFQ7LMMaZq1rgMXBk%3D

**Comment by kerchner** [comment]
@Tanych feel free to learn about this if you are looking for tickets to work on

**Comment by justinlittman** [comment]
Based on my research, named volumes do not support mounting directories from the host system, so we should leave existing approach in place.

However, we should still upgrade to docker-compose.yml version 2. See #382.
