### ISSUE TITLE
Credential UI design mockups

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#146]
Supports #133.

- List view for list of my credentials, w/ability to Add a new credential
- Create credential screen
- Update credential

**Comment by rajatvij** [comment]
@lwrubel @kerchner Please check following wireframe for the Credentials UI Screen, Let me know if any modification is required in screen of if we dont need changelog there.

https://drive.google.com/drive/u/0/folders/0B6mKHHXuA0dfZlJmcUI2SkVUOEU

**Comment by kerchner** [comment]
Closing; #133 is occurring already, no need to go back and create wireframes.
