### ISSUE TITLE
Seed validation upon new seed add

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#158]
Enhance the UI to allow the user to enter a token, and have the application validate and populate the UID.  The UID should be viewable (read-only) in the seed detail page (and possibly seed set detail page).  Followon to #101.

**Comment by kerchner** [comment]
As per discussion 11-Apr, we do want to validate at the time the user adds the seed via UI.  This is likely to require a "validate seed" message to go from the UI app to the harvester, returning info about UIDs, invalid seed names, etc.

**Comment by justinlittman** [comment]
I'd suggest that we see if this an actual user problem before we implement. This is likely to take a fair bit of work.

**Comment by kerchner** [comment]
An intermediate option would be to do this upon the first harvest of the seed (i.e. when in https://github.com/gwu-libraries/sfm-twitter-harvester/blob/100920e4d9e94e955be79f1293d9790008314c73/twitter_harvester.py#L91-L92 - there is a screen_name but not an id) and call `Twarc.user_lookup()`  as this invokes a Twitter API call that should return more robust error information regarding whether a user is suspended, not found, private, etc.

Ideally this would be done at the time of seed add, but at least doing it at the time of harvest (for seeds where there's no user id) will get a bit more info, at the expense of an API call of course.

**Comment by lwrubel** [comment]
Closing, but monitor how changes with seed deletion and on / off button changes improve workflow for handling seed changes.
