### ISSUE TITLE
Activate/inactivate for seeds, seed lists

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#159]
The seeds list on the seedset page should allow the user to inactivate/activate individual seeds, and add a change note to these changes.

We should discuss and make a decision on whether to provide for deletion of seeds.

**Comment by justinlittman** [comment]
Deleting seeds complicates history, so I would encourage inactivation.

**Comment by kerchner** [comment]
Spun off #185 to deal with the question of deletion.

**Comment by kerchner** [comment]
- A Seed will have an active/inactive toggle
- A SeedSet will have a "Pause"/"Recording" (or similar) button (which uses the existing is_active flag) and does not modify any SeedSet field values (e.g. frequency, etc.)

**Comment by justinlittman** [comment]
Here's a proposal that may simplify and allow consistency across streaming and non-streaming harvests.
1.  Get rid of harvest start date.  (Can you think of a significant use case for this?)
2.  When the stop date for a harvest passes, it is toggled to pause.
3.  Changes to a seedset or a seed or the addition of a seed to a seedset can only be made when the seedset is paused.
4.  Seedsets are paused by default when they are created.

So, for a non-streaming harvest type:
1. User creates the seed set.  (Seed set is paused and editable.)
2. User adds seeds to the seed set.
3. User unpauses the seed set.
4. Harvests are scheduled.
At a future point:
1. User pauses the seed set.  (Seed set is editable.)
2. User adds a new seed and inactivates an existing seed.
3. User unpauses the seed set.
4. Harvests are unscheduled.
When the scheduled stop time is reached:
1. Harvests are unscheduled.
2. Seed set is paused.

For a streaming harvest type:
1. User creates the seed set.  (Seed set is paused and editable.)
2. User adds seeds to the seed set.
3. User unpauses the seed set.
4. Harvest start message is sent.
At a future point:
1. User pauses the seed set.  (Seed set is editable.)
2. Harvest stop message is sent.
2. User adds a new seed and inactivates an existing seed.
3. User unpauses the seed set.
4. Harvest stop message is sent.
When the scheduled stop time is reached:
1. Harvests stop message is sent.
2. Seed set is paused.

Let's discuss.

**Comment by justinlittman** [comment]
@lwrubel Are you OK with me taking this ticket and proceeding?  I'd also like to knock off #181 and #129 at the same time.

**Comment by lwrubel** [comment]
OK. See bootstrap's toggle widget as a possible UI handle to the active/inactive setting. If it makes sense to break this ticket down and split it up, let me know.

**Comment by kerchner** [comment]
Closing - fixed in #222
