### ISSUE TITLE
implement messaging tracer bullet

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#16]
Depends on #14.  Workers can just log to console when messages are received / passed further along.

**Comment by justinlittman** [comment]
Depends on #22.

**Comment by rajatvij** [comment]
I have been trying to create a json message out of forms on seed update page. By our use case i think the json messages should be generated when a seed, seed set or collection is created or updated. Theoretically using get_object function in view we should be able to get the values of the fields in view itself from where we can create and push json messages on queue. But i can't seem to get around it yet. So i would appreciate any help i can get on this. Or if there is any other approach that i should use.
I can always use javascript to get around this but i think finding a django way to do this would make our code more cleaner as compared to using javascript in this case.

**Comment by justinlittman** [comment]
This is all only a temporary step until we add a scheduler.  I would
suggest just adding a "send message" button that triggers sending the
message for the seed set.  No need for anything more complicated.

**Comment by kerchner** [comment]
Per discussion, the form should submit to the django view, and the view code should trigger the JSON message being sent to the queue - rather than sending the message from the Javascript on the client side.

**Comment by justinlittman** [comment]
The tracer bullet consists of:
1. A user populating collection, seed, seed set, and credential information in the SFM UI for a Flickr user .  (Parts of this can be performed in Admin.)
2. Some action by the user (clicking a button, submitting a form) triggers constructing a Flickr user harvest start message and submitting to the queue.
3. The Flickr Harvester receives the message and performs the harvest.

Some additional details:
* For JSON fields in the model, the user can enter JSON into the text box.  This includes Credentials.token and SeedSet.harvest_options.
* Wherever necessary, parts of the harvest message can be hardcoded.
* The routing key for the message should be `harvest.start.flickr.flickr_user`.
* The harvest type is `flickr_user`.

Following is an example Flickr user harvest start message:
```
{
            "id": "test:1",
            "type": "flickr_user",
            "seeds": [
                {
                    "uid": "131866249@N02"
                }
            ],
            "options": {
                "sizes": ["Thumbnail", "Original"]
            },
            "credentials": {
                "key": "FLICKR_KEY",
                "secret": "FLICKR_SECRET"
            },
            "collection": {
                "id": "test_collection",
                "path": "/tmp/test_collection"

            }
}
```
