### ISSUE TITLE
Seeds not listing on seedset detail page

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#161]
Steps to reproduce:
1. Create a seedset and add a seed to the seedset.
2. Go to the details pages for the seedset.

Expected result:
Seeds are listed in seeds section.

Actual result:
No needs are listed.

Looking at the code, `context["seed_list"] = seed_set.seeds.all()` is missing from `get_context_data()` for SeedSetDetailView.

Probably should be added to unit test as well.

**Comment by lwrubel** [comment]
I'm kind of mystified how this line disappeared, since it was there (although not written as succinctly) in a [commit in t99](https://github.com/gwu-libraries/sfm-ui/commit/5da73dbefb1509e5a4d55a665d09ee3e6cb23b19) . But maybe something happened when I had to resolve merge conflicts.

**Comment by justinlittman** [comment]
I had a feeling it was something like that.
