### ISSUE TITLE
Only send harvest.start.web message when there are seeds

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#168]

**Comment by kerchner** [comment]
@justinlittman please elaborate scenario

**Comment by justinlittman** [comment]
Sure.  It's possible (in fact, it has happened to me) that a harvest does not result in any urls being extracted.  In that case, a web harvest start message should not be sent.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-utils/commit/adf54d3332767131191f26791e972672de5c5f15
