### ISSUE TITLE
Support harvest options for Twitter harvester

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#176]
In particular, which type of entities (urls, etc.) to extract.

**Comment by kerchner** [comment]
In 1.0, let's use a default set of entity type(s) in implementing #155.   This ticket is for post-1.0 work to enable the user to specify non-default options.

**Comment by justinlittman** [comment]
This is critical because the twitter sample stream will create an enormous number of URLs that will overwhelm the web harvester.  And it's easy.

**Comment by justinlittman** [comment]
PR for this ticket:  https://github.com/gwu-libraries/sfm-twitter-harvester/pull/10

**Comment by Tanych** [comment]
The Weibo harvest has the same problem, it gets bunches of urls in texts including the photo urls. Usually, thousands of urls. It would increase the burden of web harvester.
