### ISSUE TITLE
Add seed set id to harvest path

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#177]
Currently, the collection id is used to determine the path for a harvest.  Using the collection id and the seed set id will keep different types of harvest separate, which makes figuring out what is what on the file system a bit easier.

**Comment by rajatvij** [comment]
@justinlittman Although this might save multiple seedsets in same folder, but wouldn't using harvest type instead of seed set id be more human readable and cleaner. And that would also keep different type of harvest separate. Let me know what seems better to you.

**Comment by justinlittman** [comment]
I can see harvest types changing, so I'd prefer to stick with seed set id
(which will not change).
