### ISSUE TITLE
Support seedless harvest types

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#181]
Some harvest types (e.g., Twitter stream and Weibo friends) don't have seeds.  Since a seed is required to send a harvest start message, the current kluge is add a dummy seed, which is then ignored by the harvester.

To fix this:
* Create a means of identifying seedless harvest types.
* When a harvest submit is triggered, if the harvest type is seedless then skip the check that requires a seed.
* Send the seed set identifier in the harvest start message.
* Change the UI so that seeds cannot be added for seed sets of seedless harvest types.
* Change the UI so that seeds or seed counts are not listed for seed sets that are seedless harvest types.
* Update the message spec to reflect the above.

**Comment by kerchner** [comment]
Fixed in #222
