### ISSUE TITLE
Twitter REST exporter

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#182]

**Comment by justinlittman** [comment]
Depends on https://github.com/gwu-libraries/sfm-ui/pull/203.

PRs for this ticket:
* https://github.com/gwu-libraries/sfm-utils/pull/9
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/7

**Comment by kerchner** [comment]
Resolved by the above two PRs.
