### ISSUE TITLE
Sina Weibo exporter

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#183]
This will be like the Twitter exporter (#182).

**Comment by Tanych** [comment]
## Exporter with uid
Currently, the uid locates in the seeds page. The exporter can filter the post status data relying on the seeds' uids. However, the weibo harvester is seedless. It might a problem with exporting the status using uids. For example, someone follows ten users, but he only needs to export two followers' haverster data. 
In this case, it also needs to add seeds and uids in the seed page.

**Comment by kerchner** [comment]
See https://github.com/gwu-libraries/sfm-weibo-harvester/pull/10

**Comment by kerchner** [comment]
Completed in https://github.com/gwu-libraries/sfm-weibo-harvester/pull/12
