### ISSUE TITLE
Filter which credentials are viewable/editable by a user

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#184]
In the course of implementing #133, a question arose as to which credentials should be viewable in the credentials list view; should a user be able to view, and possibly even edit, other users' credentials in the same group? - ref. discussion on #180.   Consider the fact that a SeedSet created by User 1, using a credential from User 1, will be editable by User 2 - when User 2 edits it, will User 2 be able to re-save the SeedSet if it still uses User 1's credentials?   These are questions that seem to need some discussion.

The scope for this ticket is to discuss, make a decision, and implement filtering related to Credentials.

**Comment by rajatvij** [comment]
Here's a proposal on user permissions required to view/edit credentials

User belonging to a group should be able to view all credentials in the group, but should only have access to edit credentials that he/she created.

NOTE: Here i am not sure whether we should even give user access to view the credential detail screen of all credentials under the same group at all but user should be able to select these credentials belonging to the same group in seedset create page at least or atleast have an entry on credential list screen.

Considering user is able to view credentials in same group. User may need following permissions:

**group 1**
_user1–cred1–can edit/update_–need custom permission to restrict access to user created objects only
_user2–cred2–can edit/update_–need custom permission to restrict access to user created objects only
_user3–cred3–can edit/update_–need custom permission to restrict access to user created objects only

_user1–cred1, cred2, cred3–can view–can create_–is handled by django group permissions
_user2–cred1, cred2, cred3–can view–can create_–is handled by django group permissions
_user3–cred1, cred2, cred3–can view–can create_–is handled by django group permissions

**group 2**
unable to access group 1 objects – is handled by django group permissions

**Comment by kerchner** [comment]
Filter only by group, but allow users in the group to edit.

**Comment by rajatvij** [comment]
@kerchner @justinlittman I have pushed a branch which lets us only see credentials that are owned by user in credential list screen and deals with the available group credentials on seedset create screen. 

But if we type the url any other credential we can edit and view that credential. Dealing with that issue might require us to create custom permissions and adding those permissions to users for any created object by user(I am not sure that is the approach we should take here). I think it would be better to separate that into a new ticket. As that ticket can potentially cover other user access issues related to collections too.

**Comment by justinlittman** [comment]
For now, can you make it so that the edit button is only enabled on the
credentials page if the credential was created by the User of the User is a
SuperAdmin?
