### ISSUE TITLE
sfm-weibo-harvester and sfm-ui integration tests issues

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#187]
## 1. Sfm harvesters raise UnicodeEncodeError when seed token includes Non-ASCII
Including sfm-ui and sfm-weibo-harvester
### Sfm-ui Related Input
Seedset
* Name: 帐号关注(Anti-Corruption Followers)
* Harvest options: {"incremental": true}

Seeds
* Token: 测试(Anti-corruption-seed) 

### Havester Error Output
```python
sfmweiboharvester_1 |   File "weibo_harvester.py", line 45, in search_timeline
sfmweiboharvester_1 |     since_id = self.state_store.get_state(__name__, "{}.since_id".format(query)) if incremental else None
sfmweiboharvester_1 | UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

The reason for the error is that the token includes non-ASCII characters, and it uses `string.format` to combine ASCII and Unicode. Therefore, it raises the `UnicodeEncodeError`.

All the harvesters including `sfm-twitter-haverster` and `sfm-flickr-harvester` have the same problem when try to save the since_id with Unicode seed token to files.

### Possible Solutions:
Take Unicode format
```python
 since_id = self.state_store.get_state(__name__, u"{}.since_id".format(query)) 
```

### Sfm-ui Credential Input
```python
Credential: {'access_token': u'2.00ZUHDrBCwSOKCabef2add053DyTTC', 'api_secret': u'fe6ce4c477f059b58c986d5224f48a6d', 'api_key': u'1983438406', 'redirect_uri': u'https://about.me/tanvict'}
```
### Error Output
```python
evapp_1         | [Tue Apr 12 12:34:52.328596 2016] [:error] [pid 221:tid 139871582680832] Traceback (most recent call last):
sfmdevapp_1         | [Tue Apr 12 12:34:52.328597 2016] [:error] [pid 221:tid 139871582680832]   File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 108, in run_job
sfmdevapp_1         | [Tue Apr 12 12:34:52.328599 2016] [:error] [pid 221:tid 139871582680832]     retval = job.func(*job.args, **job.kwargs)
sfmdevapp_1         | [Tue Apr 12 12:34:52.328600 2016] [:error] [pid 221:tid 139871582680832]   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 145, in inner
sfmdevapp_1         | [Tue Apr 12 12:34:52.328601 2016] [:error] [pid 221:tid 139871582680832]     return func(*args, **kwargs)
sfmdevapp_1         | [Tue Apr 12 12:34:52.328601 2016] [:error] [pid 221:tid 139871582680832]   File "/opt/sfm-ui/sfm/ui/jobs.py", line 52, in seedset_harvest
sfmdevapp_1         | [Tue Apr 12 12:34:52.328602 2016] [:error] [pid 221:tid 139871582680832]     message["credentials"] = json.loads(str(historical_credential.token))
sfmdevapp_1         | [Tue Apr 12 12:34:52.328603 2016] [:error] [pid 221:tid 139871582680832]   File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
sfmdevapp_1         | [Tue Apr 12 12:34:52.328604 2016] [:error] [pid 221:tid 139871582680832]     return _default_decoder.decode(s)
sfmdevapp_1         | [Tue Apr 12 12:34:52.328604 2016] [:error] [pid 221:tid 139871582680832]   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
sfmdevapp_1         | [Tue Apr 12 12:34:52.328605 2016] [:error] [pid 221:tid 139871582680832]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
sfmdevapp_1         | [Tue Apr 12 12:34:52.328606 2016] [:error] [pid 221:tid 139871582680832]   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
sfmdevapp_1         | [Tue Apr 12 12:34:52.328607 2016] [:error] [pid 221:tid 139871582680832]     obj, end = self.scan_once(s, idx)
sfmdevapp_1         | [Tue Apr 12 12:34:52.328607 2016] [:error] [pid 221:tid 139871582680832] ValueError: Expecting property name: line 1 column 2 (char 1)
```

### Reason
`seedset_harvest(seedset_id) ` in [jobs.py](https://github.com/gwu-libraries/sfm-ui/blob/master/sfm/ui/jobs.py#L50) use `json.loads` try to decode the `string` as a dcitionary.
However, `json.loads` only support for ASCII string. 

##  Possible Solutions
A possible solution is using `ast.literal_eval` instead of `json.loads`. However, there are lots of disscusion about them. 
## Links
* http://stackoverflow.com/questions/9949533/python-eval-vs-ast-literal-eval-vs-json-decode
* http://stackoverflow.com/questions/956867/how-to-get-string-objects-instead-of-unicode-ones-from-json-in-python
* https://docs.python.org/2/library/json.html
* http://stackoverflow.com/questions/19309731/python-json-loads-expecting-property-name-line-1-column-2-char-2

**Comment by Tanych** [comment]
Weibo harvester issues Solved by commit https://github.com/gwu-libraries/sfm-weibo-harvester/pull/9/commits/6194505ec8f440483f6669c5101dc1ffde34d4cf 
I am not sure whether twitter harvester needs to add  the solution if the seed token is beyond English words.
@justinlittman

**Comment by justinlittman** [comment]
Can we add the unicoding to the state store instead of each harvester
separately?

**Comment by Tanych** [comment]
@justinlittman The problem is that `"{}.since_id"` will be considered as ASCII string type in Python 2, While python 3 will consider as Unicode. Currently, the seed token stored as Unicode which reads from django form. When we try to combine an ASCII with Unicode, Like:  
```python
>>>"{}.since_id".format(u"中文")
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    "{}.since_id".format(u"中文")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```
It won't work in this way, because `format` depends on the first half part `"{}.since_id"` , it tries to decode as ASCII.

**Comment by lwrubel** [comment]
@Tanych will make change above in each harvester.

**Comment by Tanych** [comment]
fixed by https://github.com/gwu-libraries/sfm-twitter-harvester/pull/9 and https://github.com/gwu-libraries/sfm-weibo-harvester/pull/9
