### ISSUE TITLE
Changes to harvest modeling for web harvester

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#188]
Prereq of #155.

Web harvests are different from social media harvests.  Web harvests are initiated by harvesters (not the SFM UI scheduler).  As such, the harvest model object is not created when the harvest message is sent.  In addition, web harvests reference the parent social media harvest from which they originated.

Also, web harvests don't have seeds that are recorded as seed model objects.

Thus, the proposed changes are:
1. Add web harvest as a harvest type.
2. Change harvest model so that a harvest model object has an optional parent harvest.
3. Change harvest model object creation so that it is created in response to harvest start message.

**Comment by kerchner** [comment]
Resolved in #190 - closing issue.
