### ISSUE TITLE
Remove encoding from WARC response records

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#195]
According to Kristinn Sigurðsso, encoding should be removed from payload in WARC response records.  See Chapter 6.3.2 of spec and https://twitter.com/kristsi/status/720909413733789696.

**Comment by kerchner** [comment]
Others suggest that coding should not be removed.  Still up for debate.

**Comment by justinlittman** [comment]
Punting on this for now.
