### ISSUE TITLE
Move sfm ui message consumer into own container

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#198]
This way when the message consumer crashes, it can be set to automatically restart.

With the current configuration, there is no way to set it to automatically restart. It requires stopping and starting the entire sfm ui container.

**Comment by justinlittman** [comment]
In went part-way down this route and realized that it would require contortions with the settings files.  (Since the message consumer would require different apps installed.)  For now, came to the conclusion that this is more complicated than it is worth.

**Comment by kerchner** [comment]
Reopen for consideration in light of #274 .  If we're going to put a config for startup/non-startup of `apscheduler` then this might be easier to implement.

**Comment by justinlittman** [comment]
Not having this in separate container is causing operational difficulties, as (1) it doesn't automatically restart when it fails and (2) it does not have its own logs.

**Comment by justinlittman** [comment]
Fixed by:
* https://github.com/gwu-libraries/sfm-ui/pull/632
* https://github.com/gwu-libraries/sfm-docker/pull/15

**Comment by justinlittman** [comment]
To account for this change in the development environment, when you next pull development containers you will need to add the uiconsumer configuration to your `docker-compose.yml`.  See `example.docker-compose.yml`.
