### ISSUE TITLE
Update rabbitmq hash in docker-compose files to match sfm-docker prod.docker-compose.yml

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#202]
In 0.5.0, the rabbitmq image hash in sfm-docker/prod.docker-compose.yml was updated to a more recent image.   However, we should also update the same in example.docker-compose.yml files across the various repos to match.

**Comment by Tanych** [comment]
@kerchner If we update the `example.docker-compose.yml`, we also need to update `sfm-*-havester`.

**Comment by kerchner** [comment]
Merged via multiple PRs above.
