### ISSUE TITLE
Rename "seedset"

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#208]
Current term "seedset" does not work for harvests that don't have seeds. Replace with something more universally applicable.

**Comment by kerchner** [comment]
@lwrubel Add candidate terms (so far) from Slack conversation.

**Comment by kerchner** [comment]
This needs to be changed on a very stable code base.  Isolating as its own milestone.

**Comment by lwrubel** [comment]
Possibilities:
harvest set, subcollection, collection part, collector, harvest strategy, harvest definition, harvest plan, job, job plan, pipe, net, map, funnel

**Comment by lwrubel** [comment]
Will go forward with the terminology:

Collection Set > Collection > [optional: Seed]

**Comment by justinlittman** [comment]
PRs for this ticket:
* https://github.com/gwu-libraries/sfm-ui/pull/293
* https://github.com/gwu-libraries/sfm-utils/pull/14
* https://github.com/gwu-libraries/sfm-flickr-harvester/pull/7
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/12
* https://github.com/gwu-libraries/sfm-weibo-harvester/pull/15

**Comment by lwrubel** [comment]
Closed with #293 .
