### ISSUE TITLE
Harvest history

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#211]
Determine where and how to display recent harvests and results. Could be a separate page.

**Comment by kerchner** [comment]
@justinlittman add linkage to the PR that implemented this.

**Comment by justinlittman** [comment]
This is https://github.com/gwu-libraries/sfm-ui/commit/841ef22ea7ffc4ffe14d96cd41cee80c79244c6d in https://github.com/gwu-libraries/sfm-ui/pull/236
