### ISSUE TITLE
Update export UI for different types of seed sets

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#219]
Once #181 is completed, the export UI should be updated for the following:
* On the export create page, the option to select seeds should only be available if a seed set has multiple seeds.
* On the export details page, if an export has multiple seeds, those seeds should be displayed. If an export is for a seedset that can have multiple seeds, then "All seeds will be exported" should be displayed. If an export is for a seedset that cannot have multiple seeds, then nothing will be displayed.

refs #172.

**Comment by kerchner** [comment]
@justinlittman to verify whether this is already done.

**Comment by lwrubel** [comment]
@justinlittman the issue recommends adding "All seeds will be exported" on the export detail page, for exports on collections that handle multiple seeds. I'm not seeing that, although I see the help text on the export create page that all seeds will be exported. 

On the export detail page, some confirmation that all seeds were included, even if slightly different wording (e.g. "All seeds selected.") would be helpful. Unless I'm not understanding something here.

**Comment by kerchner** [comment]
Ref PR #372

**Comment by kerchner** [comment]
This is done.
