### ISSUE TITLE
implement flickr harvester

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#22]
In support of #16.

**Comment by justinlittman** [comment]
Here's the pull request for this ticket:  https://github.com/gwu-libraries/sfm-flickr-harvester/pull/1

@dchud - This pull request needs a reviewer assigned.

**Comment by dchud** [comment]
@dchud will review independent of sfm-ui work.

**Comment by justinlittman** [comment]
Based on yesterday's discussion, the following changes are necessary:
* Update for changes in messaging spec.
* Fix formatting of README.
* Remove flickr_photo as harvest type from docs.  It's just confusing.
