### ISSUE TITLE
Processing environment

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#227]
It should be super-easy to iterate over social media content, e.g., to run analysis.

Thus, we should provide either a docker container or a pre-loaded virtualenv (at root of /sfm-data) that has the various warc iterators.  Probably also want to add a warc-find utility that can find the WARCs associated with a collection or seed set for feeding to warc iterators.  Also might want to include twarc tools.

**Comment by justinlittman** [comment]
Additional PRs for this ticket:
* https://github.com/gwu-libraries/sfm-utils/pull/12
* https://github.com/gwu-libraries/sfm-docker/pull/3

**Comment by kerchner** [comment]
Fixed in:
https://github.com/gwu-libraries/sfm-ui/pull/238
https://github.com/gwu-libraries/sfm-utils/pull/12
https://github.com/gwu-libraries/sfm-docker/pull/3
