### ISSUE TITLE
Enhance Credential view to display which Seedsets are using this Credential

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#242]

**Comment by kerchner** [comment]
Consider improving UI to inform user why a credential used on another twitter filter isn't available.

**Comment by justinlittman** [comment]
Comment from Maria at IA:

> I was also thinking that listing out credentials onto a table might also be useful. This way the user could quickly see what credentials they’ve used for each collection. Right now you have to click in to view it and I found myself getting confused about which ones I’d used & where.
