### ISSUE TITLE
Weibo Harvester Options

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#244]
Weibo posts have tree differents type links ( see https://github.com/gwu-libraries/sfm-weibo-harvester/issues/2#issuecomment-202580546). There are lots URLs invovled photos, Weibo short URLs and Weibo full URL in per post. The option function can reduce the burden of the web harvester.
Ref. #176

**Comment by kerchner** [comment]
Fixed in https://github.com/gwu-libraries/sfm-weibo-harvester/issues/12
