### ISSUE TITLE
Functionality issues in adding Weibo timeline

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#247]
### 1. Collection update
When I try to update the collection page, it occurs the following error:
```python
'collection_pk'
Request Method:	GET
Request URL:	http://localhost:8080/ui/seedsets/1/update/
Django Version:	1.8.8
Exception Type:	KeyError
Exception Value:	
'collection_pk'
Exception Location:	/opt/sfm-ui/sfm/ui/views.py in get_context_data, line 174
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/opt/sfm-ui/sfm',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Wed, 11 May 2016 10:57:42 -0500
```
### Reason
In [url.py](https://github.com/gwu-libraries/sfm-ui/blob/293ae0e2c155928ca94229a5e78f424523b38ca2/sfm/ui/urls.py#L32), the url parameter is `pk`, but it calls with `collection_pk` in [views.py](https://github.com/gwu-libraries/sfm-ui/blob/293ae0e2c155928ca94229a5e78f424523b38ca2/sfm/ui/views.py#L174). We can change either side to fix the issue.

**Fixed** by  https://github.com/gwu-libraries/sfm-ui/commit/c8a062aa6d1153ce12770b6779d672633cdbb07f#diff-5f076dc3f0e71f8a63564ea39bc885a3R180

### 2 Seedset name is non-ASCII character
It's the same issue with https://github.com/gwu-libraries/sfm-ui/issues/186.  When the seedset name is chinese characters, the message format at https://github.com/gwu-libraries/sfm-ui/blob/master/sfm/message_consumer/sfm_ui_consumer.py#L150 raises this error.

### 1 Credential
The seedset page will list all the credential objects when adding a Weibo timeline seedset. It's a little hard to find the correct one if there are lots of credentials. It looks like this:
*  Credential 1 "Weibo"
*  Credential 2 "Weibo"
*  Credential 3 "Weibo"

We can list the credential name or something readable to users.

### 2 Schedule
The schedule field in seedset page has four choices--**hour, day, week and 4 weeks**. However, it doesn't much fit for Weibo timeline because of the losing data issues.  The details have been documented in https://drive.google.com/open?id=1M1ma8_ROQxlFMeNVSDhthlYodkwiP3DCIo2oS81WaAs
The better choices might be **20 mins, half hour, hour and 12 hour**. 

### 3 End date
The format of the end date in the harvester page is not showing to the users.

### 4 Harvester Options
Weibo harvester has involved functions related to collecting media or web resources.  Whether it needs to add the photo size options for collecting the photos? 

### 5 Exporter with uid
The uid field locates in the seeds page. The exporter can filter the Weibo post data relying on the seeds' uids. However, the Weibo harvester is seedless. It might a problem when exporting the data with uid. For example, someone follows ten users, but it only needs to export two followers' harvester data.

**Comment by kerchner** [comment]
@Tanych confirms this is done.
