### ISSUE TITLE
Tweaks to export page

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#255]
Display token/uid for seeds instead of object names.

**Comment by kerchner** [comment]
Recommend updating 'Dedupe' label to 'Deduplicate' (avoid jargon) in https://github.com/gwu-libraries/sfm-ui/blob/master/sfm/ui/templates/ui/export_detail.html#L35

**Comment by lwrubel** [comment]
Functionality added with #263. Still need to discuss label suggestion from @kerchner

**Comment by lwrubel** [comment]
Fixed and committed to master.
