### ISSUE TITLE
Support branding of UI

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#257]

**Comment by kerchner** [comment]
Also include contact info as part of branding info.

**Comment by kerchner** [comment]
Summer 2016 implementation should be min.

**Comment by kerchner** [comment]
- include a contact address for assistance.

**Comment by lwrubel** [comment]
@lwrubel suggest further detail on this ticket

**Comment by kerchner** [comment]
@lwrubel will propose a scope for this ticket

**Comment by lwrubel** [comment]
Assignment for work to implement branding TBD, likely @Tanych or @adityadharne

**Comment by lwrubel** [comment]
Contact email address. 
Institution name
Institution URL
Institution logo

Consider .env file as location for these elements.

**Comment by lwrubel** [comment]
Create a new, separate setting in .env for contact email (different from admin email). After discussion, put institutional info in the footer.

**Comment by justinlittman** [comment]
@lwrubel Does the institutional info appear as you'd like?
![screen shot 2017-01-18 at 8 34 11 am](https://cloud.githubusercontent.com/assets/588335/22066039/ffaadbec-dd58-11e6-8c0d-10cdfaa43bc2.png)

**Comment by justinlittman** [comment]
This is tested and good to go once @lwrubel approves institutional info.

**Comment by justinlittman** [comment]
Pull requests:
* https://github.com/gwu-libraries/sfm-docker/pull/14
* https://github.com/gwu-libraries/sfm-ui/pull/617

These will need to be squashed/rebased before merge.

**Comment by lwrubel** [comment]
Per discussion, make institution name and link configurable, remove copyright reference. Everything else looks good.

**Comment by Tanych** [comment]
@justinlittman  
make some tweaks on PRs 
* https://github.com/gwu-libraries/sfm-docker/pull/14
* https://github.com/gwu-libraries/sfm-ui/pull/617

The default value is `gw libraries`  with the corresponding links, it looks like:

![new_footer](https://cloud.githubusercontent.com/assets/3956411/22434678/ff498d60-e6ea-11e6-8e5b-9777c4008b90.png)
Please take a look at it.

**Comment by justinlittman** [comment]
Also, https://github.com/gwu-libraries/sfm-docker/commit/6b2e8ea78eca819a94c9bb97873b35a471b14eb6
