### ISSUE TITLE
Restrictions on Weibo authorization using django allauth

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#264]
## Limitations
To be frank, it's complex and not easy to make the a web application pass the official application review.  It's the same situation to what we have tried at the beginning of the project. Only the application owner and the 15 test users(once added in the application management, the test users can't be edited) can use the API. 

## Test information
Adding Weibo django allauth in sfm-ui.
```python
 sociallogin.token.app.provider == 'weibo':
            form = CredentialWeiboForm({
                'name': credential_name,
                'platform': Credential.WEIBO,
                'api_key': sociallogin.token.app.client_id,
                'api_secret': sociallogin.token.app.secret,
                'redirect_uri': "http://gwu-libraries.github.io/sfm-ui",
                'access_token': sociallogin.token.token,
            })
```
### Configuration 
  - WEIBO_API_KEY=1983438406
  - WEIBO_API_SECRET=fe6ce4c477f059b58c986d5224f48a6d

### Test case - Log in with the **application owner**
* Result: sfm-ui can get the access token successfully.

### Test case - Log in with **normal weibo account**
* Result: Unexcept error
```python
Request Method: 	GET
Request URL: 	http://127.0.0.1:8080/accounts/weibo/login/callback/?state=vZO8wmTjF3DP&code=c6a9d9ba4a4b3bdfd4e3393a92f5f039
Django Version: 	1.8.8
Exception Type: 	KeyError
Exception Value: 	

'idstr'

Exception Location: 	/usr/local/lib/python2.7/dist-packages/allauth/socialaccount/providers/weibo/provider.py in extract_uid, line 25
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
```

* Reason 

The Weibo application authorization process seems only work smoothly for the audited application.  For the unaudited application, it has lots of limitations to make the application widespread.

### Refers
[Official answers](http://open.weibo.com/wiki/index.php?title=%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98&diff=13494&oldid=13487) for the unaudted application.

**Comment by kerchner** [comment]
For 0.6, hide the "Connect Weibo Account" button.

**Comment by Tanych** [comment]
To hide the `connect Weibo Account`, the docker yml file for sfm-ui shouldn't include the environment value `WEIBO_API_KEY` and `WEIBO_API_SECRET`.
