### ISSUE TITLE
Usability scrub

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#281]
Review locations of elements on screen, flow, etc.  and update as needed

**Comment by justinlittman** [comment]
See https://github.com/gwu-libraries/sfm-ui/tree/t281-scrub

**Comment by lwrubel** [comment]
@justinlittman: pls add a notificaiton that confirms turn on/off happened, separate from the next harvest message.

**Comment by kerchner** [comment]
Add links to project site and readthedocs (recommend in footer)

**Comment by lwrubel** [comment]
oops, I put the footer with placeholder links in #282. I think it's fine for me to carry on with it there unless anyone sees a need to have that work merged into this branch.
