### ISSUE TITLE
UI should warn user if they are trying to run a filter with credentials already in use 

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#285]
Only one filterstream can run at a time with the same set of credentials.

**Comment by kerchner** [comment]
This does not need to prevent multiple REST harvest Collections with the same credentials (vs. filter harvest Collections).   We'd have to determine whether Twitter's API allows simultaneous use of filter and REST API with the same credentials.

**Comment by kerchner** [comment]
Allow credential to show up in the dropdown (selection of credentials), but don't allow the user to turn on collection of the stream.   Present a message stating that you can't turn on the filter because the credential is already in use by another filter (specify which filter, if possible).

**Comment by Tanych** [comment]
The message notification would be like this:
The credential twitter-victor(_credential name linked to the credential_) is using by twitter search: twitter filter 1(_twitter search name linked to the collection details page_),  twitter filter 2,  twitter filter 3. Please stop them first, if you want to do the twitter filter.

So the credential is in use only by twitter filter, how about the credential is using by twitter search or twitter sample? Do I also need to forbid turning on if someone adds a twitter filter?
