### ISSUE TITLE
Add Flickr and Weibo to processing environment

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#288]
For use in a processing environment, for instance.

**Comment by kerchner** [comment]
@justinlittman based on your comments on #228 are you inclined to mark this as Wontfix?

**Comment by justinlittman** [comment]
@kerchner I'd be inclined to recast this ticket as just done and push to 0.6.2.

**Comment by justinlittman** [comment]
Following add dev_no_warcprox.txt:
* https://github.com/gwu-libraries/sfm-weibo-harvester/commit/c3deea62e1665f00075360671ef28b988f6405a7
* https://github.com/gwu-libraries/sfm-flickr-harvester/commit/2e2cd0e599f68526866c0b62914fecd0e18d3ed1

**Comment by justinlittman** [comment]
See https://github.com/gwu-libraries/sfm-docker/commit/8ca988353bea876dc2e1f228c2ee3a07d7203891.
