### ISSUE TITLE
Pin particular version of packages

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#29]
In the docker install, apt-get install is used to install a number of packages.  The versions of these packages could change from one build to the next, harming the stability and reproducibility of our builds.  The particular versions should be pinned.

To install the specific version simply run:
````
    apt-get install <package name>=<version>
````

e.g.
````
    apt-get install subversion-tools=1.3.2-5~bpo1
````

**Comment by justinlittman** [comment]
We're currently encountering a problem building containers that upgrade pip to 8.0.0.  7.1.2 works fine.

**Comment by justinlittman** [comment]
To find the version of a dependency:  `apt --installed list | grep gettext  `

**Comment by justinlittman** [comment]
PRs for this ticket:
* https://github.com/gwu-libraries/sfm-ui/pull/131
* https://github.com/gwu-libraries/sfm-flickr-harvester/pull/3
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/3

**Comment by justinlittman** [comment]
Strategy is to place app packages in requirements/requirements.abt.  Install dependencies (e.g., zip and git) are pinned in Dockerfile.

**Comment by kerchner** [comment]
Resolved by the above three PRs
