### ISSUE TITLE
Graceful shut down of harvesters/exporterts

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#302]
For the purposes of performing upgrades, there needs to be a way of gracefully shutting down harvesters/exporters (i.e., completing the current request and handling no more).

**Comment by justinlittman** [comment]
And in general, need a procedure for performing upgrades to the SFM that minimize negative impacts.

**Comment by justinlittman** [comment]
http://stackoverflow.com/questions/37515686/stop-a-running-docker-container-by-sending-sigterm
https://docs.docker.com/engine/reference/commandline/stop/
https://medium.com/@gchudnov/trapping-signals-in-docker-containers-7a57fdda7d86#.9ragb8vc8
https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/
http://engineeringblog.yelp.com/2016/01/dumb-init-an-init-for-docker.html

**Comment by justinlittman** [comment]
Here's my thoughts on this ticket:
1.  The general process for an upgrade should be `docker-compose stop` then `docker-compose pull` then `docker-compose up -d`.  Note that `docker-compose stop` will send a SIGINT and then 10 seconds later a SIGKILL.
2.  Each container should manage its own temp space.  That temp space should be in /sfm-data.  Containers should cleanup the temp space as necessary, e.g., after an unclean shutdown.
3.  Optional retry functionality should be added to the BaseConsumer.  This will persist a message to disk when it is received and delete it when processing is completed.  If the message is found on startup it will be retried.  What happens on retry depends on the BaseConsumer implementation.
4.  The exporters, web harvester, and elk loader should cleanup any files and retry.
5.  The other harvesters should resume.  See below for changes to BaseHarvester.

Changes to BaseHarvester to support resuming:
1.  Upon starting a harvest, the harvester should send a harvest status message with status PROCESSING.
2.  A separate process/thread should monitor for completed WARC files.  (For warcprox, files have a .open extension until completed.)  Upon finding a completed WARC file, it should iterate over the WARC for the purposes of determining state (note that this is the state of the harvest that is actually committed to completed WARCs, not that is in an interdeterminate state as seen by the social media client), extracting URLs, and making counts.  Upon completing, it should move the file, send a WARC created message, send web harvest requests, and send harvest status messages, persist state, and persist counts.  (Note that the need to persist counts was previously noted, but left as a todo.)
3.  To resume (i.e., when a message is found on disk on startup), any remaining completed WARC files are processed.  Then the harvest is resumed based on the persisted state.

**Comment by kerchner** [comment]
Also entails updates to Twitter, Flickr, Tumblr, and Weibo harvesters and exporters.

**Comment by justinlittman** [comment]
Here's how this works for all harvesters and exporters except Twitter Stream Harvester:
When a harvest/export request is received, the message is persisted to disk.  When it is completed, the persisted message is deleted.  When the harvester/exporter is started, it looks for persisted messages.  If it finds one, is executed it before starting to consume from the queue.

When executing a persisted message on start, the exporter always starts over.  Thus, if it was in the middle of an export when it was stopped, it starts from scratch.

During execution, a harvester checkpoints itself whenever it processes a WARC file.  Checkpointing consists of copying the WARC file to its destination, updating state in the state store, and persisting the counts to disk. Thus, when executing a persisted message on start the harvester will continue for the last state in the state store and the counts from disk.

For the Twitter Stream Harvester, restart is automatically handled by supervisor.  Upon reaching a stop signal, the harvester will attempt to stop harvesting tweets and close warcprox.  Closing warcprox will also close the WARC file, allowing it to be processed now or on a later resume.

**Comment by justinlittman** [comment]
Here are the PRs for this ticket:
* https://github.com/gwu-libraries/sfm-utils/pull/17
* https://github.com/gwu-libraries/sfm-flickr-harvester/pull/9
* https://github.com/gwu-libraries/sfm-weibo-harvester/pull/19
* https://github.com/gwu-libraries/sfm-tumblr-harvester/pull/4
* https://github.com/gwu-libraries/sfm-web-harvester/pull/3
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/16

**Comment by justinlittman** [comment]
Suggestions for testing:
* You will need to build the containers.
* Attached is an example [docker-compose.yml](https://github.com/gwu-libraries/sfm-ui/files/474788/docker-compose.txt).
* Test every harvest and export type.
* Test killing a container during a harvest/export.
* Test killing Twitter Stream Harvester during a harvest.
* Test shutting down all containers with `docker-compose stop` during harvests/exports.
* Run all of the unit and integration tests.

Note that the travis tests will fail since they depend on changes to sfmutils and containers.

**Comment by justinlittman** [comment]
@kerchner This is ready to go for testing.

**Comment by kerchner** [comment]
Fixed by #444
