### ISSUE TITLE
Need mechanism for monitoring harvesters/exporters

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#303]
Both whether they are up and what they are working on and how far they've gotten on what they're working on.  Other than peeking at the logs.

**Comment by kerchner** [comment]
Also consider monitoring components such as UI app, message queue, etc. - health check.

**Comment by justinlittman** [comment]
Branches for this ticket:
* https://github.com/gwu-libraries/sfm-ui/tree/t303-monitor
* https://github.com/gwu-libraries/sfm-utils/tree/sfm_303-monitor
* https://github.com/gwu-libraries/sfm-docker/tree/sfm_303-monitor

**Comment by justinlittman** [comment]
I scoped this ticket down to functionality that could be added with a low effort level, but provided a reasonable first cut at monitoring.

**Comment by justinlittman** [comment]
To create test environment:
* Add `RABBITMQ_MANAGEMENT_PORT` to environment for ui. See https://github.com/gwu-libraries/sfm-docker/compare/sfm_303-monitor for changes to be made to docker-compose.yml file.
* Run all containers in dev:
```
UI_REQS=dev
TWITTER_REQS=dev
FLICKR_REQS=dev
TUMBLR_REQS=dev
WEIBO_REQS=dev
WEB_REQS=dev
```
Also, make sure that code is linked in.  For example:
```
        volumes:
            - "../sfm-twitter-harvester:/opt/sfm-twitter-harvester"
            - "../sfm-utils:/opt/sfm-utils"
            - "../warcprox:/opt/warcprox"
```

To test:
1. After startup, click Monitor on the header. Notice that there is no status or queued requests.
2. Create some harvests and exports.  Notice that there statuses appear in Monitor for harvesters and exporters.  Notice that only the most recent harvest/export that is handled is listed.  Note unless your timing is really good, you won't see any queued requests.
3.  Kill a harvester and exporter.  Now create some harvests for the killed harvester and exports for the killed exporter.  Notice that queued requests are now listed.
4.  Kill UI and bring back up.  Monitors should still appear properly, though it will list new harvester/exporter instances. (One is the old instance, the other is the new instance.)

**Comment by justinlittman** [comment]
Here are the PRs for this ticket:
* https://github.com/gwu-libraries/sfm-ui/pull/499
* https://github.com/gwu-libraries/sfm-utils/pull/22
* https://github.com/gwu-libraries/sfm-docker/pull/9

**Comment by justinlittman** [comment]
@lwrubel This ticket is ready for testing.
