### ISSUE TITLE
Determine how to order list views

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#307]

**Comment by kerchner** [comment]
(Where "alphabetically" means non-case-sensitive)
- Order home page view alphabetically
- Order collection sets alphabetically
- Collections list
- Seeds list
- Harvests list - reverse chronological - including when you click to the /harvests paginated view
- Credentials list
- Change log (appears to be fine as-is)
- Exports (appears ok - verify whether or not this is paginated)
If you come across any other lists, please ask!

**Comment by adityadharne** [comment]
@kerchner @lwrubel @justinlittman The exports list is not paginated and currently is in the reverse chronological order, does this need to change?

**Comment by kerchner** [comment]
The order is fine as-is.  We can add pagination later as a separate ticket if we determine it's needed.
