### ISSUE TITLE
In-app help

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#309]

**Comment by kerchner** [comment]
@lwrubel to link related tickets to this one, and/or merge into this ticket.

**Comment by lwrubel** [comment]
* See #319 for query help.
* Add example help text for adding a seed. Although SFM will strip the @ sign from screen-names, it's still confusing for users. Flickr screen names (which have spaces) should be included too.

**Comment by kerchner** [comment]
See #353 - for in-app help, add text to bulk add form that the list should be account names, not UIDs.

**Comment by lwrubel** [comment]
Addressing #348 to add group field help text.

**Comment by lwrubel** [comment]
Partially addressing #353 by changing help text on bulk add forms.

**Comment by kerchner** [comment]
As per comment in PR #393, alerting about needing to turn off a collection to add seeds will be addressed in #392.
