### ISSUE TITLE
plan for integrating optional django shibboleth support with docker

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#31]
Probably using https://github.com/KonstantinSchubert/django-shibboleth-adapter

**Comment by dchud** [comment]
See notes on #4.

**Comment by dchud** [comment]
There are a few options for approaching this - might be worth scheduling time with dev team to discuss before proceeding.

**Comment by kerchner** [comment]
As per discussion with @dchud , going to try using https://pypi.python.org/pypi/djangosaml2/

**Comment by dchud** [comment]
For this ticket, bring back a sketched out plan for the library you think fits best, where it integrates in the django/apache/docker environment, and what our next tickets should be.

**Comment by justinlittman** [comment]
Supplanted by #450
