### ISSUE TITLE
Simple SFM overview from project site

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#316]

**Comment by justinlittman** [comment]
@lwrubel - Here are my comments for your consideration:
* It seems like 3 different font sizes are used in the body.  I found that disconcerting.
* "linked from" to "linked from or embedded in"
* "SFM documents the steps" is in the first and second sections.
* "researchers, students, librarians, archivists" needs an "and".
* I found the "How might I use SFM?" section confusing.  I couldn't tell if these were supposed to be a set of steps or just a list of things.
* I would omit the export detail page screen shot.
* "Feed data into your own processing pipeline." to "Feed data into your own processing pipeline from the command line."
* I agree with you that I don't like the term "immature."

**Comment by lwrubel** [comment]
After much annoying css and theme fiddling, I've got this to a point where I think it addresses the comments (thanks for those!).

**Comment by justinlittman** [comment]
You nailed it.

A few minor comments for your consideration:
* In the steps, we list monitoring before turning on collecting.
* Add a screenshot of the command line.

These are not critical and can be addressed later (if at all).

Perhaps we should ask Robin D. to take a look at it?  (Again, not critical.)
