### ISSUE TITLE
Allow user to have multiple credentials per platform.

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#317]

**Comment by Tanych** [comment]
### Possible name conflict
It might be just a user-friendly case not an issue. The default name for the credentials is the same, especially when users create credentials by connecting social media account. 
```
Name	Platform	Date Added	Active
victor's twitter credential	twitter	July 19, 2016, 1 p.m.	Yes
victor's twitter credential	twitter	July 19, 2016, 1 p.m.	Yes
```
The users need to rename the credentials if they try to keep the default name.

**Comment by Tanych** [comment]
I just rollback the `can_connect` social account in 4e4a05a35435b424f9ae15269639dda3a4323bfb . I think it might be a mistake deleted. 
Another case is that it added the same `credentials` keys and names when someone clicks the `connect to twitter account` multi-times. I am not sure whether it's an issue or the API only provides `a single access_token key` to one unique user.

**Comment by justinlittman** [comment]
@Tanych Do you know if this ticket is completed or if there is still outstanding work?

**Comment by kerchner** [comment]
Ref PR #375
