### ISSUE TITLE
Reconsider Twitter search

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#320]
When running a Twitter search for the Pulse shootings, but the following was observed:
* Search ran until it hit a rate limit, paused, and repeated.  The search never ended.
* All of this was recorded to a single WARC, which was never finished.
* Other harvest requests were blocked waiting for the search  to end.

Consider:
* Only running search backwards (which should be finite).
* Terminating search after a specific amount of time or number of tweets.

**Comment by Tanych** [comment]
I realize the same problem one week ago when I am trying to search NBA playoff. It needs to wait a long time to complete the search.

**Comment by justinlittman** [comment]
I've reviewed the Twitter search API docs.  The reality is that a search can take a long time given the number of possible tweets and rate limits.

I think the solution is to run multiple Twitter REST harvesters so that searches can run without holding up other harvest requests.  Also, suggest (in docs) against running long searches with too short a frequency.

I'm going to do some experiments with running multiple harvesters.

**Comment by justinlittman** [comment]
Also need to consider whether warcprox is holding open a single WARC file for an extended period (which can be risky) or creating multiple WARCs.

**Comment by kerchner** [comment]
Implemented by:
- https://github.com/gwu-libraries/warcprox/commit/b015e4ae804d32371bb0492d63b11c0504c4f319
- documentation updates to come

**Comment by kerchner** [comment]
Fixed in #444 and in the above change to warcprox.
