### ISSUE TITLE
In ELK, normalize hashtag capitalization

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#323]
Currently, hashtags with different capitalization are treated as different hashtags, e.g., top 10 hashtags report.

**Comment by Tanych** [comment]
### Possible Solution
We need to create a new indice using the [custom-analyzers](https://www.elastic.co/guide/en/elasticsearch/guide/2.x/custom-analyzers.html) to make the elasticsearch return the buckets with case insensitive.  There is no better way in Kibana level. 

### Refs
https://qbox.io/blog/elasticsearch-aggregation-custom-analyzer
https://www.elastic.co/guide/en/elasticsearch/guide/2.x/custom-analyzers.html

**Comment by Tanych** [comment]
The solution will post on the branch [hashtags](https://github.com/gwu-libraries/sfm-elk/tree/t323-hashtags_case). 
Currently, the hashtags visualization is using the `.raw ` fields to count the total number. However, the `.raw`  is setting `not_analyzed` which can't apply `tokenizer` analysis to the raw data. 
I apply the analyzer to the `hashtags` field and build the visualization based on it.
 
### Demo
![hashtags](https://cloud.githubusercontent.com/assets/3956411/16424509/6dcb907e-3d2e-11e6-800a-ee9c0af2a911.png)

| hashtags | Count |
| -------- | --------: |
| GWU	| 75 |
| 50DAYSOFFOIA	| 16 |
| FOIA	| 16 |
| BREXIT	| 10 |
| GWCLASSOF2020	 | 9 |
| SMPAPROUD	| 5 |
| ALAAC16 |	4 |
| BLACKLIVESMATTER	| 4 |
| DETAINEE	| 4 |
| NABA2016	| 4 |

Previously, hashtag `gwu` and `GWU` counted as separately.  Now, we make it all in capital letter.

**Comment by justinlittman** [comment]
This work is done. It just needs to be tested.

**Comment by justinlittman** [comment]
Completed by https://github.com/gwu-libraries/sfm-elk/pull/2
