### ISSUE TITLE
In ELK, add top retweets vizualization

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#324]

**Comment by Tanych** [comment]
The visualization only shows the retweets count, but people needs know the retweeted text or other details. So I think it's better to build a search to display the `text`,`retweet_count` and `screen_name`. 

|Time |	screen_name |	text |	retweet_count|
|-------|:-------:|:-------:|:-------:|
|June 24th 2016, 09:31:02.000|GWU_IAS|RT @WhiteHouse: “The United Kingdom and the European Union will remain indispensable partners of the United States” —@POTUS https://t.co/gI…|1,421|
|June 23rd 2016, 18:14:31.000|crandallkeith|RT @GWtweets: Washington, DC is the 2nd-most walkable city in the U.S. according to new research by #GWU and @SmartGrowthUSA🚶https://t.co/…|11|
|June 24th 2016, 11:27:00.000	|GWtweets	|RT @GWmedia: #Brexit: #GWU experts available to comment on UK’s decision to leave the EU ➡️ gwmedia@gwu.edu https://t.co/85ntfYmW2W|7|
|June 24th 2016, 11:58:54.000	|caitsummers	|RT @GWmedia: #Brexit: #GWU experts available to comment on UK’s decision to leave the EU ➡️ gwmedia@gwu.edu https://t.co/85ntfYmW2W|7|

However, if the two users retweeted the same, it will count multip-times.

**Comment by justinlittman** [comment]
Will add if requested by users.
