### ISSUE TITLE
Optional, public summary page for collection set

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#325]
This would list the collections, collection criteria, seeds, and a summary of collection stats.  It would NOT provide social media data.  It would be OPTIONAL.

**Comment by justinlittman** [comment]
Perhaps expose to web observatories?  http://www.webscience.org/how-to-get-involved-with-web-observatory/

**Comment by lwrubel** [comment]
After SFM discussion at RUS on 9/12, Zach wanted to show a UW1020 class what we have collected from the election collection. A public collection page would support this use case.

**Comment by justinlittman** [comment]
Replaced by #894.
