### ISSUE TITLE
Support for import / export of collection sets

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#326]

**Comment by justinlittman** [comment]
The original motivator for this was needing to move collections from a test instance to production (e.g., the Pulse collection).

Based on discussions with Chris Prom, it is clear that this will lay the foundation for #123.

**Comment by lwrubel** [comment]
Need to provide a way to export not just the data collected from the platforms, but the structure of the collection set, its collections, and its seeds. In addition to the uses described above, this supports scenarios for moving collected data into a repository and preserving its structure. This also provides a way for an institution experimenting with SFM to move an experimental collection into their production instance.

**Comment by justinlittman** [comment]
Some additional requirements:
* Add a README.txt to the collection set.
* Make collections inactive on import.
* Add something (change note?) to indicate that collection was imported and where it was imported from.

**Comment by justinlittman** [comment]
See this branch:  https://github.com/gwu-libraries/sfm-ui/tree/t326-export

Still to do:  in docker-compose.yml files remove ro from sfm-data volume in sfm-ui container.

**Comment by justinlittman** [comment]
Also still to do:  Make sure that collection is placed in correct collection set directory.

**Comment by justinlittman** [comment]
PRs for this ticket:
* https://github.com/gwu-libraries/sfm-docker/pull/10
* https://github.com/gwu-libraries/sfm-ui/pull/500

**Comment by justinlittman** [comment]
Suggestions for testing:
1. Read the new docs.
2. Create a collection.
3. Wait overnight, change the serialization time by adding env variables to sfm ui container in docker-compose, or run serializecollectionset management command.
4. Make a copy of the collection set files (from /sfm-data).
5. Kill and remove existing instance of SFM.
6 Start a new instance.
7. Move copied collection set into /sfm-data.
8. Run deserializecollectionset management command.
9. Verify that collection is correctly imported.

**Comment by justinlittman** [comment]
@Tanych This is ready for testing.
