### ISSUE TITLE
Make process container's link to data volume RO

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#331]
Because that way you can't destroy the data.

**Comment by justinlittman** [comment]
Probably want to add a second volume that is writable to put processed data on.

**Comment by lwrubel** [comment]
Need to explain in docs where to put work done in processing container and how to share in code you already have.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-docker/commit/4f5c6be7c280ff90ddb2260205bcba6f8375f7e2 changes the working directory to /sfm-data.
