### ISSUE TITLE
Issues on pre-1.0

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#333]
All the test cases based on master.docker-compose.yml in https://github.com/gwu-libraries/sfm-docker/commit/7707b700725a3379b332aa8998ba8a9053ef9461
### 1.Docker version 
Not sure whether the docker version could influence the performance of SFM. Do we need to specify the docker version to make the SFM perform stable.
### 2. Docker-compose `logs` exit
Following the instruction of docker and installing the `Docker 1.11` in the new machine. When I started up  with `up -d` and checked the logs with docker-compose `logs`, it exited instead of attaching containers until no more output.
### 3. Install failed when apache is running
It occurs the following information when apache is running. We can make a suggestion about stopping the apache service before installing SFM, or classify it into `Q&A` parts.
```bash
Error starting sfmuiapp: listen tcp 0.0.0.0:80: bind: address already in use
```
### 1.Twitter search
Twitter search blocks other kinds of twitter collections when searching a hot topic with bunches of tweets, such as `NBA` and `mass shooting`. It has been documented in #320 .
### 2. Real performance on twitter exporter
Ideally, it costs nearly one minute to export 15,000 tweets. However, it takes about 5 minutes to export 20,000 tweets in real collections. Logs could be like this:
```bash 
2016-06-14 12:37:17,740: sfmutils.warc_iter --> Processed 0 records. Yielded 0 items.
<--cut for brevity-->
2016-06-14 12:41:38,274: sfmutils.consumer --> Sending message to sfm_exchange with routing_key export.status.twitter.twitter_search. The body is: {
    "status": "completed success", 
    "errors": [], 
    "warnings": [], 
    "date_ended": "2016-06-14T12:41:38.274354", 
    "id": "b005322073614158bdfc5cfcfbf95ade", 
    "date_started": "2016-06-14T12:37:17.718480", 
    "infos": []
}
```
### 3.Twitter filter stream harvester
Twitter filter might cause an issue for web-harvester when collecting the hot topics. The twitter filter will run in every half hour but the web-harvester can't complete consuming the web message in the half hour. Then the new web message created in next period is coming. As a result, there are lots of web requests are pending.  It's the situation that the consumption ability is much less than the production ability. It will create lots of pressures for web-harvester.

The status are like this:
```bash 
Type	Date requested	Status	Messages
Web	June 14, 2016, 5 p.m.	Requested	0 messages
Web	June 14, 2016, 4:49 p.m.	Requested	0 messages
Web	June 14, 2016, 4:19 p.m.	Requested	0 messages
Web	June 14, 2016, 3:49 p.m.	Requested	0 messages
Web	June 14, 2016, 3:19 p.m.	Requested	0 messages
Web	June 14, 2016, 2:49 p.m.	Requested	0 messages
Web	June 14, 2016, 1:58 p.m.	Requested	0 messages
Web	June 14, 2016, 1:28 p.m.	Requested	0 messages
Web	June 14, 2016, 12:58 p.m.	Requested	0 messages
Web	June 14, 2016, 12:28 p.m.	Requested	0 messages
Twitter filter	June 14, 2016, 11:58 a.m.	Running	0 messages
```

### 1. Flickr export failed
Can't export the items collected from Flickr-harvester. The details are documented in #332 .
### 2. Real performance on export flickr
It relative slow to export flickr item. Exporting 480 items costs 12 minutes. The reason is the large number fo warc records. The exporting 480 items contain 900 warc records. It will cost a lot on I/O.
```bash
2016-06-14 18:21:12,712: sfmutils.warc_iter --> Processed 0 records. Yielded 0 items.
<--cut for brevity-->
2016-06-14 18:33:53,677: sfmutils.consumer --> Sending message to sfm_exchange with routing_key export.status.flickr.flickr_user. The body is: {
    "status": "completed success", 
    "errors": [], 
    "warnings": [], 
    "date_ended": "2016-06-14T18:33:53.677203", 
    "id": "f509ddb8e2334c29b7e57baadd9d4637", 
    "date_started": "2016-06-14T18:21:12.693761", 
    "infos": []
}
```

**Comment by justinlittman** [comment]
Having fixed #332, I'm comfortable with these issues for 1.0.0. Let's
discuss for post 1.0.0.

**Comment by justinlittman** [comment]
And thanks @Tanych!

**Comment by kerchner** [comment]
@Tanych has created tickets for any issues still open.
