### ISSUE TITLE
resume for requested tasks when it failed

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#345]
If the tasks are failed, it will pending on `requested`. it's  better to resume these tasks when apps have been restarted next time.
### Example:
The exporting task failed because of some configurations or unexpected errors. The status will always be `requested`. 

|Export from|	Status|	Date Requested|
|----|----|----|
|performance_test > Flickr_user_001|	completed success	|June 21, 2016, 3:28 p.m.|
|performance_test > Flickr_user_001|	requested|	June 21, 2016, 3:23 p.m.|

**Comment by kerchner** [comment]
Consider long-running message acknowledgements

**Comment by justinlittman** [comment]
Being fixed as part of #302

**Comment by kerchner** [comment]
Fixed in #444
