### ISSUE TITLE
Adding seeds in bulk that include suspended or not-found twitter user timelines does not yield expected results

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#346]
This area needs additional testing.  I bulk-added these twitter user timeline seeds, and turned on the collection:

```arbaramzi45F
helpingmuslim
rah622
AntiZionism
amin9j8
AbuYahy3205
salfitariq
Khalidgojanfar
Mountainnnnnsss
ramadansitting
```

This set contains three accounts that, as of 24-June-2016, do not (or, no longer) exist as named:
```
AbuYahy3205
Khalidgojanfar
arbaramzi45F
```
and one account that, as of 24-June-2016, is suspended:
```
helpingmuslim
```

Results:
- The Harvest came back as "Success" with a warning message of:  `User id not found for user arbaramzi45F`
- UIDs were not added for any seeds in the collection
- A 2.1 KB warc file was created (essentially no harvested content)

**Comment by justinlittman** [comment]
See https://github.com/gwu-libraries/sfm-twitter-harvester/pull/15

**Comment by kerchner** [comment]
Resolved in https://github.com/gwu-libraries/sfm-twitter-harvester/pull/15
