### ISSUE TITLE
Consider option for getting screen capture of capture web pages

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#349]
Consider providing option to get PNG and/or PDF of web pages, in addition to the crawls of the HTML, possibly using tools such as wkhtmltopdf and wkhtmltoimage.

See Ruest and Milligan: [The Great WARC Adventure](http://www.digitalstudies.org/ojs/index.php/digital_studies/article/view/325/412)

**Comment by justinlittman** [comment]
No requests from users.
