### ISSUE TITLE
Change log help text/in-app help

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#350]
Consider example text or prompts for Change Log field, especially for what might be appropriate using the Create form vs Update.

**Comment by save4use** [comment]
For Update: "Enter text explaining why you made these changes at this time"

For Create, I wonder if we actually want to give people the option of adding anything to the change log, or if we just want to encourage them to use the collection, group, etc. description field. I'm having a hard time coming up with what would go into a change log note at the time of creation that wouldn't be better suited to the description field.

**Comment by lwrubel** [comment]
Thanks @save4use. I started with that text and made it a little shorter. I left the field in the Create forms for now, so we can get some feedback on any possible use cases, but changed the wording to imply that there are other places you might have put info already, as you pointed out.

For Update: "Explain why you made these changes at this time."
For Create/Add: "Further information about this addition."
