### ISSUE TITLE
Twarcbase spark twitter analysis

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#352]
The main idea is that feeding SFM dataset into [twarcbase](https://github.com/lintool/warcbase), and the twarcbase can handle huge volumes of data and do some basic twitter analysis. However, I have some questions below.

### Dataset
SFM only save bunches of WARC files. If we feed the WARC files to twarcbase, it should support loading and analysis tweets from these files. If using the JSON tweets, SFM needs to save these files or support calling the `scala` API provided by twarcbase.

### Duplicate
Duplicating is the main issue when I do the demos. I have no idea whether the twarcbase can handle the duplicate tweets. The demos have double the results when I try to feed into the same tweets twice.

### Visualizations
How to directly display the tweet analysis? More works need to do based on spark.

**Comment by Tanych** [comment]
@justinlittman 

Some trials for the [Twarcbase](https://github.com/lintool/warcbase-resources), as a reference, I will  compare the `Top-10-URL` results between `Twarcbase` and `ELK`.
## Testing sample
Three samples are used to get the top 10 URLs. The keywords and scale of tweets in JSON files show below:
* GWU: 2k
* NBA Playoff: 1k
* Apollo11: 50K

## Result
Using the `Twarcbase` [example](http://lintool.github.io/warcbase-docs/Spark-Twitter-Analysis/) to extract the top 10 URLs in JSON files. The comparison of three samples is as follow:
### 1. GWU

**Twarcbase**

 ```
16/07/21 12:59:05 INFO storage.ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
16/07/21 12:59:05 INFO executor.Executor: Finished task 0.0 in stage 20.0 (TID 46). 1371 bytes result sent to driver
16/07/21 12:59:05 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 20.0 (TID 46) in 2 ms on localhost (1/1)
16/07/21 12:59:05 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 20.0, whose tasks have all completed, from pool 
16/07/21 12:59:05 INFO scheduler.DAGScheduler: ResultStage 20 (take at <console>:56) finished in 0.004 s
16/07/21 12:59:05 INFO scheduler.DAGScheduler: Job 7 finished: take at <console>:56, took 0.006805 s
r: Array[(String, Int)] = Array((http://bit.ly/20pydHp,1), (http://t.co/0kEgkkDjFW,1))
```

The top 10 result only shows 2 URL with 1 match.

**ELK**
The ELK get the shorten results from the [entities](https://dev.twitter.com/overview/api/entities-in-twitter-objects#urls)

|URL|Count|
|:-------:|:-------:|
|https://t.co/rdo7si41t8 | 179 |
|https://t.co/7h48RYZeBd | 147 |
|https://t.co/1S2xqfgCDF | 50 |
|https://t.co/4kO9kB0eAW | 25|
|https://t.co/SRJlzblROx | 21 |
|https://t.co/azckElcyuZ | 17 |
|https://t.co/27WOWZpEx1 | 12 | 
|https://t.co/2as1iDVNlL | 12 |
|https://t.co/Dvm2vzSpng	 | 11 |
|https://t.co/E4e06Xp8HR | 11 |


### 2. NBA playoff

**Twarcbase**
```
16/07/21 12:47:58 INFO storage.ShuffleBlockFetcherIterator: Getting 0 non-empty blocks out of 2 blocks
16/07/21 12:47:58 INFO storage.ShuffleBlockFetcherIterator: Started 0 remote fetches in 0 ms
16/07/21 12:47:58 INFO executor.Executor: Finished task 0.0 in stage 4.0 (TID 6). 1161 bytes result sent to driver
16/07/21 12:47:58 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 4.0 (TID 6) in 7 ms on localhost (1/1)
16/07/21 12:47:58 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 4.0, whose tasks have all completed, from pool 
16/07/21 12:47:58 INFO scheduler.DAGScheduler: ResultStage 4 (take at <console>:38) finished in 0.007 s
16/07/21 12:47:58 INFO scheduler.DAGScheduler: Job 1 finished: take at <console>:38, took 0.027577 s
r: Array[(String, Int)] = Array()
```
It's `None`. I have tried several times, the result is the same. I am not sure what's wrong with it.

**ELK**

|URL|Count|
|:-------:|:-------:|
|https://t.co/jVhpsFYwyr	|9|
|https://t.co/UtxoRBGzGF	|8|
|https://t.co/Ev77FlZs3Z	|7|
|https://t.co/k33Sm3HFUt	|7|
|https://t.co/JT1FZlXXj7	|6|
|https://t.co/1Us68yzOqP	 |4|
|https://t.co/U2Aa7b7A0l	|4|
|https://t.co/k8YMnjFGaK	 |4|
|https://t.co/ONpxZxwPgm	|3|
|https://t.co/ej41neGRuU	|3|


### 3. Apollo11

**Twarcbase**
```
16/07/21 12:49:45 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 12.0, whose tasks have all completed, from pool 
16/07/21 12:49:45 INFO scheduler.DAGScheduler: ResultStage 12 (take at <console>:47) finished in 0.009 s
16/07/21 12:49:45 INFO scheduler.DAGScheduler: Job 4 finished: take at <console>:47, took 0.019731 s
r: Array[(String, Int)] = Array((http://…,5), (http://t.co/NNz…,3), (http://t.co/OccWXA1v8R,2), (http://t.co/oa7GnJTeLw,1), (http://t.co/tUxycFt4M3,1), (http://t.co/uziTbyFfbF,1), (http://t.co/yOl…,1), (http://t.co/xEzjue6RZW,1), (http://t.co/Ng9rekRi4b,1), (http://t.co/4WMsipKbnF,1))
```
The result has `http://…` or `http://t.co/NNz…`. It's not real URLs.

**ELK**

|URL|Count|
|:-------:|:-------:|
|https://t.co/LXupuCUFmO	|3,190|
|https://t.co/mqhtBfzOrJ	|191|
|https://t.co/R3vIz7Zye0	|179|
|https://t.co/5NU0AUtPpf	|134|
|https://t.co/TzLtYFffAv	|131|
|https://t.co/O1tVSGX3vU	 |123|
|https://t.co/bG0q1IsT5C	|123|
|https://t.co/5NU0AULqgN	|122|
|https://t.co/sEW9FM9tUk	|122|
|https://t.co/588d4uJooj	|99|

I followed the instructions provided by Twarcbase and do the testing works. It might be something wrong with anywhere. The details of the trial works need to discuss.

**Comment by justinlittman** [comment]
This work is done for now.
