### ISSUE TITLE
Bulk add seeds UI should indicate that screen names or UIDs can be provided

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#353]
- The app allows adding either UIDs or screen names (ought to test to verify that a mixed list would work in bulk add), but the form field is labeled screen name(s).
- When account(s) are added by UID, the collection detail page lists the UIDs in the Tokens column rather than the UID column.  Perhaps consider labeling the token column as screen name for consistency with the Add Seed(s) forms.

**Comment by kerchner** [comment]
@kerchner to propose how the UI should work.

**Comment by lwrubel** [comment]
Note that if you enter Flickr nsid instead of screen name, the nsid gets saved as a user name. Will add clarification via #309.

**Comment by kerchner** [comment]
Closing this ticket, as:
- #309 has resolved the help labeling.
- Opening #404 to add ability for bulk upload by screennames OR by UIDs.  UIDs may be an important way to enter names as they're more stable.
