### ISSUE TITLE
Once a seed is entered by UID, there's no link to edit it

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#356]
Only the "token" (i.e. screen name) column is rendered as a link to the seed edit page.  This link will appear if and only if a harvest is run and it successfully populates the screen name.  Consider making both the token and UID fields link to its seed edit page.

**Comment by justinlittman** [comment]
Closed by https://github.com/gwu-libraries/sfm-ui/pull/364
