### ISSUE TITLE
Harvest and Export failure/warning notification improvements

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#357]
Include seed validation problems.  Also consider where/how to show notifications associated with seeds.

**Comment by kerchner** [comment]
Ref #346

**Comment by lwrubel** [comment]
Needs more consideration after 1.1.

**Comment by lwrubel** [comment]
Discuss and scope at meeting on 9/12.

**Comment by kerchner** [comment]
This would likely require changes to the Seed model to track status and/or other info.   Scope likely too much to fit in milestone 1.2, so removing from 1.2 for now.

**Comment by justinlittman** [comment]
Closing this general ticket.  If there are specific actionable changes, they can be ticketed separately.
