### ISSUE TITLE
Enforce authorizations consistently in UI

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#362]
See description of issue in: https://docs.google.com/document/d/1eCUsHB2x_gGvxItcfGPLfphOm9C8W7gC07Udxs3nC4k/edit#

**Comment by lwrubel** [comment]
Recommend including in 1.5

**Comment by justinlittman** [comment]
This ticket will consolidate #571 and #493, which will be closed.

**Comment by justinlittman** [comment]
Requirements are as follows:
1.  A user will only be able to view and edit collection sets, collection, seeds, harvests, and exports for groups with which she is affiliated.  This includes directly typing in a URL to get to a page.  On Monitor page (or any similar page), links will only be provided by items that the user can access.
2.  Staff can view all, but only edit those associated with groups with which they are associated.  A staff may request an export from all collections.
3.  Superusers can view and edit all.
4.  A user or staff can only view the credential details for her own credential.  This also includes the credential history.
5.  Superusers can view all credentials.

**Comment by kerchner** [comment]
0.  There are three levels of users:   User, Staff, Superuser
6.  Superusers can access the Django admin page (staff and users cannot)

Just to acknowledge, this is an expansion of the scope of the ticket, which was originally just to enforce the current scheme.

I assume with the scope as above that granting users higher roles would still occur via the django admin page.

With regard to #450, the implication seems to be that when implemented, #450 would authenticate users but groups/roles would be assigned within the SFM app, rather than pulling from LDAP group membership. (I would advocate for the former as being easier to manage).

**Comment by justinlittman** [comment]
This is probably part of the implementation approach:  https://docs.djangoproject.com/en/1.8/topics/auth/default/#django.contrib.auth.decorators.user_passes_test

**Comment by Tanych** [comment]
## User Level
create two users
* user1(group: user1) 
* user2(group:user2)

Building collection sets, collection and check whether they can view each other. 
### View and Edit Result
✓: mean can  X: mean can't

| collection set | collection | seeds | harvester | exporter | credential |
|----------------|------------|-------|-----------|----------|------------|
| X              | X          | X     | X         | X        | X          |

## Staff Level
create one staff and associated `user2`
* staff1(group:user2)
### Staff View Result
* Group user1

| collection set | collection | seeds | harvester | exporter | credential |
|----------------|------------|-------|-----------|----------|------------|
| ✓              | ✓         |✓     | ✓         | **X**        |  **X**         |

* Group user2

| collection set | collection | seeds | harvester | exporter | credential |
|----------------|------------|-------|-----------|----------|------------|
| ✓              | ✓         |✓     | ✓         | **X**      |  **X**        |

**For credential and exporter**, I am not sure whether it's a problem, the staff credential and exporter page doesn't show the list of items in other users. The staff can only view with typing the link like: `ui/credentials/1/` and `ui/exporter/1/` or accessing them trough the collections that have used those credentials.

![credential](https://cloud.githubusercontent.com/assets/3956411/21897152/ba2e0d60-d8b6-11e6-9a14-84418036eb6b.PNG)

The staff can login the admin page but nothing can do.

### Staff Edit Result
* Group user1

| collection set | collection | seeds | harvester | exporter | credential |
|----------------|------------|-------|-----------|----------|------------|
| X              | X          | X     | X         | X        | X          |

* Group user2

| collection set | collection | seeds | harvester | exporter | credential |
|----------------|------------|-------|-----------|----------|------------|
| ✓              | ✓         |✓     | ✓         | ✓        | ✓         |

## Superuser Level
### View and Edit Result
| collection set | collection | seeds | harvester | exporter | credential |
|----------------|------------|-------|-----------|----------|------------|
| ✓              | ✓         |✓     | ✓         | **X**         |  **X**         |

For the credential and exporter, it's the same note as the staff level.

## Other comments
We can custom the `403` page to make the user know why they are forbidden to access the pages.
