### ISSUE TITLE
Harvesting status emails

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#368]
It would be really reassuring if I received regular (daily?) emails about the status of harvesting for my collections.  Content of email TBD and presumably a user will have the option to opt out.

**Comment by justinlittman** [comment]
A user will have an email update flag. The flag will be enabled by default. For current purposes, that flag can be changed in Admin (not by user).

Once a day, for every user with the email update flag the user will be sent an email.

The email will contain information on each collection that is part of a collection set that the user has group membership in.

If the collection is turned off, it will be indicated that the collection is turned off.

If the collection is turned off, then the following will be provided:
* Information on the last harvest
* Date of the next harvest
* A comparison of the resources collected:
   * Yesterday vs previous day
   * Last 7 days vs. previous 7 days
   * Last 30 days vs. previous 30 days

**Comment by justinlittman** [comment]
User should have option of email frequency (daily, weekly, monthly).

**Comment by lwrubel** [comment]
Closed with #423.
