### ISSUE TITLE
Investigate use of warcprox

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#38]
As suggested by @edsu:

```
You probably know about it already but here is that warcprox thing I was mentioning:

        https://github.com/internetarchive/warcprox

It might make writing your components really easy if they simply talk through a proxy that records the WARC data. I think you might even be able to use a custom http header in the request to identify the job/collection/etc that the request is a part of, since multiple clients could be talking through the same proxy. Or perhaps a proxy could be spun up as part of any harvest, and then the WARC would only include content from that harvest.
```

**Comment by justinlittman** [comment]
Some notes on my investigation with using warcprox to capture requests from twarc:

1.  Bring up warcprox.
2.  Set proxy variables:

        export HTTP_PROXY=localhost:8000
        export HTTPS_PROXY=localhost:8000

3. Modify twarc to not verify certs by changing:

        resp = self.get(url, params=params)

to:

        resp = self.get(url, params=params, verify=False)

4. Run twarc.  For example:

        python twarc.py --search justin_littman


* I wasn't able to get this to work without setting verify to false.  I tried providing the various certs generated by warcprox to get with the `cert` parameter without success.
* Need to try with a stream.

**Comment by justinlittman** [comment]
Figured out how to get this to work without setting verify to false:

        resp = self.get(url, params=params, verify="/Users/justinlittman/tmp/GLSS-F0G5RP-warcprox-ca.pem")    

Alternatively, don't change twarc, but set:

        export REQUESTS_CA_BUNDLE=/Users/justinlittman/tmp/GLSS-F0G5RP-warcprox-ca.pem

**Comment by edsu** [comment]
Nice! Is it difficult to get twarc to talk through the proxy?

**Comment by justinlittman** [comment]
Setting HTTP_PROXY, HTTPS_PROXY, and REQUESTS_CA_BUNDLE env variables is all it should take.

**Comment by justinlittman** [comment]
In a test harvesting flickr (using http://stuvel.eu/flickrapi), it appears that warcprox records the gzipped response.  Interesting.

**Comment by edsu** [comment]
Very nice. I'll be interested in hearing if streaming works. I think I remember hearing @ikreymer say he has streamed youtube videos through warcprox using youtube-dl.

**Comment by justinlittman** [comment]
I suspect the correct way to deal with twitter streaming is warc continuation records.  More to research.

**Comment by ikreymer** [comment]
yes, warcprox can indeed be used in conjunction with youtube-dl, the specific use case was to get the video stream from youtube-dl, then load that url through warcprox. Note that warcprox, by design, downloads the full response and writes to the warc, even if client has disconnected.. Chunk encoded and gzipped responses should be recorded exactly as is, also.

I would advise against continuation records, as they are not widely supported for replay.. But then again, I don't know the exact use case here, especially in regards to "streaming" :)

**Comment by justinlittman** [comment]
@ikreymer - this is for harvesting the twitter streaming api (https://dev.twitter.com/streaming/overview).  The http response is intended to be long-lived (as in hours or days).

**Comment by justinlittman** [comment]
Working on a blog post describing findings.

**Comment by edsu** [comment]
If you don't mind, please update this ticket with the post URL when/if it gets written.

**Comment by justinlittman** [comment]
Will do.

**Comment by justinlittman** [comment]
@edsu, here it is:  http://bit.ly/1ipwd0B

**Comment by edsu** [comment]
Thanks @justinlittman!

**Comment by ikreymer** [comment]
Great write up! I am actually working on a "third technique" that does not rely on warcprox, but wraps the python requests library such that the raw request and response can be recorded, while the library handles the actual communication. This gives the full control of the first option, and avoids using a separate application for recording. I am testing this for use with pywb, but can be used separately as well. It's still a bit experimental, currently lives in: https://github.com/ikreymer/pywb-ipfs/tree/master/pywb_liverec 

The approach was partially inspired by the vcr library (which can't be used directly as it does not provide raw access to the stream) https://github.com/kevin1024/vcrpy

**Comment by ikreymer** [comment]
If there is interest, I could factor out the recording portion to make it more standalone... though still experimental and needs testing, but let me know

**Comment by edsu** [comment]
@ikreymer I would definitely be interested in seeing the requests modification to record warcs. It seems like a super useful option. I seem to remember you were looking at using another Python library that had warc support? Wasn't it a python implementation of wget?

**Comment by justinlittman** [comment]
It's https://github.com/chfoo/wpull.  (I've been doing some experimentation with it.)

@ikreymer:  Sorry for the delayed response, but I shared @edsu interest as well.

**Comment by edsu** [comment]
@justinlittman ahh yes, wpull -- thanks!
