### ISSUE TITLE
Clarify backup and restore (wrlc) of prod sfm-data

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#380]

**Comment by kerchner** [comment]
Ref. thread on WRLC help desk ticket #15266

**Comment by kerchner** [comment]
WRLC has set up the following for us (Ticket #15266):

There is now an /sfm-mirror volume (from /dev/sdc1) mounted on gwsfm-prod2.  There is a script in root's crontab that runs rsync every night at 1:10am to sync up /sfm-mirror with /sfm-data. It writes a nightly log to /tmp/sync-sfm.sh.log. It can be configured to also email the log, which I've done to email it to the SFM email address.

@lwrubel and @justinlittman , we should discuss whether to:
- Adjust the frequency
- Have it *not* sync deleted files.
- Turn off success notifications and only send notifications upon failure (I'd advocate for leaving this on)
and any other adjustments we'd like to make.

For now, though, it seems to be working.  The mirror volume has been set up as the same size as sfm-data, so if we increase sfm-data, we'll also need to increase sfm-mirror.

One downside of this approach is that it only helps in scenarios such as sfm-data failure.   Situations like we had where state files got zeroed out would not be helped by this approach, as the sync would have overwritten the "good" state files with the zeroed-out ones.  This provides us with a single backup image that's between 0-24 hours old; if sfm-data got corrupted and then synced, then the copy is likely to reflect the same corrupted data.

But, we can try this approach for now and see how it serves us.

**Comment by kerchner** [comment]
@kerchner to review other realistic WRLC options with @kilahimm before finalizing

**Comment by justinlittman** [comment]
Moved to trello ticket.
