### ISSUE TITLE
Add instructions for upgrading existing instance to new versions of docker containers

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#387]
This should be fairly simple (edit docker-compose, re-compose, etc.) but want to make sure we don't forget to add this before we release the first post-1.0 version.

**Comment by justinlittman** [comment]
See #302.  This will need some testing and probable enhancements of harvesters and exporters to make sure upgrade is graceful.

**Comment by kerchner** [comment]
👍
