### ISSUE TITLE
Fix footer on collection sets lists page

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#389]
Footer is bumping into Add Collection Set button at bottom of collection set list page, when there are a lot of collection sets. See sfm prod as an admin user as an example:

![screen shot 2016-07-27 at 9 53 06 am](https://cloud.githubusercontent.com/assets/1619369/17177558/f8f36998-53df-11e6-916c-ac8d2052ae8c.png)

**Comment by justinlittman** [comment]
Fixed.
