### ISSUE TITLE
Harvest fails if one seed is not available 

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#394]
Got harvest failure message and no tweets harvested with a twitter user timeline collection with two seeds:

- liblaura (an active public account)
- nytolympics (a private account)

The error visible on the harvest page is:

```401 Client Error: Authorization Required for url: https://api.twitter.com/1.1/statuses/user_timeline.json?count=200&user_id=74796152```

When the nytolympics handle was included in a collection on the production server, some tweets from other seeds were harvested before the failure occurred. (See the News Outlets > News outlets collection). 

Related to #346.

**Comment by justinlittman** [comment]
See https://github.com/gwu-libraries/sfm-twitter-harvester/pull/15

**Comment by kerchner** [comment]
Resolved by https://github.com/gwu-libraries/sfm-twitter-harvester/pull/15
