### ISSUE TITLE
plan for integrating configurable GW-based authn

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#4]

**Comment by dchud** [comment]
pushed to later date - need to determine appropriate configuration strategy.

**Comment by dchud** [comment]
Probably best option is to use https://github.com/KonstantinSchubert/django-shibboleth-adapter and use optional docker config to integrate with local config as needed. See #31 for work on next milestone.

Note that that repo appears to be a still-active fork of https://github.com/Brown-University-Library/django-shibboleth-remoteuser

Note that allauth does *not* appear to support shibboleth, hence the need for additional support deps. http://www.intenct.nl/projects/django-allauth/

It seems unlikely that we at GWU will have an oauth or other single-signon frontend that obviates the need to speak directly to our shib infrastructure anytime soon, so hopefully this can work for us an at least some other .edu orgs.

**Comment by rajatvij** [comment]
@dchud Although this might be unrelated, but we can check python-social-auth as it supports SAML backends. Please check [http://python-social-auth.readthedocs.org/en/latest/backends/saml.html?highlight=shibboleth] for reference. 
I am not sure if we can work it out and switching from allauth to python-social-auth would need some time again.

**Comment by dchud** [comment]
@rajatvij that's a good point, I'd missed that it supports SAML.  I share your concerns about using two separate libraries with similar goals, even though we'd use them to meet separate objectives.  Let's stick with the current plan; if the django support library does what we need, it seems like it might result in a lighter footprint.  If it doesn't, we can reevaluate.

**Comment by rajatvij** [comment]
@dchud Seems like a good approach to me.

**Comment by justinlittman** [comment]
https://5chub3r7.wordpress.com/2014/12/05/how-to-not-use-shibboleth-with-the-django-web-framework/ describes a promising approach, which is to rely on Apache.
