### ISSUE TITLE
Turn down pika logging on sfm-flickr-harvester

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#40]
Steps to reproduce:
1. Bring up an environment with an sfm-flickr-harvester.
2. Send it a harvest start message.
3. `docker logs docker_sfmdevflickrharvester_1`

Expected results:
Useful logging info.

Actual result:
Way too much noise.

**Comment by dchud** [comment]
Discussion led to #53 - thinking about handling logs across containers.

**Comment by justinlittman** [comment]
This will be superseded by #57, so closing.
