### ISSUE TITLE
in-app help for collection types

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#400]
Make more info easily available about what the different collection types are. Consider ? icon and popover.

**Comment by lwrubel** [comment]
Popover not a good approach for this particular information, since it is too long and floats over the button and its dropdown. May need a separate, minimal help section within the app, or link to a part of the documentation.

**Comment by kerchner** [comment]
As discussed:
- Link in the UI next to the Add Collection button, links to documentation on RTD.  Docs should include a warning re: samplestream size
- Warning in the UI by "collect web resources" checkbox (w/link to docs)
- Warning in the UI on the create samplestream collection page (w/link to docs)

**Comment by lwrubel** [comment]
@lwrubel to write docs page, likely to be assigned to someone else for implementation.

**Comment by kerchner** [comment]
Spun off #449 for documentation additions on rtd site.  Moving this ticket (for in-app help) out of 1.2

**Comment by lwrubel** [comment]
Done with 1.6
