### ISSUE TITLE
Check for write access first before deleting state store file

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#402]
The data volume became full and un-writeable.  In this scenario, any state store files that SFM (likely code in https://github.com/gwu-libraries/sfm-utils/blob/master/sfmutils/state_store.py) attempted to write to, ended up being overwritten as 0-length files, so state store information was lost for these user timeline collections (twitter and weibo).

Recommend updating the logic to ensure that the file is currently writeable before proceeding and attempting to overwrite its contents.

And/or better handle where the state store file is present but empty.

**Comment by Tanych** [comment]
I think a possible or stable way is moving the state info to the database since this kind of info is very important, especially  doing the long period harvest, for example, one year or two years. Saving file can't guarantee other system issues. However, it might be more complicated when the harvesters request database info.

**Comment by kerchner** [comment]
@Tanych Thanks for adding your thoughts, this is definitely important and something we should discuss soon.  You may have noticed that, unfortunately, we lost the state on the weibo harvest this week.  We learned some things from what it took to recover from running out of space on /sfm-data and get the harvests going again.

**Comment by justinlittman** [comment]
@Tanych #52 is for improving the state store, possibly moving to a db.

**Comment by justinlittman** [comment]
@kerchner See https://github.com/gwu-libraries/sfm-utils/pull/16

**Comment by kerchner** [comment]
Closed by https://github.com/gwu-libraries/sfm-utils/pull/16
