### ISSUE TITLE
Additional harvest notifications

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#409]
With harvests messages working correctly (#346, #394), it is clear that the results of harvests need to be brought to attention of users, especially when there are messages.

For this ticket, 2 notifications will be added:
1.  For a collection, if the last harvest failed or has messages, those will be provided as alerts on the collection detail page.
2.  If a harvest fails or has messages, send an email to the members of the collection's group.

**Comment by justinlittman** [comment]
For testing, the easiest way to create error messages is to perform a twitter user timeline harvest with invalid screen names.

The easiest way to create a failed harvest is to perform a harvest using invalid credentials.

**Comment by lwrubel** [comment]
Closed with #410.
