### ISSUE TITLE
release notes for 0.2

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#42]
Release notes suitable for readthedocs, i.e. in the docs/ directory.  This is our first time following a release process, the first version of which @justinlittman is documenting separately in our wiki for this project.

**Comment by justinlittman** [comment]
Release notes completed:  https://github.com/gwu-libraries/sfm-docker/releases/tag/0.2.0
Release process documented:  https://github.com/gwu-libraries/sfm-ui/wiki/Release-process
