### ISSUE TITLE
Monitor free space

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#428]
Well, we got bitten again running out of free space on /sfm-data (this time on sfm-test).  This has been the single largest cause of our failures.  While in theory monitoring disk space should be part of the infrastructure, as a practical matter SFM should monitor and provide warnings.

SFM will check disk space on /sfm-data and /sfm-processing at configurable intervals. When disk space falls below a configurable level, it will send an email to the configured admin. It will not send another email until disk space goes above the threshold.

It is recommended to implement this as a scheduled job in SFM UI.  See the user harvest emails code for an example of performing tasks on a schedule.

**Comment by justinlittman** [comment]
Also worth considering is displaying free space on the home page of admins.

**Comment by justinlittman** [comment]
Before working on this, let's finalize the requirements.

**Comment by justinlittman** [comment]
If you logged in as an admin, then on the home page the amount of free space on /sfm-data and /sfm-processing will be displayed.  Also, the amount of free space will be included in the harvest status email message for admins.

**Comment by Tanych** [comment]
It might be something like the [cAdvisor](https://github.com/google/cadvisor), which give the usage of the containers. It got more advanced, for this issue, we need a simple one to monitor the space of /sfm-data and /sfm-processing and then sending email notifications. However, the sfm-data  and sfm-processing get exit when setup, the cAdivosr has no information about the exit containers.  We can talk a little more about the issue.

I tried some pieces for the CAvisor, it gives me some graph of the usages, the following graph is the **twitter-harvester container**:
![cup_mem](https://cloud.githubusercontent.com/assets/3956411/19127560/79612066-8b0d-11e6-8110-c6851b4fd025.png)

**Comment by justinlittman** [comment]
@Tanych cAdvisor is overkill for this ticket, but it looks real interesting.  Can you move the work on cAdvisor to #470?

For this ticket, we're looking for something much simpler -- the python equivalent of `df -h`.

**Comment by Tanych** [comment]
@justinlittman Yeap, for this ticket, we only need to get a very simpler solution to do that. Just check the space. I just did some researches for the possible use in the future.  I will focus on solving this tickets first. The cAdvisor would take consideration later.

**Comment by Tanych** [comment]
Some preview works for the emails and admin index:
* Emails Notification

![emails_notifaction](https://cloud.githubusercontent.com/assets/3956411/19444155/4b9899a8-945d-11e6-8b08-be0e15ca7846.png)

* Admin home
![amdin_index](https://cloud.githubusercontent.com/assets/3956411/19444173/5faed934-945d-11e6-8d59-604bafb6fc67.png)

**Comment by justinlittman** [comment]
@Tanych I like it!

**Comment by justinlittman** [comment]
I've reviewed and tested this feature.  Two requests:
1.  Add the same functionality for monitoring /sfm-processing.  It can use the same schedule and be sent in the same email, but should have a separately configurable threshold.
2.  Most of the space-related environment variables will only be used for testing.  Thus, for simplicity I would like to omit them from the example docker-compose and .env files.  The only variable that should be included in those files are for the threshold variable, which an admin will probably want to change.  In the .env file it should be under the VOLUME CONFIGURATION section.

**Comment by justinlittman** [comment]
Fixed by:
* https://github.com/gwu-libraries/sfm-ui/pull/487
* https://github.com/gwu-libraries/sfm-docker/pull/7
