### ISSUE TITLE
Consider guidance on understanding harvest status

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#430]
As reported by Maria @ IA, it is unclear how to interpret harvest status.  In particular, what does multiple harvests in the "requested" status mean.

Consider whether to add to documentation and/or UI changes.

**Comment by lwrubel** [comment]
@lwrubel to detail suggested possible UI change, to be implemented by @adityadharne

**Comment by kerchner** [comment]
Reconsider after #444 is merged.

**Comment by lwrubel** [comment]
Closing, handling more specific cases.
