### ISSUE TITLE
Consider including URLs in user profile (images/links) in web resources harvest

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#433]
Maybe just for Twitter user timeline collection?  This would be extremely valuable to the Program on Extremism use case, or any other researchers studying user profiles.  Probably would be easy to implement; just expand the scope of URLs that are harvested to include URLs within the user block of the tweet JSON.

**Comment by kerchner** [comment]
As per discussion:  Collecting user profile web resources would be a separate checkbox.  It will be important to be able to deduplicate web resources via hash (configuration in Heritrix - ref #438)

**Comment by kerchner** [comment]
Let's call the checkbox "User profile images".  The help text should be "Perform web harvests of user profile images and user banner images"

**Comment by adityadharne** [comment]
PR 1: https://github.com/gwu-libraries/sfm-ui/pull/515
PR 2: https://github.com/gwu-libraries/sfm-twitter-harvester/pull/22
