### ISSUE TITLE
Don't receive emails sent to EMAIL_HOST_USER

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#436]
If you are the EMAIL_HOST_USER and SFM send you an email, it will appear in your sent folder, not your Inbox.  (Thanks GW Gmail configuration!)

Emails should be sent from a separately configurable email (noreply@???.edu?) so that EMAIL_HOST_USER can receive them.

**Comment by kerchner** [comment]
We want to configure two separate values:  One for for the EMAIL_HOST_USER and a separate one to populate the "send-from" value in the email header - e.g. EMAIL_SEND_FROM_USER or similar. (Currently this is being populated from EMAIL_HOST_USER.)

**Comment by Tanych** [comment]
I have tried lots of situations for the django `sending email`
### Auth email and from_email is different with same STMP server
```python
 send_mail(mail_subject, mail_message, from_email='Fred <tanych5233@gmail.com>',
                                      recipient_list=[receiver_email], fail_silently=False, auth_user='sfmnoreply1989@gmail.com',
                                      auth_password='******')
```
What I receive is:
```bash
Fred <sfmnoreply1989@gmail.com> 11:17 AM (17 minutes ago)
to me 
```
The custom `from_email` is replaced by the `auth_email` for SMTP server.

### Auth email and from_email is different with **different** STMP server
```python
 send_mail(mail_subject, mail_message, from_email='Fred <tanych5233@hotmail.com>',
                                      recipient_list=[receiver_email], fail_silently=False, auth_user='sfmnoreply1989@gmail.com',
                                      auth_password='******')
```
What I receive is the same result as above.

I also try to look at the source code to figure out what's going on here, but it all seems to in the right way.
https://github.com/django/django/blob/1.8.10/django/core/mail/message.py#L269

**Comment by Tanych** [comment]
@justinlittman I also tried setting EMAIL_HOST_USER and SFM user as the same GWU email, the user can receive the notification email.

**Comment by justinlittman** [comment]
I suspect that the gmail smtp server is changing the from_email.  I'd hold on this ticket until #452 is done.

**Comment by justinlittman** [comment]
Since we don't really have control over the from_email and given the new sfm_no_reply account, declaring this ticket wontfix.
