### ISSUE TITLE
Create Twitter Filter UI page results in back-end error

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#437]
Refs #370 
While `Incremental` and schedule fields have been removed from the UI for Twitter Filter collections, clicking on create new twitter filter results in:

```
WARNING:root:Could not resolve form field 'incremental'.
Traceback (most recent call last):
   File "/usr/local/lib/python2.7/site-packages/crispy_forms/utils.py", line 91, in render_field
     field_instance = form.fields[field]
 KeyError: u'incremental'
 WARNING:root:Could not resolve form field 'schedule_minutes'.
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/site-packages/crispy_forms/utils.py", line 91, in render_field
     field_instance = form.fields[field]
 KeyError: u'schedule_minutes'
```

**Comment by lwrubel** [comment]
@Tanych can you try to replicate this? We don't think it's a problem anymore, but want to be sure before closing it.

**Comment by Tanych** [comment]
@lwrubel  It still get the warning on sfm-ui logs!

**Comment by Tanych** [comment]
For the warning of `u'schedule_minutes` key error, the inherited form has excluded the field in base form. However, the `crispy_forms` will still check the filed, It raises this warning. It won't influence the work. 

https://docs.djangoproject.com/en/1.8/topics/forms/modelforms/#modelforms-selecting-fields
