### ISSUE TITLE
Web harvester deduping

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#438]
Heritrix is not currently configured to dedupe.  Support for deduping at the collection level is required.

**Comment by lwrubel** [comment]
This is a dependency of the work to add user profile URLs to web harvesting (#433) so that we avoid collecting user profile URLs repeatedly in user timeline collection types.

**Comment by justinlittman** [comment]
Here are the relevant branches:
* https://github.com/gwu-libraries/sfm-ui/tree/sfm_438-dedupe
* https://github.com/gwu-libraries/sfm-utils/tree/sfm_438-dedupe
* https://github.com/gwu-libraries/sfm-web-harvester/tree/sfm_438-dedupe

Will want to wait until release of 1.2 and then rebase these before creating PRs.

**Comment by justinlittman** [comment]
Steps for testing:
1.  Bring up an instance of SFM, where each of these branches is being used.  The harvesters should use the branch in sfm-utils.
2.  Create a collection that involves harvesting some sort of media or web resources and is not incremental and let it harvest.  Flickr works particularly well for this.
3.  Stop and start it so that it harvests again.  This should cause web resources to be harvested again.
4.  Look on the collection details page look at the harvest list.  The number of web resources collected should be less for the subsequent web harvest.  (If deduping wasn't occurring, you would expect them to be the same.)

**Comment by justinlittman** [comment]
@adityadharne Can you please test this ticket?  Let me know if you have any questions.

**Comment by justinlittman** [comment]
@adityadharne tested and approved.
