### ISSUE TITLE
Apply scheduling to message tracer bullet

### ISSUE THREAD

**Issue by rajatvij** [gwu-libraries/sfm-ui#44]
* Schedule harvest jobs according to the schedule defined in seed sets.
* According to schedule, submit the appropriate harvest_start message.
* It will need to consider the harvest_start and harvest_end_date defined for the seed set.

**Comment by dchud** [comment]
@rajatvij and @justinlittman - please discuss and fill in description so we are clear what the work to be done for this milestone will be.

**Comment by dchud** [comment]
Key questions for evaluating [apscheduler](apscheduler.readthedocs.org):
 * how is the process invoked, and how does it recover from system restart? do we need to supervise that process ourselves?
 * what is its persistence layer?
 * if it persists to db, how do we handle that connection viz. django connection?
 * what do it require of our models that might be different?

**Comment by kerchner** [comment]
Here's a working model that I think we can build our use of apscheduler on:   https://gist.github.com/kerchner/3eb79879d745dac71b8c   .  It should solve some of the issues of, for instance, how to get a handle to the BackgroundScheduler from elsewhere in the application.

**Comment by kerchner** [comment]
However, we also need to engage apscheduler's ability to persist a scheduler (e.g. if the app is stopped and restarted later).

**Comment by kerchner** [comment]
Rename sfm_exchange queue to sfm_ui_queue
