### ISSUE TITLE
Remove "Bad response in record" warning in WARC iterator

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#441]
This isn't useful to us, as we wouldn't want to export anything but actual posts anyway, and it vastly clutters up the logs.

**Comment by justinlittman** [comment]
PRs for this ticket:
* https://github.com/gwu-libraries/sfm-utils/pull/18
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/17

**Comment by justinlittman** [comment]
@kerchner This is ready to go.

**Comment by kerchner** [comment]
Resolved by https://github.com/gwu-libraries/sfm-twitter-harvester/pull/17 and https://github.com/gwu-libraries/sfm-utils/pull/18
