### ISSUE TITLE
Update elk to use "collection set" rather than "collection"

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#442]
- Update comment/example in `example.docker-compose.yml`
- Consider changing `--collection` command option (and/or allow for `--collection` as well as `--collection-set` ?)

**Comment by justinlittman** [comment]
#463 is for supporting limiting by collection.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-docker/commit/81932a5835f53c88bef653a154410fce55108b74
