### ISSUE TITLE
Adding an invalid Twitter uid or screenname as a seed results in creation of a WARC w/credential owner's tweets

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#448]
CASE 1:  INVALID UID
Steps:
- Create a twitter user timeline harvest with Uid=99999999999999999999999 which should be an invalid UID
- Turn on harvesting
- run an export

Result:
- The harvest comes back with a status of Success, and a warc was created.  No warnings.
- The export seems to be contain all tweets originating from the account whose credentials were used (e.g. @DanKerchner)

Expected Result:
- Non-Success status for the Harvest, or some more visible indication in the Harvest list (on Collection view) that there were warnings
- No WARC created, or an empty WARC

CASE 2:  INVALID SCREENNAME
Steps:
- Create a twitter user timeline harvest with token=jkhasasdlhlhkasdfhjkasdlhasdfhjlajhlhjkadsfasdf which should be an invalid screen name
- Turn on harvesting
- run an export

Result:
- The harvest comes back with a status of Success, and a warc was created.  A warning is presented "Warnings messages reported by last harvest: User id not found for user jkhasasdlhlhkasdfhjkasdlhasdfhjlajhlhjkadsfasdf
- The export seems to be contain all tweets originating from the account whose credentials were used (e.g. @DanKerchner)

Expected Result:
- Non-Success status for the Harvest, or some more visible indication in the Harvest list (on Collection view) that there were warnings
- No WARC created, or an empty WARC

**Comment by Tanych** [comment]
@kerchner  For the UID test case, the twitter `user_timeline` will return the credential owner's default timeline if the UID is valid. 
For the screen_name test case, I think it exports the result based on the previous test case.

I can add some regex rules for adding screen_name or UID when adding bulk seeds, but for the front-end UI, it's a little tricky to validate the screen_name or uid . We'd better think though how to make all the validation works.

**Comment by Tanych** [comment]
@kerchner 
for case 1 invalid UID, I can add some warning message similar as the invalid screen name. It could be like this:
```
Warning messages reported by last harvest:
Screen name not found for user 99999999999999999999999
```
 However, for the warc files, it needs to change based on discussion. I think it's not a simple work. The warc file records the API request for the user lookup. 
```
WARC/1.0
WARC-Type: response
WARC-Record-ID: <urn:uuid:cef657c4-f7ef-4dfa-90fc-b7f7ce0cca7f>
WARC-Date: 2016-12-28T15:49:20Z
WARC-Target-URI: https://api.twitter.com/1.1/users/lookup.json?user_id=99999999999999999999999
WARC-IP-Address: 104.244.42.66
Content-Type: application/http;msgtype=response
Content-Length: 1067
WARC-Block-Digest: sha1:ad20ace8416715db948f5580d20180954b4420a8
WARC-Payload-Digest: sha1:c3259eff9700c4c7f239554407c01c1b5ff1b84b

HTTP/1.1 404 Not Found
cache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0
content-disposition: attachment; filename=json.json
content-encoding: gzip
content-length: 98
content-type: application/json;charset=utf-8
date: Wed, 28 Dec 2016 15:49:21 GMT
expires: Tue, 31 Mar 1981 05:00:00 GMT
last-modified: Wed, 28 Dec 2016 15:49:21 GMT
pragma: no-cache
server: tsa_b
set-cookie: lang=en; Path=/
set-cookie: guest_id=v1%3A148294016164288579; Domain=.twitter.com; Path=/; Expires=Fri, 28-Dec-2018 15:49:21 UTC                                                          
status: 404 Not Found                                                                                                                                                     
strict-transport-security: max-age=631138519                                                                                                                              
x-access-level: read                                                                                                                                                      
x-connection-hash: 9bf7957065fafd994791b1b7a60bb1b4                                                                                                                       
x-content-type-options: nosniff                                                                                                                                           
x-frame-options: SAMEORIGIN                                                                                                                                               
x-rate-limit-limit: 900                                                                                                                                                   
x-rate-limit-remaining: 898                                                                                                                                               
x-rate-limit-reset: 1482940824                                                                                                                                            
x-response-time: 16                                                                                                                                                       
x-transaction: 00d187040089a35b                                                                                                                                           
x-twitter-response-tags: BouncerCompliant          
```
If we should totally ignore the invalid uid or screen name harvester, what we need to do is sending a failure message without any request record instead of the warning message. It can be done at UI with some javascript, but it might involve additonal work. Also, we can apply changes  to `twitter_harvester` and `warc_proxy`.

**Comment by lwrubel** [comment]
@justinlittman take a look.
