### ISSUE TITLE
export tracer bullet

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#45]
Key goals:

 * enable user export requests
 * enable warc export
 * notify sfm-ui of completion/station with messaging

Please create additional tickets as warranted for work to be done in sequence, rather than making this one big mega-pull request.

**Comment by dchud** [comment]
Relation to #47: for #45, focus on kicking of and performing the export.

**Comment by justinlittman** [comment]
Assuming these basic requirements:
* Export is for a seed set or a subset of seeds in a seed set.
* Export can be limited by harvest date or content date.
* Export is to CSV/Excel.

The approach will be for a user to make a request via SFM-UI.  SFM-UI will record the export request and send an export request message that will be claimed by the appropriate exporter.  The export request message will contain the appropriate details, including the location for the export.  Exporter will determine which WARCs to use by querying the SFM-UI's REST API and then prepare the export.  When completed, it will send an export response message.  SFM-UI will receive the message, update the export request record, and notify the user.

**Comment by justinlittman** [comment]
Here are the pull requests for this ticket:
* https://github.com/gwu-libraries/sfm-ui/pull/154
* https://github.com/gwu-libraries/sfm-utils/pull/8
* https://github.com/gwu-libraries/sfm-flickr-harvester/pull/5

**Comment by kerchner** [comment]
The pull requests above have all been merged, so the work for this ticket is complete.
