### ISSUE TITLE
Add seed (non-bulk) for Twitter should validate for type

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#453]
Add Seed should validate (for Twitter) that:
- screen name is non-numeric
- UID is numeric
- only allow entry of one field or the other, but not both (this is one of several ways to handle this, not the only one).  Perhaps use a radio button like the bulk add page (again, there are other ways to implement this).

Also consider validations for other platforms where appropriate.

Also ref #158

**Comment by lwrubel** [comment]
@Tanych We think this was fixed in 1.6 but would you verify?

**Comment by Tanych** [comment]
it fixed in 1.6!

**Comment by Tanych** [comment]
fixed in https://github.com/gwu-libraries/sfm-ui/issues/714, closed!
