### ISSUE TITLE
Export segmentation

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#454]
Exporters should segment large datasets into multiple files. This is particularly relevant for exporting from twitter filter collections in the election dataset and other filter collections (e.g. several SMPA faculty collecting from filter stream), but also applies to user timeline exports that have a lot of accounts and/or prolific tweeters.

**Comment by lwrubel** [comment]
This issue will arise with exports from the elections collection.

**Comment by Tanych** [comment]
### Performance 
Using `xlsxwriter` and `openpyxl` tests some basic benchmarks when exporting large numbers of rows.

#### Versions
* python      : 2.7.6
* openpyxl    : 2.3.3
* xlsxwriter  : 0.9.3

The following test cases are exporting rows to `xlsx` files, we can use the performance  to decide how to make the large datasets into segments files. The row data is like `Row: 1 Col: 0` which wrote to the file.

#### Case 1
Dimensions: Rows = 10,000    Cols = 15

|            | Time cost (s) | File Size | Readable in Excel |
|------------|---------------|-----------|-------------------|
| xlsxwriter | 1.34          | 580.0 KB  | Yes               |
| openpyxl   | 2.26          | 728.3 KB  | Yes               |

#### Case 2
Dimensions: Rows = 100,000    Cols = 15

|            | Time cost (s) | File Size | Readable in Excel |
|------------|---------------|-----------|-------------------|
| xlsxwriter | 13.24          | 5.8 MB  | Yes               |
| openpyxl   | 16.48       | 7.0 MB  | Yes               |

#### Case 3
Dimensions: Rows = 500,000    Cols = 15

|            | Time cost (s) | File Size | Readable in Excel |
|------------|---------------|-----------|-------------------|
| xlsxwriter | 66.92        | 28.96 MB  | loading slow but can view             |
| openpyxl   | 83.22       | 34.87 MB  | loading slow but can view               |

#### Case 4
Dimensions: Rows = 1,000,000    Cols = 15

|            | Time cost (s) | File Size | Readable in Excel |
|------------|---------------|-----------|-------------------|
| xlsxwriter | 133.67     | 57.99 MB  | hard to read             |
| openpyxl   | 166.25       | 69.63 MB  | hard to read             |


#### Case 5
Dimensions: Rows = 2,000,000    Cols = 15

|            | Time cost (s) | File Size | Readable in Excel |
|------------|---------------|-----------|-------------------|
| xlsxwriter | **166.00**     | **60.90 MB**  | hard to read             |
| openpyxl   | 336.52       | 140.05 MB  | hard to read             |

> xlsxwriter reaches its max rows **1024*1024=1048576** in a single xlsx file.

**Comment by lwrubel** [comment]
Present option of downloading as one file or segmented (default) with several options and default of 250,000. Values: 100K, 250K, 500K, 1 million.

**Comment by justinlittman** [comment]
Finished testing.  I've added individual line comments.

Other comments:
* I'd like to see None/null be used instead of -1 for all.  -1 is the sort of thing that will confuse future developers.
* segment_size needs to be added to the messaging spec.

**Comment by justinlittman** [comment]
As a bonus I threw in a testing option for a 100 item segment.
