### ISSUE TITLE
Harvest warning message should include Twitter UID, not (just) screen name

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#455]
Harvest warning message when user is suspended/private can come back referencing user screen name as "None":

```
    "message": "Unauthorized for user None because account is suspended or private", 
    "code": "token_unauthorized"
```

making it difficult to know which token was the problem.   Including the UID as well would resolve the issue.

See Harvest id=3dbc0acaf5b04d1387de0f07f2e82397 in production.

**Comment by adityadharne** [comment]
PR: https://github.com/gwu-libraries/sfm-twitter-harvester/pull/23
