### ISSUE TITLE
Include timezones on Harvest detail

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#456]
Currently in production, harvest details look like this:

Requested: Sept. 22, 2016, 11:09 a.m.
Started: Sept. 22, 2016, 7:09 a.m.
Ended: Sept. 22, 2016, 7:09 a.m.
Updated: Sept. 22, 2016, 11:09 a.m.

Possible solutions:
- Is this just something that is not but needs to be configured correctly on production?  (for example, harvesters' containers' timezones are not set the same as ui container timezone?)
- And/or consider displaying timezone with harvest detail date/times.

**Comment by dchud** [comment]
I'm seeing the same thing at the database row level for harvests.  Confirms that they're being recorded incorrectly, not strictly a UI issue, though I like @kerchner's idea of showing timezones too.

![20161026003402-screenshot1](https://cloud.githubusercontent.com/assets/62130/19713441/29358b24-9b14-11e6-967e-ecc2cf8efeef.png)

**Comment by justinlittman** [comment]
Moved towards the top of backlog.  This should be slotted for 1.4.

**Comment by Tanych** [comment]
It's actually not the database or timezone setting problem. Django  stores `datetime` information in `UTC` in the database. We can display the time in different setting timezone if set `USE_TZ=True` .

Date can be display as:
`Tue, 8 Nov 2016 11:14:35 -0500` or `2016-11-08T11:13:32.460002-05:00	`

The Django timezone describes as follow:
https://docs.djangoproject.com/en/1.10/topics/i18n/timezones/

**Comment by justinlittman** [comment]
I've reviewed this and it is ready to be merged once 1.3.1 is tagged.
