### ISSUE TITLE
ELK exiting with "Problem with application dependencies"

### ISSUE THREAD

**Issue by peterk** [gwu-libraries/sfm-ui#458]
After editing docker-config to include the experimental ELK support the machine starts but stops after a while. The log contains an error that indicates a permissions problem in the setup script. I am using the standard configuration options.

```
Problem with application dependencies.
/usr/local/bin/sfm_elk_start.sh: line 3: /opt/sfm-setup/setup_reqs.sh: Permission denied
Waiting for elk
 * Starting periodic command scheduler cron
   ...done.
 * Starting Elasticsearch Server
sysctl: setting key "vm.max_map_count": Read-only file system
   ...fail!
waiting for Elasticsearch to be up (1/30)
```

**Comment by justinlittman** [comment]
@peterk Thanks Peter!  Which version are you running?

**Comment by peterk** [comment]
Latest. Did a fresh install. Host OS is Mac OSX 10.11.6 if that is of importance.

**Comment by peterk** [comment]
Did I just report this in the wrong repo? So sorry.

**Comment by justinlittman** [comment]
@peterk We put all of our SFM tickets in the sfm-ui repo, so you got it correct.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-elk/commit/bf715f0e46ebbb05535743fc519700ee27bf2f34

**Comment by justinlittman** [comment]
@peterk If you change your docker-compose.yml file to use the gwul/sfm-elk:master image for ELK, you should get the fix.

(Well, you need to wait about 10 minutes from now for the new image to build on Docker Hub.)
