### ISSUE TITLE
Harvest list crashes

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#467]
This commit https://github.com/gwu-libraries/sfm-ui/commit/909c63054535271b9f9bc96636ecc01d95f7a745#diff-e060b863b48be5d5d439598397ab008f may be causing harvest_list.html to return a stack trace with `Invalid filter: 'naturaltime'`

This is occurring on sfm-test; I haven't tested elsewhere to confirm but can do so and update the issue.

**Comment by justinlittman** [comment]
sfm-test wasn't running the latest code. I've updated it and it now works.

Thanks to @lwrubel for catching this bug during testing.

**Comment by kerchner** [comment]
Thanks @justinlittman
