### ISSUE TITLE
plan delivery flow for exported materials

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#47]
Think through strategies for movement of files, user notification, expiry of moved files for delivery, and UX implications, and propose work to be done in future milestones.  Probably should result in a narrative proposal, not code for this cycle.

**Comment by kerchner** [comment]
@dchud I think Justin may have pre-empted this ticket with:  https://drive.google.com/open?id=1Oyso5o0Sun0g0F-3XVPifelahhWGSI9ARyPHfUgEAzs   - or is that not what you had in mind?

**Comment by justinlittman** [comment]
I think these are (mostly) non-overlapping.  @kerchner and I will discuss.

**Comment by kerchner** [comment]
Note possible need for filtering before delivery of export to check for and remove deleted etc. posts.

**Comment by dchud** [comment]
w/r/t #45: #47 should focus on delivery, notification, and management/deletion after expiry.

**Comment by kerchner** [comment]
Draft document is coming together [here in Google Drive](https://docs.google.com/document/d/1coiJp3J2_j1cABdI6pq6rva_83AW9zZkg7AB6qZAX_8/edit)

**Comment by dchud** [comment]
Discussed 11/30 and will follow up with more tickets.
