### ISSUE TITLE
Consider providing ability for user to disable harvest notifications

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#471]
This is driven by user feedback from the Program on Extremism.   This collection harvests frequently (@30min) and harvests almost always have warnings.   The user requested to be removed from the collection set's group due to the overabundance of emails.   Granted, email filters can mitigate this issue, but the user in this case would have preferred a way to disable the harvest notifications.

**Comment by adityadharne** [comment]
The harvest notifications are not dependent on the user profile settings. The current frequency affects the summary emails. We can add a check-box in the create collection view. This way the user can decide about the harvest notifications while creating a collection itself.

**Comment by kerchner** [comment]
@adityadharne Interesting, so we could either configure harvest notifications on/off at
- the collection level, or
- the user level (across all of the user's collections)
- or both? (with a logical "and" ?)
I would advocate for the user level, but interested to hear thoughts from @justinlittman @lwrubel @Tanych

**Comment by justinlittman** [comment]
Concur with user level.

**Comment by lwrubel** [comment]
Closed by #492.
