### ISSUE TITLE
Determine whether retweeted Weibos need to be handled differently

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#473]
Retweeted Weibos are rendering as just "转发微博" in Excel export.   A few questions:
- Is there a way to also provide the original Weibo's text in the export?
- Are we harvesting the images and web resources from the original Weibo?  (Or are we only seeing "转发微博" and not recognizing that there were links in the origina Weibo

**Comment by Tanych** [comment]
As discussed before,  I have done the retrieve of the original weibos and links in retweeted status. However, the export part, I just get the text in weibos but not in the retweeted part. If need to add,it's simple to do that.

**Comment by Tanych** [comment]
After adding the retweets fields, it would like this:
![retweets](https://cloud.githubusercontent.com/assets/3956411/19241390/7557aa80-8edc-11e6-9a16-3c831b0b85c7.png)
