### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#479]
For various reasons, I find myself needing to delete (primarily in testing/dev environments).  It would be helpful if SFM UI supported the following forms of delete:
- Delete collection set and all data on disk.
- Delete collection and all data on disk.
- Delete all harvests for a collection and all data on disk.

**Comment by justinlittman** [comment]
Depends on #532

**Comment by kerchner** [comment]
Fixed in #589
