### ISSUE TITLE
review / start iterating over UX for collection building

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#48]
Starting from our existing wireframes and UI, iterate over design and flow for end-user collection creation.  May result in new/updated wireframes, and tickets for focused improvements to UI code in this milestone and future milestones.

**Comment by lwrubel** [comment]
Preliminary list of functionality for each page at: https://docs.google.com/document/d/19IpXkOavCU6vZVkD2gYHfWCjMtRUYw3eOVIgwr7JPTs/edit

Next step is creating an updated set of wireframes.

**Comment by lwrubel** [comment]
Questions for further discussion being logged at:
https://docs.google.com/a/email.gwu.edu/document/d/1-NmYuzl_p2Wc83uhrvLfacnA8s0kR7zBif0KuFdLqU8/edit?usp=sharing
