### ISSUE TITLE
Enhance stats

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#481]
It would be helpful if we could provide additional statistics on data being collected to help guide users on building a collection.  While we don't want to duplicate what DocNow is doing, a simple approach like the following would be beneficial:  Each harvester has the opportunity to return additional statistics in the harvest status message.  Those statistics would be only for data since the last status message (which means in the last WARC file), not for the entire harvest.  (This eliminates memory issues or needing to persist large sets of statistics.)  The statistics would be limited to say the top 25 items.  The statistics would be displayed on the collection detail page.  Only the most recent set of statistics would be stored on the harvest model.

For example, for Twitter, it might return the top hashtags and top user mentions.  Other harvest types may not return additional statistics.

**Comment by lwrubel** [comment]
Proceed as an experiment and consider which harvest types it best suits. Check in with users about the usefulness of stats.
