### ISSUE TITLE
Add back "mentions" column in Twitter Excel, CSV exports

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#482]
This is a very useful column for conducting network analysis on a set of tweets.  Not sure why it wasn't carried forward from the original SFM.

**Comment by lwrubel** [comment]
Also supports identifying additional users to track, as in the case of building up a set of official GW accounts.

**Comment by kerchner** [comment]
PR is https://github.com/gwu-libraries/sfm-twitter-harvester/pull/19

**Comment by adityadharne** [comment]
New PR is https://github.com/gwu-libraries/sfm-twitter-harvester/pull/21
