### ISSUE TITLE
Consider adding back is_retweet column in Twitter Excel, CSV exports

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#483]
May be useful for analysis; not sure why this was removed.  We could survey users, but it would be less effort to just add it back.

**Comment by lwrubel** [comment]
Look at twitter-provided JSON retweet field, rather than trying to infer from that and tweet text itself, as was done in old SFM.

**Comment by justinlittman** [comment]
Also added is_quote column.  Closed by https://github.com/gwu-libraries/sfm-twitter-harvester/pull/20
