### ISSUE TITLE
Twitter harvest options UI usability issues

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#484]
1. The Incremental/Media/Web Resources checkboxes do not, but should have a section heading (at the same level as "Description" , "Credential" etc.).  We can discuss what the heading might be called.
2.  The order of these three options is different when in edit vs. view (detail) mode.  This has certainly confused me a few times and likely would confuse others:

Order on Collection edit page:
- Incremental
- Media
- Web resources

Order on Collection detail page (non-edit mode):
- Media
- Incremental
- Web resources

The other plaforms' harvest options should be reviewed for similar issues of consistency.

**Comment by justinlittman** [comment]
I've reviewed this and it is ready to be merged once 1.3.1 is tagged.
