### ISSUE TITLE
Make accept-heading configurable in Twarc

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#485]
As suggested by @jeffersonbailey at IA, gzip encoding the http response payloads is redundant and can make extracting the social media data more complicated.

**Comment by lwrubel** [comment]
This also helps future users of WARCs collected by SFM who may want to use something other than warc_iter.

**Comment by justinlittman** [comment]
I created some sample WARC files and sent to Jefferson @ IA. Waiting to hear back.

**Comment by justinlittman** [comment]
Closing, since no word from IA on this feature request.
