### ISSUE TITLE
Adding/removing seeds from a Collection should be reflected in collection's change log

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#488]
Adding or removing "child" seeds from a Collection is not reflected in the collection's change log.  All that is recorded is that the collection was turned off, then on.  This is important for collections such as Program on Extremism which will frequently be adding seeds to a twitter user timeline collection, and may even have different users modifying the seed list.

**Comment by justinlittman** [comment]
Duplicate of #377.
