### ISSUE TITLE
Consider checking for duplication when adding seeds

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#489]
Currently (1.1) SFM allows the user to add a seed where a seed already exists with this screen name.

**Comment by lwrubel** [comment]
This comes up in PoE collection management and other collections with large seed lists.

**Comment by lwrubel** [comment]
@kerchner to work out the logic and possibly reassign to @adityadharne for implementation.

**Comment by kerchner** [comment]
This requires further investigation, but currently Bulk Add does seem to ignore duplicates, but only if they're the same case.  Duplication logic should be case-insensitive (for Twitter screen names, at least)
