### ISSUE TITLE
handle harvest completed return message

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#49]
Decide how to handle return messages: what to store, what actions to possibly kick off, and what to show in UI.  For this milestone, should probably at minimum:

 * record harvest in Harvest model, along with some form of stats
 * show basic summary in UI, e.g. a timeline view
 * plan work for future releases: notifications, troubleshooting, etc.

**Comment by kerchner** [comment]
For 0.3.0, receive message and update Harvest objects.  UI will be in a subsequent milestone.
