### ISSUE TITLE
Check user timeline seed lists

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#496]
Based on our experience with large twitter seed lists in the End of Term project, it would be useful to have a utility to check Twitter user timeline seed lists for being not found or suspended/private before adding to a collection.  

Possibly this could be a twarc utility. Its lookup_screen_names option does part of this, returning a user object when the account is active or private (has a "private" Boolean value). Not found accounts are not returned in the response from Twitter.

**Comment by kerchner** [comment]
Ref #158 - @lwrubel I don't think this is entirely a duplicate, but it's related.

What's the down side of always checking seeds before adding to a collection (within the SFM UI)?

**Comment by justinlittman** [comment]
@kerchner The challenge would be to find a non-hacky way to do it in the UI, since the UI doesn't have credentials and existing social media clients.

**Comment by lwrubel** [comment]
Writing a twarc utility would satisfy this use case.

**Comment by justinlittman** [comment]
Current approach has proven adequate.
