### ISSUE TITLE
Document storage

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#501]
As recommended by @dchud:
- Explain linked vs. Docker storage
- Storage directory structure
- How to copy out of Docker storage
- How to migrate between Docker storage and linked storage.

**Comment by lwrubel** [comment]
This is a documentation ticket.

**Comment by justinlittman** [comment]
Discussion with @ianmilligan1 about experiences setting up SFM illustrated that these docs would be helpful.  Make sure to reference the docs in example.env.

**Comment by justinlittman** [comment]
@chrisprom also asked for explanation of linked vs docker storage.
