### ISSUE TITLE
Consider enhancing reply/retweet collection abilities

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#502]
To support Professor Waisbord's (SMPA) research need to more easily measure the "interactivity" of a Twitter account:
- Consider adding `in_reply_to` column to Excel/CSV extracts
- Consider flag to attempt to harvest tweets that a tweet already being collected retweeted and/or replied to

**Comment by kerchner** [comment]
`in_reply_to_screenname` is in export currently, but not the ID of the tweet that's being replied to.

**Comment by kerchner** [comment]
Ref. Justin's upcoming Jupyter notebook.

**Comment by lwrubel** [comment]
Also relevant to research by several of Briant's teams.

**Comment by lwrubel** [comment]
This ticket involves applying the changes if they are determined to be worthwhile.

**Comment by justinlittman** [comment]
No longer significant.
