### ISSUE TITLE
Consider add links from seeds to social media websites

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#504]
As suggested by Yonah, it would be helpful to have links from seeds to the social media websites.  For example, from "justin_littman" to https://twitter.com/justin_littman.  This would make it easier for new curators of collections to understand the seeds in the collection.

**Comment by kerchner** [comment]
This was in "Old SFM" and was helpful.

**Comment by lwrubel** [comment]
Would have been helpful in setting End of Term seedlist.

**Comment by lwrubel** [comment]
Check in with Yonah (working for Vakil) once this is implemented, for feedback.

**Comment by kerchner** [comment]
As per conversation:
- On the collection seed list page, add a new column with just the platform icon, where the icon links (in each row) to the respective profile page.
- On the seed detail/edit page, where there is more room, show the platform profile url (link) in full form.

**Comment by justinlittman** [comment]
Need to handle when there is no token as in the following screen shots.
![screen shot 2016-12-01 at 4 59 27 pm](https://cloud.githubusercontent.com/assets/588335/20814429/97336bf6-b7e7-11e6-97e0-2433faef49ff.png)

![screen shot 2016-12-01 at 4 58 49 pm](https://cloud.githubusercontent.com/assets/588335/20814435/9d49f122-b7e7-11e6-8d66-dc9ea4cf49d9.png)

![screen shot 2016-12-01 at 4 58 31 pm](https://cloud.githubusercontent.com/assets/588335/20814445/a4fbc742-b7e7-11e6-8755-a83de7fd0313.png)

**Comment by adityadharne** [comment]
@justinlittman yes, the options are either to not show it at all, or to add a link to the seed in its place. Which one should I go ahead with? Any other ideas?

**Comment by justinlittman** [comment]
Actually I'd suggest adding another column called "Link".  If there is no link then leave blank.  That will allow handling Twitter and Flickr (where it is related to the token) and Tumblr (where it is related to the UID).

Also remember that the seed detail page should not display the link if there isn't one.

**Comment by adityadharne** [comment]
@justinlittman that is a link column with the icon, or the entire link? Can twitter have a UID but not a token?

**Comment by justinlittman** [comment]
Link column with the icon. Twitter can have a UID but not a token.
