### ISSUE TITLE
Standardize date format for exports

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#505]
As reported by Yonah, experts for different types of social media use different date formats.  For example, Twitter uses MM/DD/YYYY, whereas Flickr uses YYYY-MM-DD.  The recommended format is YYYY-MM-DD (ISO 8601).

**Comment by lwrubel** [comment]
see #506

**Comment by justinlittman** [comment]
@Tanych Where is the PR for this ticket?

**Comment by Tanych** [comment]
@justinlittman 
as the Flickr says [here](https://www.flickr.com/services/api/misc.dates.html), the `taken date` always be displayed in the timezone of the photo owner. The date gets from the API would be like ` "taken": "2013-03-26 05:50:01"`. It has no timezone infos, do I need to get these info and do the convert?

**Comment by justinlittman** [comment]
For our current purposes, I would say no.  Simpler approach is OK.

**Comment by kerchner** [comment]
Flickr export data dictionary can note `taken` timezone info as described in the link above.

**Comment by kerchner** [comment]
PR is https://github.com/gwu-libraries/sfm-flickr-harvester/pull/14

**Comment by kerchner** [comment]
Fixed in gwu-libraries/sfm-flickr-harvester#14
