### ISSUE TITLE
Flickr export date posted format

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#506]
The format of the date posted in the Flickr export is not particularly helpful.  It should be in the same format as date taken.

![screen shot 2016-10-31 at 1 35 05 pm](https://cloud.githubusercontent.com/assets/588335/19864536/0cec68a2-9f6f-11e6-91be-19724329dbf4.png)

**Comment by Tanych** [comment]
Date Note in Flickr
https://www.flickr.com/services/api/misc.dates.html

**Comment by justinlittman** [comment]
I've reviewed this and it is ready to be merged once 1.3.1 is tagged.
