### ISSUE TITLE
Add like count to Twitter export

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#507]
As suggested by Yonah, a column for like counts should be added to Twitter export.

**Comment by lwrubel** [comment]
Roll this work into #482.

**Comment by adityadharne** [comment]
PR is https://github.com/gwu-libraries/sfm-twitter-harvester/pull/21

**Comment by yonahbg** [comment]
Not sure if this is worth going into, but the export includes "favorite_count" rather than "like_count", favorites having been phased out in 2015.

**Comment by yonahbg** [comment]
As commented above, "favorite_count" should probably be "like_count", reflecting a Twitter-wide nomenclature change in 2015. This could also be an API problem.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-twitter-harvester/commit/0d7c70d3e3a4749caa191771e3227d1554543ff0
