### ISSUE TITLE
Excel export files require repair

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#514]
Opening every Excel export from SFM on my Mac consistently results in 
![exporterror](https://cloud.githubusercontent.com/assets/3451175/19973034/5e2cec1c-a1ba-11e6-81a8-68d29227649e.jpg)

The file can be repaired and seems to behave well after that, but we are probably not creating it correctly.

**Comment by kerchner** [comment]
@adityadharne you noted a problem with JSON exports, can you describe it here?

**Comment by adityadharne** [comment]
This the error I get:
![screenshot from 2016-11-03 12 15 56](https://cloud.githubusercontent.com/assets/15873333/19974642/8403857c-a1bf-11e6-8fc9-2f5ce3b53579.png)

**Comment by kerchner** [comment]
@adityadharne Which application are you using to open to JSON document?

**Comment by adityadharne** [comment]
@kerchner using Firefox with JSONView

**Comment by justinlittman** [comment]
That's because it is a line-oriented JSON file, which isn't valid JSON.  Each of the lines is valid JSON.

**Comment by kerchner** [comment]
👍

**Comment by Tanych** [comment]
@kerchner could you send me the file that can't open?

**Comment by kerchner** [comment]
sent via email

**Comment by Tanych** [comment]
thanks!

**Comment by Tanych** [comment]
The detail of the issue for `openpyxl` is [here](https://bitbucket.org/openpyxl/openpyxl/issues/442) , currently, there is no any better way to handle such edge cases. A simple solution for this is to prefix the value with a single quote. But, there might another edge case such as `-test`,'1/0' etc.

**Comment by Tanych** [comment]
For the `openpyxl`, if we set to the cell to `TYPE_STRING`, it also will check whether it stats with '=', if so, mark the cell as formula.
```python 
elif isinstance(value, STRING_TYPES):
            value = self.check_string(value)
            self.data_type = self.TYPE_STRING
            if len(value) > 1 and value.startswith("="):
                self.data_type = self.TYPE_FORMULA
            elif value in self.ERROR_CODES:
                self.data_type = self.TYPE_ERROR
            elif self.guess_types:
                value = self._infer_value(value)
```

Whether we should consider using [xlsxwriter](https://github.com/jmcnamara/XlsxWriter) to write xlsx, it supports to disable convert string to formula.

I think the big difference between `openpyxl` and `xlsxwriter` is that openpyxl focuses on deal with `xlsx` files including loading, modify while `xlsxwirter` pays attention to write file as `xlsx` format.

https://xlsxwriter.readthedocs.io/workbook.html

**Comment by Tanych** [comment]
For this issue, adding a single quote before and after the `text` field. The excel can consider the `text` as a regular string not the formula. It might modify the data, but can avoid the open failure.

**Comment by Tanych** [comment]
@kerchner you can retest the formula issue for twitter export when PR https://github.com/gwu-libraries/sfm-twitter-harvester/pull/30 and https://github.com/gwu-libraries/sfm-utils/pull/27 are merged.
It can guarantee no problem when exporting to `xlsx` but not `csv`.

**Comment by justinlittman** [comment]
I tested and this works for xlsx, but not csv.
