### ISSUE TITLE
Supervisor fails on Twitter stream harvester container restart

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#516]
As reported by Maria @ IA, when a Twitter stream harvester container restarts and there is an existing harvest, the restarted container fails when supervisor tries to restart the harvest.

```
twitterstreamharvester_1  | Error: The directory named as part of the path /var/log/sfm/0d3e7c0fefd041f0962183f269fe4abb.out.log does not exist. in section 'program:0d3e7c0fefd041f0962183f269fe4abb' (file: '/etc/supervisor/conf.d/0d3e7c0fefd041f0962183f269fe4abb.conf')
twitterstreamharvester_1  | For help, use /usr/local/bin/supervisord -h
```

The problem is that the log directory is created [here](https://github.com/gwu-libraries/sfm-utils/blob/master/sfmutils/supervisor.py#L39).  Thus, when the container comes back up and supervisor tries to restart the job, the log directory hasn't been created yet.

The proper solution is to move the logs to the container working directory. This way the directory will exist on restart.

**Comment by adityadharne** [comment]
I had the same issue a while back.

**Comment by justinlittman** [comment]
I can't replicate the problem.  I suspect it is a race condition.  However, it is still a good idea to move logs to working directory.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-utils/commit/40042b8723fb9540e37cb68770432dae28d04cd7
