### ISSUE TITLE
Twitter warning messages for suspended or private accounts do not accurately describe issues 

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#517]
Currently:

|  When an account is actually... |  SFM warning message is... | But should be... |
| ------------------- | ------------------ | ---------------- |
| Protected | Unauthorized for user AAmerikia because account is suspended or private |  Unauthorized for user AAmerikia because account is protected |
|  Suspended | User id not found for user _99DieLowin99_ | Unauthorized for user _99DieLowin99_ because account is suspended or not found |
|  Not Found | User id not found for user asfdjidasdfiojasdfjklasdfjkljklasdfjjkl | User id not found for user asfdjidasdfiojasdfjklasdfjkljklasdfjjkl because account is suspended or not found (Correct as is) |

The account statuses above were verified by browsing to http://twitter.com/<screen name> .  Bear in mind that the statuses of these particular accounts may change by the time you work on this ticket.

Also note that when an account is Protected, SFM does currently populate the seed's User ID.  This is correct as is.  When it's suspended or not found, Twitter doesn't provide the User ID, so SFM can't/doesn't populate the seed's User ID.

**Comment by justinlittman** [comment]
* If we have screen name, can get user id if OK or protected.  Otherwise, 404 if suspended or not found.
* If we have user id, can get screen name if OK or protected.  Otherwise, 404 if suspended or not found.  However, we then try user timeline and get 401.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-twitter-harvester/commit/6f74815d651f06575d54ad23bd36b60eab5e046a
