### ISSUE TITLE
Collection page: Consider links near the top to jump to sections

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#519]
When the list of seeds is long, the Collection page is also very long.  Often I find myself wanting to view the harvest log.  An easy solution would be adding anchor tags for the different page sections, and placing navigation links (to jump to those sections) near the top.   This would also increase usability for mobile users.

Perhaps consider this for other pages, but I think the Collection page is the one that primarily needs it.

**Comment by lwrubel** [comment]
Discuss this issue with the UX consultant in Jan 2017 and seek his advice.

**Comment by justinlittman** [comment]
Consider using Bootstrap scrollspy.

**Comment by lwrubel** [comment]
Might fit into @adityadharne's work on 1.6 and seed list. Try scrollspy first.

**Comment by lwrubel** [comment]
Relates to #679.
