### ISSUE TITLE
Export notifications should be emailed to only the user who requested the export

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#524]
Export notifications are currently being emailed to all users in the collection's group.

**Comment by adityadharne** [comment]
- Despite having set `Access for less secured apps` to `ON`. I get this (most of the time): 
```ERROR 2016-12-05 10:47:56,042 66 message_consumer.sfm_ui_consumer Error sending email: (534, '5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuk\n5.7.14 5JZMUF5Qr7ceNyeeVkwxKRDwDo2YqcFKXJpRKb827Vv6v9IffLSbREg5D0sUZ9R6kHFw4u\n5.7.14 bX9PLYO6uN_VDJPMRdLaBAArsN8s1k8YUmERxp1LT09XpEczHcGQQJgIzExxPfrRLC3hlF\n5.7.14 puKGjf0MRQz9ztWOE3mxHk8YborwGQn7tFtD7bCA18L2Lr3hTtBQyJysvyBVskyXEKviRE\n5.7.14 lND7mWVt-wfwSf5dC_5jvBkZ9F7S0> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 q53sm9714015qtq.0 - gsmtp')```

- There is sometimes a significant delay in the emails when it does go through; anywhere from 2-24 hours.

- Another observation; the emails that do come through are for harvest notifications.

**Comment by adityadharne** [comment]
- Cannot recreate this bug; emails are being delivered to the user who requested the export and not to the entire group.

**Comment by justinlittman** [comment]
And looking at the code, it appears that is should only go to the user who requested the export.

**Comment by kerchner** [comment]
@kerchner needs to specify example where this is occurring

**Comment by adityadharne** [comment]
Export notifications are currently being emailed to the user who requested it.
