### ISSUE TITLE
Consider upgrading pip

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#527]
I've forgotten why we have it pinned with an old version.

**Comment by lwrubel** [comment]
Version in use is two versions old.

**Comment by Tanych** [comment]
### Testing case
* `pip` upgrade to `9.0.1`
* all the containers build locally based on the new sfm-base
* testing exporters and hasversters

when upgrade the `pip` verison to `9.0.1`, all the harvesters and exporters works well for the master branch.

|                       | Haverster | Exporter | Web harvester |
|-----------------------|-----------|----------|---------------|
| Flickr user           | ✓         | ✓        | ✓             |
| Tumblr posts          | ✓         | ✓        | ✓             |
| Twitter search        | ✓         | ✓        | ✓             |
| Twitter user timeline | ✓         | ✓        | ✓             |
| Weibo timeline        | ✓         | ✓        | ✓             |
| Twitter Filter       | ✓         | ✓| ✓          |
| Twitter Sample        | ✓         |  ✓ | ✓          |

Not sure whether there are other issues related the upgrading.

**Comment by Tanych** [comment]
test both link-in sfm-utils and not link sfm-utils.

**Comment by Tanych** [comment]
Building image locally and not link the  `sfm-utils` in local directory. Testing the functions.
All seems to work well.

**Comment by lwrubel** [comment]
@justinlittman ready to implement.

**Comment by justinlittman** [comment]
Fixed by:
* https://github.com/gwu-libraries/sfm-utils/commit/dc3967d11160956e1afb69328c6b25887d569167
* https://github.com/gwu-libraries/sfm-ui/commit/31d0b33cc11c772d6bcdfc325b5448d9b8ac4084
* https://github.com/gwu-libraries/sfm-twitter-harvester/commit/66bf7634d21fa0f69a143c37c9c58cddac0340ef
* https://github.com/gwu-libraries/sfm-flickr-harvester/commit/f76fffe6798c82e49dc5c2df772f80fa077af2a2
* https://github.com/gwu-libraries/sfm-tumblr-harvester/commit/37c47feecd4b4db17b1e087fcb2dae2e263cf71c
* https://github.com/gwu-libraries/sfm-web-harvester/commit/ad207a363104d5f5eccd2d2cbe1feef6788b6c89
* https://github.com/gwu-libraries/sfm-weibo-harvester/commit/042be86b8aa36919476d9b22ca9d1eb8bc73d6c3
* https://github.com/gwu-libraries/sfm-docker/commit/6929f81a4e456485d3b13b33d1f7aaf7e101e236
* https://github.com/gwu-libraries/sfm-elk/commit/8159e98d50725838b92deca58f9caffe89471c5a
