### ISSUE TITLE
Twitter export is not consistently extracting URLs

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#531]
This issue came about in supporting GW researcher S. Karaoglu, who is relying on the URL columns to identify tweets that may contain embedded images.  The issue described herein results in some tweets potentially being missed, i.e. not identified as containing links when the tweet actually does contain links/embedded media.

### Tweets with URL in text but not in `['entities']['urls']` resulting in empty URL columns in the extract

Exports to Excel format (and I assume CSV as well) are not consistently extracting URLs from the tweet text.   Some are retweets and some are not.  Relevant code is [here](https://github.com/gwu-libraries/sfm-twitter-harvester/blob/master/twitter_rest_exporter.py#L45-L46).   Next step would be to see whether Twitter is or is not consistently populating `['entities']['urls']`.  If not, we should consider to not rely on `['entities']['urls']` but instead use regex matching on the tweet text to achieve more consistent extraction of URLs.

Some examples of tweets where the export url1 column was empty but should not have been:

http://twitter.com/RFERL/status/795370889370071040
text = `FBI director says new batch of e-mails doesn't change previous conclusion on Hillary Clinton case https://t.co/NUJ7XNgru2`

http://twitter.com/VOANews/status/795362434961829889
text = `RT @W7VOA: Here's the new @FBI letter regarding @HillaryClinton investigation. #VOAalert https://t.co/uCBZtZ65sX`

It appears that these occur in the case of embedded media as opposed to links pointing outside of Twitter (or to other tweets, e.g. retweeted tweets).  It is possible that it might occur in the case of external links, but I wasn't able to identify an example.

### Retweets containing embedded media

Retweets with embedded images are rendered in Twitter with the embedded image, but often the URL is truncated in the text of the [primary] tweet and the URL also doesn't appear in ['entities'].  However, we should strongly consider extracting URLs from `['retweeted_status']['text']` (and/or `['retweeted_status']['entities']`

Example:
http://twitter.com/VOANews/status/795435289061769216
text = `RT @CarolynVOA: #Election2016 Turning the glass #nyc convention center into the #HillaryClinton election night party #VOAalert https://t.co…`

**Comment by adityadharne** [comment]
- There is a `['media_url']` field in `['entities']` which gives links to the embedded media (uploaded media). We can add this to the export.  
- The `['media_url']`for http://twitter.com/RFERL/status/795370889370071040 is http://pbs.twimg.com/media/Cwm5gXlXEAA1hnm.jpg

**Comment by kerchner** [comment]
@adityadharne Thanks for your analysis.  Yes, please proceed with adding a new export column to extract ['media_url'] 👍

**Comment by adityadharne** [comment]
PR Ref: https://github.com/gwu-libraries/sfm-twitter-harvester/pull/24

**Comment by kerchner** [comment]
Fixed in https://github.com/gwu-libraries/sfm-twitter-harvester/pull/24
