### ISSUE TITLE
Keep track of changes to collections, seed sets, seeds

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#54]
https://github.com/etianen/django-reversion?

**Comment by justinlittman** [comment]
https://www.djangopackages.com/grids/g/model-audit/

**Comment by justinlittman** [comment]
I'd take a closer look at these:
* https://github.com/treyhunner/django-simple-history
* https://github.com/jjkester/django-auditlog

**Comment by justinlittman** [comment]
So like django-reversion, django-simple-history records historical versions of model objects.  This is optimized for reverting to a previous version of a model object.  However, it is not optimized for our use case of wanting to provide a log of changes.  (We would be responsible for comparing versions and determining what has changed.)

**Comment by dchud** [comment]
It seems possible that both goals might be worthy features - an "undo" based on -reversion or -simple-history might be something users are glad to have.  But, yes, the goal of this ticket is to log changes for the sake of record keeping.

**Comment by justinlittman** [comment]
A few notes:
* Until https://github.com/jjkester/django-auditlog/pull/47 is accepted, referring to our fork of django-auditlog.
* Formatting of the history is performed in `templates/ui/history_snippet.html`. This approach can be changed depending on what makes the most sense for the UI.
* A note field is added to the collection, seed, and seedset model.  This is a sneaky way of adding a note to the log entry.  The note field in model instances should be ignored.  (In the model update pages it is set to blank.)  When formatting the log entry, the note can be extracted and handled appropriately.

**Comment by justinlittman** [comment]
Per discussion with @kerchner and @lwrubel, leaving not merging these commits until later this milestone or early next.

**Comment by justinlittman** [comment]
For #117, this will need to be added to sfm_ui_consumer.py:

When seeds are updated based on tokens that have changed:
```
                       seed.note = "Updated token based on harvest {}".format(self.message["id"])
```

When seeds are updated based on uids that have been found:
```
                        seed.note = "Updated uid based on harvest {}".format(self.message["id"])
```

**Comment by justinlittman** [comment]
Also, in test_sfm_ui_consumer.py when checking updated seeds:
```
        self.assertTrue(seed1.note)
```
and
```
        self.assertTrue(seed2.note)
```

**Comment by kerchner** [comment]
Resolved in https://github.com/gwu-libraries/sfm-ui/pull/151
