### ISSUE TITLE
Credential process needs to be clarified and explained

### ISSUE THREAD

**Issue by yonahbg** [gwu-libraries/sfm-ui#544]
The process for getting each credential isn't necessarily easy or straightforward. This can be clarified in the documentation. 

Two elements: better explanation about why individual credentials are needed; better explanation about how credentials are actually acquired, especially explaining some of the more complicated or confusing aspects (like organization name).

**Comment by justinlittman** [comment]
@yonahbg:  Can you also take into account these comments from @chrisprom:

> I think [this section of the doc](https://sfm.readthedocs.io/en/latest/credentials.html#connecting-credentials) needs a bit more background information.  I tried setting up the connecting credentials on my laptop instance, but it gives me an ‘error logging into social media accounts’ error message. But, that might be because I am running off localhost.

**Comment by justinlittman** [comment]
Comment from @chrisprom on Twitter:

> Twitter: consider adding a few more instructions on how to get the secret key and the Access tokens from Twitter.  I was able to figure out how to do it, but possibly only because I had done this before since the way you get them set up in twitter is not overly intuitive since they separate stuff into different tabs.

**Comment by justinlittman** [comment]
Comment from @chrisprom on Tumblr:

> Is was unclear if I should use Oauth key or the secret key.  I put in the secret key and had to go back in put in Oauth key after getting an error message.  In general your language here should match what Tumblr says.

**Comment by yonahbg** [comment]
I'm taking care of the second two comments, but I don't know enough about desktop instances to be able to explain anything in [this section of the doc](https://sfm.readthedocs.io/en/latest/credentials.html#connecting-credentials).

**Comment by justinlittman** [comment]
OK.  Assign the ticket to me when you're done and I'll handle that section.

**Comment by yonahbg** [comment]
I made the fixes, it's ready for you.
