### ISSUE TITLE
Twitter collection type documentation needs clarification

### ISSUE THREAD

**Issue by yonahbg** [gwu-libraries/sfm-ui#546]
Twitter documentation should be clearer and include more specific answers and suggestions.
One example that needs to be added is explaining which collection types cannot be used at the same time.

**Comment by justinlittman** [comment]
Comment from @chrisprom on user timeline:

> * Quote: “To identify a user timeline, you can provide a screen name or Twitter user ID (UID). If you provide one, the other will be looked up and displayed in SFM UI.” → This is only true after the first harvest runs, so you may want to note that.
> * It will be unclear to new users if the “twitter screen name” is the @ handle (e.g. “@UIPD”) or the the visual user name (e.g. “U of I Police”).  Twitter documentation is not clear on their own nomenclature, so your docs should make clear what needs to be put in the field.  I think you can just call it the username and give an example such as @SocialFeedMgr.  Again, make sure the language used matches whatever the social media platform calls it.

**Comment by justinlittman** [comment]
Comment from @chrisprom on search:

> “To formulate a search query, use the Twitter Advanced Search query builder. Pay careful attention to the query syntax described in Twitter’s documentation.”  
> * Not sure what you mean by “Twitter’s documentation” since that seems non-existent to me.  The interface you reference runs a query, then spits back a results page.  It seems to be that the user should just try a sample query there, then cut and paste from the header of the results page into SFM, so perhaps your documentation could be simplified.
