### ISSUE TITLE
Elasticsearch won't start up

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#550]
From the elk log:
```
elk_1                     | bootstrap checks failed
elk_1                     | max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
```

Ref https://github.com/docker-library/elasticsearch/issues/98 - it appears that this issue was introduced with 5.0.  The sfm-elk Dockerfile doesn't currently reference a particular build of the elk dockerhub image, so the solution lies in pinning to a pre-5.0 elk image.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-elk/commit/a3746635d53a2bcedad15dcb12c591d6adf890c9
