### ISSUE TITLE
Persist SFM objects loaded in ELK

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#556]
Currently the ELK data is stored in a directory named by the docker container ID, which will change if the ELK container is recreated.

Instead we'd like to persist it so that the loaded data will be present if the container is recreated.  One way we can accomplish this is by using the SFM collection set ID instead of the docker hostname.

**Comment by kerchner** [comment]
Data persistence is needed for GW Program On Extremism support; they would like to take advantage of SFM ELK analytics starting in Jan. 2017 or sooner if possible.

**Comment by justinlittman** [comment]
An alternative is to set the hostname in the docker-compose file instead of depending on docker to generate one.  See https://docs.docker.com/compose/compose-file/#/cpushares-cpuquota-cpuset-domainname-hostname-ipc-macaddress-memlimit-memswaplimit-oomscoreadj-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir

**Comment by justinlittman** [comment]
There are 3 possibilities for scoping an ELK instance:
* Everything (if the `command: --collection-set` is omitted)
* A collection set (if the `command: --collection-set` is included)
* A collection (pending https://github.com/gwu-libraries/sfm-ui/issues/463)

I'd recommend that the solution take all of these into account.

**Comment by kerchner** [comment]
@justinlittman How about if we simply rename the variable that will uniquely (and persistently) identify this ELK instance's indexing etc. data to something more neutral, like `ELK_DATA_ID` (open to other suggestions).   One could choose to set its value to the collection id, a name (e.g. "poe"), or any identifier.

This still leaves configuration of the `--collection-set` option open to all of the options above.

**Comment by justinlittman** [comment]
I've tested this and works correctly.

Comments:
* Also add hostname config to example.prod.docker-compose.yml.
* Consider tweaks to wording of http://sfm.readthedocs.io/en/latest/exploring.html#enabling-elk

OK to merge after fixing above.

**Comment by kerchner** [comment]
@justinlittman resolved as per above (see additonal, new pull request #557 for documentation tweak)

**Comment by kerchner** [comment]
Fixed in:
 - https://github.com/gwu-libraries/sfm-elk/pull/5
 - https://github.com/gwu-libraries/sfm-docker/pull/11
 - https://github.com/gwu-libraries/sfm-ui/pull/557
