### ISSUE TITLE
Remove twarc dependency from sfm-weibo-harvester

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#563]
Determine why sfm-weibo-harvester requires twarc.  If it doesn't, remove the dependency.

**Comment by justinlittman** [comment]
It is used here:  https://github.com/gwu-libraries/sfm-weibo-harvester/blob/master/weiboarc.py#L13

Weiboarch is based on Twarc and re-uses a few methods from it rather than duplicating.
