### ISSUE TITLE
Change log needs a way for a user to describe why collection was turned on/off

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#566]
A very common scenario I see is that the user wants to turn on and/or off a collection, but there is currently no way to note a description associated with this change, in the change log.

Possible options:
- A way to amend a change log item's Description field after the fact
- A way to enter a no-change change log entry, for the purpose of being able to add a description (which would essentially be used to describe the previous change)
- A clean way to provide the option of entering a Description with a turn on/off change, at the time of the change.  Might be tricky to do this without complicating the UI, but not impossible.

**Comment by justinlittman** [comment]
More broadly, a user should be able to add an arbitrary note to the change log that is not tied to a change.

**Comment by justinlittman** [comment]
Grrr ... I mistakingly committed to master.

@lwrubel Can you take a look at this from a UI perspective? I'm suspect you might want to put these features on the page differently.
