### ISSUE TITLE
Add entry in change log for Collection when seeds are added

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#567]
Currently the change log allows the user to answer the question of "When did I add this particular seed?" but an equally important question I come across is "What seeds were recently added to this collection?" and there is currently no easy way to answer that, especially for collections with many seeds.   All that you would see in the change log is that the collection was turned off and back on, but no clue as to what edit occurred during that time - usually a seed add.

A solution would be to have the addition of a child seed trigger creation of a new entry in the parent collection's change log to note the seed's (or seeds') addition.

**Comment by justinlittman** [comment]
Duplicate of #377
