### ISSUE TITLE
Other users' collections can be accessed through the Monitor feature.

### ISSUE THREAD

**Issue by yonahbg** [gwu-libraries/sfm-ui#571]
In the Monitor feature, under Harvester status, all of the collections that are undergoing harvests are listed. This (apparently) includes all harvests from the iteration in the last 3 days. These harvests are linked, and through them, one can access the collections of other users. 
While the lack of security between accounts has been an existing issue, this is especially problematic since this makes the collections of others very accessible.

**Comment by justinlittman** [comment]
Consolidated into #362
