### ISSUE TITLE
Warn admins on long queue lengths

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#574]
![screen shot 2016-12-06 at 7 14 22 am](https://cloud.githubusercontent.com/assets/588335/20925239/bd4a36f4-bb83-11e6-89af-369c9b5e3105.png)

**Comment by lwrubel** [comment]
This severely impacts the Twitter rest harvester for all SFM users. Discuss design with @justinlittman before implementation.

**Comment by Tanych** [comment]
@justinlittman 
what I think with this issue is that we can add an `interval` job (can be 2 hour or 4 hour) to check the queue message, if any queue of the request is larger than the setting threshold( might be 100) , we will send a message to the admin.

**Comment by justinlittman** [comment]
So rather than implement multiple checks (e.g., space usage, queue lengths) each of which are scheduled separately, I'd prefer to see a single health check has one schedule, but performs multiple checks.

**Comment by Tanych** [comment]
That's true, one schedule job checks all queue info, if any of them has reached the limit, warning message will sent.

**Comment by lwrubel** [comment]
@justinlittman  ready for testing
