### ISSUE TITLE
Fix footer for smaller windows to allow access to Documentation

### ISSUE THREAD

**Issue by yonahbg** [gwu-libraries/sfm-ui#584]
When the window is too small, the footer disappears.
This is how it is for the large screen, with this header:
![header large screen](https://cloud.githubusercontent.com/assets/23175249/21025508/b70065a0-bd56-11e6-817b-11c98ffe76e1.JPG)

Which then has this footer, which gives version number, documentation, etc.:
![footer large screen](https://cloud.githubusercontent.com/assets/23175249/21025510/b7014a74-bd56-11e6-9734-a64c1832dd96.JPG)

However, when the window is too small and switches modes, with this header:
![header small screen](https://cloud.githubusercontent.com/assets/23175249/21025509/b700cbb2-bd56-11e6-863c-0b1a06280958.JPG)

Then the links in the footer disappear:
![footer small screen](https://cloud.githubusercontent.com/assets/23175249/21025507/b6ff5fd4-bd56-11e6-8ea5-54042a74ed33.JPG)

**Comment by justinlittman** [comment]
Works now.
![screen shot 2017-02-06 at 3 02 12 pm](https://cloud.githubusercontent.com/assets/588335/22664167/74b1afa0-ec7d-11e6-8b11-f41d5a07fb5d.png)
