### ISSUE TITLE
Consider adding collection start date

### ISSUE THREAD

**Issue by yonahbg** [gwu-libraries/sfm-ui#585]
It would be useful, especially for event capture collection, to have a collection start date in addition to the end date. That way, only records during the desired time are recorded.

Problems with this may include that the process of turning a collection on may be confusing to the system.

**Comment by justinlittman** [comment]
Additional suggestion from @yonahbg:

> When we met last, we talked about the idea of being able to add a start date rather than just an end date. The main concern was being able to distinguish between being "on" and "off," which was both from a UI problem and back end issue.

> I had an idea for it, which I'm not sure if it's possible: a "yellow" mode. (I don't have the right word yet, so yellow is a substitution, but it would be "pending" or "scheduled" or the like; yellow in contrast with Red off and Green on).

> Then, if one wants to schedule a collection to start at a specific time (say, tweets from @whitehouse from the incoming administration, so beginning at noon on Jan 20), a start date and time would be entered. Then, the mode toggle would, rather than turn "on", turn "yellow." Such a "yellow" status would then turn, automatically, to "on" at the scheduled time.

> Similarly, if a collection has a scheduled end, it could switch from "on to "yellow", instead of "off". I imagine that it would make it easier this way as well as provide the added benefit of knowing when a collection functioned properly but simply came to the end of its scheduled time.

**Comment by justinlittman** [comment]
Has not been significant user requests for this feature.
