### ISSUE TITLE
Exporter memory problem

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#588]
This is based on a problem encountered with http://ec2-54-234-3-231.compute-1.amazonaws.com/ui/exports/14/

Steps to reproduce:
1.  Create a collection containing at least 500,000 tweets.
2.  Request an excel export containing all of the tweets.
3.  Observe memory usage (e.g., with `top`).

Expected result:
Export completes successfully.

Actual result:
Server runs out of memory and becomes unresponsive.

**Comment by Tanych** [comment]
@justinlittman  There might be a memory leak problem in the exporter when I doing some simpler tests. Exporting 200,000  tweets to `xlsx` need 2.4G mem while the mem is not free when exporting is done. I will  keep looking at what's going on here.

**Comment by kerchner** [comment]
For 1.4, we can consider adding a warning in the UI regarding large Excel exports, i.e. that 200,000 tweets typically requires ~2.4GB of memory (also determine what 100,000 requires).   The user may want to consider exporting to CSV, then loading the CSV into Excel.  Work with @lwrubel on wording.

**Comment by Tanych** [comment]
For the memory issue, whether we should consider use `xlsxwriter` when exporting to the `xlsx` files.
The memory benchmark is as follow:
http://xlsxwriter.readthedocs.io/working_with_memory.html

One big advantage for `xlsxwriter` is that it can write in constant memory mode.

**Comment by justinlittman** [comment]
Options:

1. Provide UI warning against large XLSX exports.
2. Remove XLSX support and rely on CSV.
3. Write a PETL writer that uses xlsxwriter.

I recommend 2.

**Comment by lwrubel** [comment]
Suggested wording for now, to put into dropdown Export format field: 
"Excel (XLSX) - For more than 100,000 tweets use CSV instead"

(assuming 100,000 is a good cutoff)

**Comment by justinlittman** [comment]
@lwrubel Tweet or items?

**Comment by Tanych** [comment]
For the solution  3, we will not use PETL. Actually, totally using xlsxwriter. It might be less than 10 line code for implement the exporting. 
```python
def to_xlsx(table,source):
    """
    Using xlsxwrite table to xlsx, using openpyxl has memory issue.
    """
    workbook = xlsxwriter.Workbook(source, {'constant_memory': True})
    worksheet = workbook.add_worksheet()

    for idx, row in enumerate(table):
        for idy, col in enumerate(row):
            if hasattr(col, 'isoformat'):
                worksheet.write(idx, idy, col.isoformat())
            else:
                worksheet.write(idx, idy, col)
    workbook.close()
```
But it needs more tests on exportings.

**Comment by Tanych** [comment]
### Mem monitor
Exporting `209,294` tweets using `xlsxwriter` and `petl.toxlsx`.
### xlsxwriter
* Time cost
147s
* mem graph
Memory cost constantly about 136MB.

![mem-graph](https://cloud.githubusercontent.com/assets/3956411/21320708/fe7c01e6-c5df-11e6-9549-77a7ccd8e494.png)

### petl.toxlsx
* Time cost
177s
* mem graph
Memory cost about `2.5GB`, max reaches `4.2GB`.

![mem-openpy](https://cloud.githubusercontent.com/assets/3956411/21320806/42693b80-c5e0-11e6-8481-3b11ea687dd4.png)
