### ISSUE TITLE
Changes to messaging spec re: warcs created

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#59]
* Add number of WARCs created and size to harvest status message.
* Remove APIs called from WARC created message.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-ui/wiki/Messaging-Specification/_compare/de063f60d658a0b8915acebf8275ed38092f5250 for the change to the spec.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-utils/pull/5 makes the changes in BaseHarvester.

**Comment by kerchner** [comment]
Closing; fixed by https://github.com/gwu-libraries/sfm-utils/pull/5
