### ISSUE TITLE
In documentation, add links to archived social media platforms' data dictionaries

### ISSUE THREAD

**Issue by reliztrent** [gwu-libraries/sfm-ui#595]
e.g., http://sfm.readthedocs.io/en/latest/data_dictionary.html could link to:

Twitter API documentation - https://web.archive.org/web/*/https://dev.twitter.com/docs
Tweets - https://web.archive.org/web/*/https://dev.twitter.com/overview/api/tweets (this may have had an alternate URL before January 2015)
Entities - https://dev.twitter.com/docs/platform-objects/entities

**Comment by lwrubel** [comment]
@yonahbg I can give context and explanation for this. See me (or email) for discussion first. Roll in with #586, #587, #599.

**Comment by lwrubel** [comment]
Closing since work is merged into master with data dictionary work.

**Comment by kerchner** [comment]
Closed in #621
