### ISSUE TITLE
setup and document docker

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#6]
To only include rabbitmq service.

**Comment by dchud** [comment]
New repo to be "sfm-docker".

**Comment by dchud** [comment]
Also: investigate adding other GW Libs staff to have sufficient admin rights on docker hub.

**Comment by kerchner** [comment]
Succcessor to #8

**Comment by justinlittman** [comment]
@kerchner added as an owner of [gwul](https://hub.docker.com/u/gwul/) organization.

**Comment by justinlittman** [comment]
See https://github.com/gwu-libraries/sfm-docker/commit/d1b5ea22cf059695288dec632fca1c79c97dc909 for setup and documenting docker.

Will add documentation once docs directory is setup.

**Comment by rajatvij** [comment]
Pull request accepted. hence closing the ticket.
