### ISSUE TITLE
Tumblr harvester warc file is not the real status 

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#619]
Since the Tumblr APIs don't support `since_id` and `max_id`. It only supports offset of the status stack. The posts save like followings stack, the number is the `post_id` which will increase in the latest posts. The latest posts save on the top of the stack. 

| p1 | p2 | p3 |
|----|----|----|
| 5  | 6  | 7  |
| 4  | 5  | 6  |
| 3  | 4  | 5  |
| 2  | 3  | 4  |
| 1  | 2  | 3  |
|    | 1  | 2  |
|    |    | 1  |

On the first harvester, we can harvester all the posts `[1,2,3,4,5]` and record the since_post_id as `5`. Next time, if one new post has created, we need to request the first five posts (in real we do in 50, since we don't know how much new posts create), they are `[6,5,4,3,2,1]`. Because only `6` is larger than the since_post_id `5`, the `tumblrarc` will only return `6`. The same process to deal with `[7,6,5,4,3,2,1]`.

If there are no new posts create, the API request will return `[5,4,3,2,1]` and warc file will create since the warc file are created based on every API requests. However, `tumblrarc` will return `None` because of no new ids are larger than `5`. The real issue is that the new `Baseharvester` add a function `process_warc`. It will get the posts from the warc files not the `tumblrarc`. Thus, every new harvester will record the first 50 posts if there are no new posts in Tumblr account because the mismatch in wac file and real posts we want.

We need to find a way to identify whether there are new posts without generating the old records in warc files. It's similar like to determine whether a twitter uid or screen_name is valid without the warc file creating.

**Comment by justinlittman** [comment]
https://github.com/gwu-libraries/sfm-tumblr-harvester/pull/10
