### ISSUE TITLE
Consider separating Weiboarc out into its own app

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#620]
As part of the CEAL grant, it might be a worthwhile contribution to China social media studies if we separate out Weiboarc (https://github.com/gwu-libraries/sfm-weibo-harvester/blob/master/weiboarc.py) into its own app and publish to pypi, to essentially be Twarc's Weibo equivalent.

**Comment by lwrubel** [comment]
Not doing as part of this grant. Complicated by Weibo permissions difficulties.
