### ISSUE TITLE
Export list of seeds from a collection

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#622]
It would be helpful to be able to export a list of seeds from a collection. In updating the End of Term collection, for example, I'd like to compare what we have with the US Digital Registry. This would also be helpful in sharing with researchers what we are collecting (e.g. list of news outlets).

**Comment by justinlittman** [comment]
It would also be helpful for re-using seed lists in other collections.  For
example, to create a Trump Term collection from EOT seeds.  Or to duplicate
seeds in a test environment.

**Comment by lwrubel** [comment]
To be clear: not using the Export button but a link/button from the collection detail page. Include option to show columns they choose (token, uid, link)

**Comment by kerchner** [comment]
This is only applicable to Twitter user timeline collections, tumblr blog post collections, and flickr user collections

**Comment by lwrubel** [comment]
Add a button for "Export seed list" to the Seeds panel heading. Use export glyphicon. Clicking on the button should lead to a csv with the fields: screenname, userid, link. Either file could automatically download, or a pop-up window with the data could appear. Whatever is easier to implement at this point.

**Comment by lwrubel** [comment]
Per discussion with @justinlittman consider a view, should not involve touching exporter.

**Comment by adityadharne** [comment]
PR: https://github.com/gwu-libraries/sfm-ui/pull/802
