### ISSUE TITLE
Add configuration to hide/unhide Weibo search collection type

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#630]
Since the Weibo search API requires credentials with advanced access, presenting Weibo search as a collection type might be confusing to most users, as most users with Weibo credentials are unlikely to have advanced access.

Add a configuration in the environment variables to (in the UI) show/hide Weibo collection types that require advanced API access (right now this is only the Weibo Search collection type - see https://github.com/gwu-libraries/sfm-ui/pull/624). By default they should be hidden.

**Comment by kerchner** [comment]
When adding this variable to `example.env` (in sfm-docker), provide sufficient comments above the variable to explain it, with links to Weibo (and/or SFM) documentation about Weibo advanced API access.

**Comment by lwrubel** [comment]
Per discussion with @kerchner, this may move into the next milestone if more time needed for review.

**Comment by kerchner** [comment]
Fixed in https://github.com/gwu-libraries/sfm-docker/issues/17 and in #624
