### ISSUE TITLE
Handle Tumblr rate limits

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#637]
Apparently Tumblr enforces rate limits.

The EOT blog harvest failed with:

```
The harvest for Tumblr blogs reharvested (http://ec2-54-144-198-169.compute-1.amazonaws.com:80/ui/harvests/320/) failed.

Error messages:
- 429 Client Error: Limit Exceeded for url: https://api.tumblr.com/v2/blog/americanartluce.tumblr.com/posts?api_key=mUfPa6vLOX7TGge5kupDDOo3lQkRCGoPMUHQJLfDAFgONbd84l&filter=html&limit=50&offset=0
```

Unfortunately, Tumblr doesn't document the rate limits.  According to [this post](https://groups.google.com/forum/#!searchin/tumblr-api/limit|sort:relevance/tumblr-api/LCy7e0j9PeU/F15E_LzuAQAJ), the API limits aren't published and may change.  And according to [this post](https://groups.google.com/forum/#!searchin/tumblr-api/limit|sort:relevance/tumblr-api/EMqJ7N9Jz9w/7W27Pt69-00J) there may be useful HTTP headers.

I'd suggest that we implement a wait on 429 strategy with backoff (similar to what Twarc does for Twitter).

**Comment by Tanych** [comment]
@justinlittman  if the header has no such field like "x-ratelimit-api_followers-reset:", what should be the default time to reset?

**Comment by justinlittman** [comment]
I'd say keep it simple and wait for 5 minutes. I wouldn't count on the header fields.
