### ISSUE TITLE
Add monitoring of sfm_ui queue

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#641]
Because the sfm ui consumer seems to fail regularly and it would be helpful in diagnosing/warning.

**Comment by justinlittman** [comment]
@Tanych Can you roll this into the work on #574?

**Comment by Tanych** [comment]
sure!

**Comment by Tanych** [comment]
@justinlittman 
whether the sfm-ui queue info needs to display at the monitor page?

**Comment by justinlittman** [comment]
Yes, please.

**Comment by Tanych** [comment]
@justinlittman 
some tweaks work on sfm-ui queues
* adding  sfm-ui queue on monitor pages
* adding monitoring for sfm-ui queue

Please review this for PR https://github.com/gwu-libraries/sfm-ui/issues/633.
