### ISSUE TITLE
Harvester log path in docs appears to be wrong

### ISSUE THREAD

**Issue by runderwood** [gwu-libraries/sfm-ui#646]
Docs on monitoring say that harvester logs are in /var/log/sfm/<harvester_id>.out.log. I don't see a /var/log/sfm.

Maybe I'm looking in the wrong place?

**Comment by justinlittman** [comment]
You're right -- they moved and the docs weren't updated.  The correct path is `/sfm-data/containers/<container id>/log/<harvest id>.err.log`, for example, `/sfm-data/containers/bffcae5d0603/log/d4493eed5f4f49c6a1981c89cb5d525f.err.log`.

I will update the docs.

**Comment by runderwood** [comment]
thanks!
