### ISSUE TITLE
Quoted term in Twitter search seed raises uncaught exception

### ISSUE THREAD

**Issue by runderwood** [gwu-libraries/sfm-ui#648]
Entering a term like `"bird law"` raises an uncaught exception in ui/models.py, line 505.

I've fixed it locally by changing line 507 to:

```except (ValueError, AttributeError):```

I can fork and do a pull request if you want. But it's a trivial change. Let me know.

**Comment by justinlittman** [comment]
Our grant would smile kindly upon a pull request.  Thanks!

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-ui/pull/651
