### ISSUE TITLE
Twitter search running infinite with one-time harvester 

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#649]
### Scenario 
* Building a twitter search collection with 5 or 10 minutes task with the schedule.In other words, the end date should be 5 or 10 minutes away.
* Adding a hot topic seed like: `Trump AND inauguration`.
* Turn the collection on.
### Result
The collection won't stop even if it reaches the end time and turn off. Also, we can't export the 5 min collection tweets.
### Details
![collection_sleep](https://cloud.githubusercontent.com/assets/3956411/22115908/bbc2fede-de3c-11e6-9950-6668fcfe3535.png)

During the collection period, the credential has reached the rate limit and go to sleep about 15 minutes. The collection ends in the sleep period. The sfm-ui shows that the collection has been turned off. However, When the sleep period has finished, the twitter search collection will keep collecting tweets. It won't stop even if we kill the containers and restart the containers.

**Comment by runderwood** [comment]
It so happens I've just reproduced this.

It looks like fixing this would require passing the end date to harvesters in the start message. In the case of the Twitter harvester, I think you'd have to have this to wrap the Twarc `rate_limit` function decorator to check current date/time against and shutdown if reached.

There are other ways, but in my (very limited!) view, the above seems most straight-forward and probably more useful for potential future harvesters.

**Comment by justinlittman** [comment]
I'm not convinced this is a problem.  For example, http://gwsfm-prod2.wrlc.org/ui/collections/98/ completed successfully as a one-time search.

**Comment by Tanych** [comment]
@justinlittman a one-time harvester is not the situation. The above scenario is a short twitter-search task running 5-10 minutes.

**Comment by Tanych** [comment]
@justinlittman 
I have re-test some short terms to verify whether it works. After running three or four days, the collection can complete as expected. In this case, we need to provide doc to describe this situation. When users try to build a `one-time harvester` or `5-10 minutes` twitter search collection for large amount of tweets, such as `trump` or other hot topics. We need notice the user, it would cost a long time to complete the collection. It doesn't support the `5-10 minutes` collects sample. It needs to wait the API ends the collections.

**Comment by justinlittman** [comment]
We provide a warning in the [search docs](http://sfm.readthedocs.io/en/latest/collections.html#twitter-search). And a search that is scheduled too often will result in harvests being skipped. The emails to users warns them about scheduling harvests too frequently.

I'd suggest that existing functionality and documentation covers this case adequately.

(In addition, I'm glad that you've tested it a bit more thoroughly.)
