### ISSUE TITLE
Change Timezone from GMT to EST in RabbitMQ

### ISSUE THREAD

**Issue by rajatvij** [gwu-libraries/sfm-ui#66]
Currently all messages in RabbitMQ are timestamped in GMT timezone which is different from our timezone. So to have a better clarity i suggest to use EST(GMT - 5hr) timezone or to include timezone along with time.

For eg, 2015-11-25T17:08:39.951739 EST instead of 2015-11-25T17:08:39.951739

**Comment by kerchner** [comment]
Don't use EST specifically.  Get the timezone from the server.

**Comment by justinlittman** [comment]
See https://github.com/docker/docker/issues/12084 and http://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

**Comment by rajatvij** [comment]
@justinlittman and @kerchner For this we have two ways to achieve this. 

1. We can either make changes in each Dockerfile like [this](http://tedwise.com/2015/05/02/setting-the-timezone-in-a-docker-image) 

2. Or at docker-compose level like [this](https://github.com/docker/compose/issues/1377) by mounting our localtime and timezone as volumes to the images. 

Personally i prefer the 2nd way as that takes care of the setting up timezone automatically and we don't need to specify timezone there and in first case we are only able to update local timezone, but not the universal timezone. And we would need to updated Dockerfile of each image which i am not even sure we are having. 

So please let me know which approach to follow and i will push the changes accordingly.

**Comment by justinlittman** [comment]
I've also seen reference to setting the TZ env variable in the docker-compose (e.g, `TZ=America/Los_Angeles`).  Can you give this a try?

For 2, will the location of the volumes on a user's machine vary?  Our is it the same on all machines/OSes?

**Comment by rajatvij** [comment]
For 2 we just need to mount these volumes to each docker container: 

volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

And for 1st it works even without setting a TZ env variable in Docker file. We just need to add following lines in Dockerfile, but this would only change the timezone of that single container and here we need to specify the timezone:

# Set the timezone.
RUN sudo echo "America/New_York" > /etc/timezone
RUN sudo dpkg-reconfigure -f noninteractive tzdata

**Comment by justinlittman** [comment]
Can you try just setting a TZ environment variable in the docker-compose and see if it works?  (See, for example, the discussion in https://github.com/sameersbn/docker-gitlab/issues/113).

I'm very reluctant about making assumptions about the machine that docker is running on.  So what if someone is using windows?  Or we run integration tests in docker containers in travis-ci -- I can imagine that for security purposes they prevent links to local files.

**Comment by kerchner** [comment]
Check django timezone handling (relies on pytz etc.), locale-aware date-times, and recommended approach.

**Comment by dchud** [comment]
Fyi: https://docs.djangoproject.com/en/1.8/topics/i18n/timezones/

**Comment by justinlittman** [comment]
After review, I think our django tz settings are correct.

**Comment by justinlittman** [comment]
@rajatvij -- where exactly are you trying to get the tz correct?  The timestamp in which messages?

**Comment by kerchner** [comment]
Not critical for 0.4.  Pushing to discuss after Rajat is back.

**Comment by rajatvij** [comment]
@justinlittman when we simply do docker-compose logs we get the timestamps in EST Timezone.

For eg., 
sfmdevrabbit_1 | =INFO REPORT==== 28-Jan-2016::17:07:09 ===
sfmdevapp_1    | [Thu Jan 28 17:07:10.308037 2016] [mpm_event:notice]

All such timestamps are in EST Timezone, we can change it including following in docker-compose for each comtainer.

volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro

**Comment by justinlittman** [comment]
On Ubuntu, this approach seems to work for some logs:
```
sfmdevapp_1    | [Fri Jan 29 11:22:26.782034 2016] [mpm_event:notice] [pid 208:tid 139811049641856] AH00489: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
sfmdevapp_1    | [Fri Jan 29 11:22:26.782735 2016] [core:notice] [pid 208:tid 139811049641856] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'
```
but not other logs:
```
sfmdevapp_1    | INFO 2016-01-29 16:22:25,972 60 ui.sched Starting scheduler
sfmdevapp_1    | INFO 2016-01-29 16:22:25,973 60 apscheduler.scheduler Scheduler started
```

On OS X (using Docker Toolbox) it doesn't seem to work for any.

**Comment by rajatvij** [comment]
@justinlittman We can deal with this problem in 3 different ways:

1) We can change the timezone for each individual container by adding following lines to container's Dockerfiles:

_App dockerfile:_
```
# Relocate the timezone file
RUN mkdir -p /config/etc && mv /etc/timezone /config/etc/ && ln -s /config/etc/timezone /etc/

# Set the time zone
RUN echo "America/New_York" > /config/etc/timezone
```
_App entrypoint script:_
```
# Set timezone as specified in /config/etc/timezone
dpkg-reconfigure -f noninteractive tzdata
```

This is by far the most complete solution. It's just that i am hesitating to tinker with all container's Dockerfiles.

2) We can show localtime timezone instead of container's timezone as mentioned in my above comment by including following lines for each container in our docker-compose file: 

_docker-compose.yml_
```
volumes:
- /etc/localtime:/etc/localtime:ro
- /etc/timezone:/etc/timezone:ro
```
This might need some more work as we would need to deal with the app container's error logs time as container timezone remains unchanged with this. And we would also need to work to sync time for Docker Toolbox for OS X using boot2docker. 

3) We can use approach 2 for all container's where it doesn't matter for us to change container's timezone(all container's except sfm-ui, harvesters and db(maybe)) and then use approach 1 for sfm-ui, harvesters and maybe db containers

This approach is cleaner but i would need to check on how to implement this in OS X too. 

Let me know which approach to take on this and i will work on it.

**Comment by justinlittman** [comment]
See http://www.ivankrizsan.se/2015/10/31/time-in-docker-containers/

**Comment by justinlittman** [comment]
@rajatvij - You can go ahead and make same change in other repos.

**Comment by justinlittman** [comment]
(Most importantly sfm-docker.)
