### ISSUE TITLE
Long track filter busts tables

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#661]
Keep tables from breaking when there's a long string for the twitter filter seed field. 

![screen shot 2017-01-31 at 4 47 20 pm](https://cloud.githubusercontent.com/assets/1619369/22486353/2e495dba-e7d7-11e6-8109-f80a9738070a.png)

**Comment by lwrubel** [comment]
See also collections for corporate hashtags created by grad student.

**Comment by lwrubel** [comment]
Also apply changes to the Change Log (diff-snippet) so that it also wraps and does not go off the side of the screen.

**Comment by rithvikmundra** [comment]
@lwrubel When I clicked on view all changes at the end of the change log.... it redirected me a new HTML page which has all the change logs and it looked like this 

![screenshot from 2017-04-24 18 03 31](https://cloud.githubusercontent.com/assets/17887041/25360769/9213748e-2918-11e7-9b6c-b29efdd11457.png)

I think it would be nice if I also fix this issue in the change logs page of SFM and hence I am going ahead and fixing this page too as part of this ticket.
