### ISSUE TITLE
Harvest messages for twitter user timeline show None instead of Token 

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#663]
Harvests are sometimes showing None instead of token. It's not all seeds and not all the time. See the AnacostiaNPS seed as noted in harvest 375, and which is described as "None (User ID: 755493428453117953)" in harvest 438 on the EOT instance. EOT is on SFM 1.4.2, not sure if this is solved by 1.4.3.

![screen shot 2017-02-01 at 2 15 52 pm](https://cloud.githubusercontent.com/assets/1619369/22522278/012e43e2-e889-11e6-9160-505e91ba172c.png)

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-twitter-harvester/commit/6f74815d651f06575d54ad23bd36b60eab5e046a
