### ISSUE TITLE
Connected credential conflict

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#664]
Related to #573 

Steps to reproduce:
1. As testuser, connect your Twitter credentials.
2. As testuser2, connect your Twitter credentials.

Expected result:
Testuser2 is notified that credentials are a duplicate.

Actual result:
![screen shot 2017-02-02 at 2 50 30 pm](https://cloud.githubusercontent.com/assets/588335/22565692/fb5dad6c-e956-11e6-8b99-f447b0820320.png)

**Comment by Tanych** [comment]
duplicate with https://github.com/gwu-libraries/sfm-ui/issues/807
