### ISSUE TITLE
Sign up and Log in page input fields

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#668]
Shorten input fields so they don’t span the screen.

**Comment by lwrubel** [comment]
Research bootstrap and django-crispy-forms to get better control over forms layout.

**Comment by adityadharne** [comment]
PR: https://github.com/gwu-libraries/sfm-ui/pull/695

**Comment by Tanych** [comment]
sorry for making comments on the wrong place yesterday. Moving comments here
@lwrubel @adityadharne 
hey, I think we can do a little more with the sign in page, here I suppose it to be with pure bootstrap html.
It's just some suggestion based on  my experience.
* normal
![new look](https://cloud.githubusercontent.com/assets/3956411/22708726/598c6e72-ed45-11e6-906e-7577e2b5ce4f.png)
* empty field
![new_look_empty](https://cloud.githubusercontent.com/assets/3956411/22708765/80e98342-ed45-11e6-81fd-3a02ed7192ff.png)
* with login error(has a fade in close on the right)
![new_look_with_error](https://cloud.githubusercontent.com/assets/3956411/22708731/5dba6eb8-ed45-11e6-90b0-cefd777e86a8.png)

**Comment by Tanych** [comment]
@lwrubel  for the sign-up page, we might miss one thing. We need to provide a checkbox:
* [X] I agree 

By clicking signup, you agree to the `Terms and Conditions`.

Something like above. We need to provide the terms and conditions to disclaims any obligation in case of law cases, even though we have some on the login page.

**Comment by Tanych** [comment]
@lwrubel 
The new sign up page I personal design
* empty
![signup-1](https://cloud.githubusercontent.com/assets/3956411/22996721/bbda066c-f39d-11e6-9130-c8b21e25e3b0.png)

* error message
![signup-2](https://cloud.githubusercontent.com/assets/3956411/22996722/bbf605ba-f39d-11e6-9e77-451fc1b9b3c3.png)

**Comment by lwrubel** [comment]
Thanks for the nice mockups, @Tanych. @adityadharne I think you may have some of this in the works, from what I've seen. Would you apply the two-button approach in the image to the login page? Stick with default bootstrap colors. 

Also make according views changes so that it's the home page. This saves the user another click and makes more sense for now. 

For text to appear on the right: 

**Build Social Media Collections**
Social Feed Manager empowers researchers, faculty, students, and archivists to define and create collections of data from Twitter, Tumblr, Flickr, and Sina Weibo.
Learn more

The button for Learn more should go to the project page for now: http://go.gwu.edu/sfm.

**Comment by lwrubel** [comment]
As discussed, move sign up button to the right section, make "Learn more" a text link. Remove the "home" page.

**Comment by kerchner** [comment]
Fixed in #695
