### ISSUE TITLE
sketch export manifest

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#67]
Refs #47, plan for detail about (a) what was captured, (b) specifics of seeds, (c) log of changes.

**Comment by dchud** [comment]
Work in progress: https://docs.google.com/a/email.gwu.edu/document/d/1EAs0r7fbTPh1fJV_UU6gKYvUJESaXvpu3FE7XSAC8dU/edit?usp=sharing

**Comment by kerchner** [comment]
Draft has been completed as per above, as a basis for ongoing refinement.   Development will start with #123.
