### ISSUE TITLE
Create credential (Add credential) UX

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#671]
* Put a note at top: * Indicates required field
* Make input fields not span the whole screen.
* In the space to the right, put text “Learn more about adding Twitter credentials and then obtain your own Twitter credentials from Twitter.” where Learn more is a link to SFM documentation and obtain your own is a link to the Twitter site (https://apps.twitter.com/). 
* Include key steps from the documentation so users can refer to that (rather than another tab with the documentation) as they go through Twitter’s steps.

**Comment by adityadharne** [comment]
@lwrubel Do we add generic instructions on the page, or platform specific?

**Comment by lwrubel** [comment]
See #719 (assigned to @yonahbg to work on today) for the platform-specific language.

**Comment by adityadharne** [comment]
PR https://github.com/gwu-libraries/sfm-ui/pull/731

**Comment by lwrubel** [comment]
Closed with #731.
