### ISSUE TITLE
Collection Sets list UX

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#673]
* Put a definition of a collection set at the top. “Collection sets are … “
* Give use case or examples as context.

**Comment by lwrubel** [comment]
Per discussion with Cory Lebson: 

* Add a definition beneath the Collection Sets list:
"A collection set is a group of collections around a particular topic or theme."
* Shorten the length of fields
* Put "Added:" in front of the date created.

**Comment by adityadharne** [comment]
PR https://github.com/gwu-libraries/sfm-ui/pull/731

**Comment by lwrubel** [comment]
Closed with #731.
