### ISSUE TITLE
Create Collection Set UX

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#674]
* Note required fields: “* Indicates required field”
* Reduce input field length so it doesn’t span the page. 
* Try using the space on the right for short explanations of Collection Set Name, Description, Group. Use bootstrap affordances, not tables. 
* Explanation for “Group” should say that your default group is your username, unless the SFM team has added you to another group.

**Comment by adityadharne** [comment]
PR https://github.com/gwu-libraries/sfm-ui/pull/731

**Comment by lwrubel** [comment]
Closed with #731.
