### ISSUE TITLE
Collection Set detail UX

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#675]
* Edit alert about “New collection set added. You can now add collections.” to include what a collection is, perhaps, “A collection retrieves data from a particular social media platform.”
* Use accordion or similar device to hide some fields (call “Details”) and provide more emphasis on other information. Hide: ID, Created, Group. For now, leave Description, Stats, WARCs visible. 
* Change “WARCs” to “Data collected”
* Remove time from Date Created.
* Add more detail to the list of collection types in the Add Collection dropdown:
  * Twitter user timeline: Collect tweets from specific accounts
  * Twitter search: Collect recent tweets matching a query
  * Twitter filter: Collect tweets in real time matching filter criteria
  * Twitter sample: Collect a subset of all tweets in real time
  * Tumblr blog posts: Collect blog posts from specific blogs
  * Flickr user: Collect posts and photos from specific accounts
  * Weibo timeline: Collect posts from a user and the user’s friends
* Next to the dropdown add a link: “More about collection types” which goes to the documentation.

**Comment by kerchner** [comment]
Suggest removing the word "Collect" from each description to shorten text

**Comment by kerchner** [comment]
Start by expanding text in buttons.  Try two lines per collection type, as per http://semantic-ui.com/elements/list.html

**Comment by Tanych** [comment]
@kerchner @lwrubel @justinlittman @adityadharne 
As we discuss before, I find a reasonable way to solve this problem:
Adding a popover on the right which triggers by hover not click(when mouse moves on the item) for each item. It would show the detail of the function and when loss focus, it will disappear. It would like this:

![collection](https://cloud.githubusercontent.com/assets/3956411/23069164/64f576a8-f4f4-11e6-96fe-cc9704b5df1e.PNG)

To implement this with adding less 10 lines code based on bootstrap.

Refs:
https://v4-alpha.getbootstrap.com/components/popovers/

**Comment by kerchner** [comment]
Looks nice :+1:

**Comment by lwrubel** [comment]
@adityadharne take a look at both approaches and implement whichever display seems to work best.

**Comment by lwrubel** [comment]
Closed with #710.
