### ISSUE TITLE
Create collection: Twitter user timeline UX

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#676]
* Note required fields: “* Indicates required field”
Shorten fields width to provide room for explanation next to item. Or put explanation above the field, next to the label. 
* Only display problem conditions/warnings. Do not show blue “credential is not used in any other collections” message since it’s unnecessary information. Confirm that existing warning/danger text includes a suggestion to fix the problem.
* Change “incremental” to “incremental harvest”. Change definition to “Only collect new items since the last data retrieval”.
* Group next three items about media and web resources with bold text/header: “In addition to tweets, collect:”
  * Change Media to:  “Media (e.g., images, videos) that are embedded in tweets.” Remove explanation. 
  * Change “User profile images” to “User profile images and user banner images.” Remove explanation.
  * Change “Web resources” to “Web pages referenced in tweets.” Remove explanation. 
* Add explanation next to schedule: “How often frequently you want data to be retrieved.”

**Comment by lwrubel** [comment]
Consider question mark graphic and tooltip option if screen has too many words.

**Comment by adityadharne** [comment]
PR https://github.com/gwu-libraries/sfm-ui/pull/731

**Comment by lwrubel** [comment]
Closed with #731.
