### ISSUE TITLE
Reconsider name “Change log"

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#678]
“Change log” sounds overly technical. Consider “History of changes.” Use "Additional notes (optional) on pages where "Change note" currently appears. Check in with @save4use, @reliztrent, Vakil Smallen.

**Comment by lwrubel** [comment]
Once wording confirmed, change globally. @lwrubel will check in with team and reassign for implementation.

**Comment by justinlittman** [comment]
OK as is for now.
