### ISSUE TITLE
Seeds list on collection detail page 

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#679]
Tighten up horizontally: move Link column to the first column. 

Change For Twitter user timeline, Tumblr, and Flickr, coordinate with work in #677
* Include number of seeds in seeds panel header as in harvests panel, e.g. (1-10 of 98)
* When there are more than 10 seeds, hide the rest. Offer an option to display the whole list on the page, considering bootstrap affordances. 
* Consider bootstrap table condensed, striped rows to make table easier to view.

**Comment by yonahbg** [comment]
This was helpful for getting to the bottom of the list. 
However, only 10 seeds are revealed at a time, with no option to expand them all. This means that it's harder to search for seeds using find in page, which I've used several times.

**Comment by adityadharne** [comment]
@yonahbg it will be fixed in https://github.com/gwu-libraries/sfm-ui/issues/749
