### ISSUE TITLE
Collection detail page: Define “Seeds” in context of collection type

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#685]
Provide a collection-type specific definition of seed in the panel heading. 
* Seeds (Twitter accounts)
* Seeds (Filter criteria)
* Seeds (Search query)
* Seeds (Tumblr blogs)
* Seeds (Flickr users)
* Seeds (Weibo users)

Place a question mark bubble graphic (check font awesome) next to Token and UID and provide a pop-up/modal explanation of each of those, with an example.

Instead of “Token” and UID, use label appropriate for the type of collection (e.g. username, user ID, blog name).

Hide the Token column in the case of Tumblr, since it's always empty.

**Comment by lwrubel** [comment]
Place a question mark bubble graphic (check font awesome) next to Token and UID and provide a pop-up/modal explanation of each of those, with an example. 

Instead of “Token” and UID, use label appropriate for the type of collection (e.g. username, user ID, blog name).

**Comment by lwrubel** [comment]
Hide the Token column in the case of Tumblr, since it's always empty.

**Comment by adityadharne** [comment]
PR: https://github.com/gwu-libraries/sfm-ui/pull/766
