### ISSUE TITLE
Use diagram to help with Twitter collection screens

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#688]
Create a graphic showing the elements of a tweet that affect collection set-up. Point out user image, user banner image, media, web page. Place diagram on twitter collection create pages.

**Comment by Tanych** [comment]
@lwrubel @adityadharne 
hey, I think we can do a little more with the sign in page, here I suppose it to be with pure bootstrap html.
It's just some suggestion based on  my experience.
* normal
![new look](https://cloud.githubusercontent.com/assets/3956411/22708726/598c6e72-ed45-11e6-906e-7577e2b5ce4f.png)
* empty field
![new_look_empty](https://cloud.githubusercontent.com/assets/3956411/22708765/80e98342-ed45-11e6-81fd-3a02ed7192ff.png)
* with login error(has a fade in close on the right)
![new_look_with_error](https://cloud.githubusercontent.com/assets/3956411/22708731/5dba6eb8-ed45-11e6-90b0-cefd777e86a8.png)

**Comment by adityadharne** [comment]
@Tanych That is pretty cool, so you suggest creating a new home page?

**Comment by Tanych** [comment]
no need to create a page, it's just some edits based on your submission.
