### ISSUE TITLE
Group selection for Collection Sets

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#690]
If a person only has one group, just print the group name. Only show group selection dropdown if person has multiple groups.

**Comment by rithvikmundra** [comment]
@lwrubel I couldnt make much progress on this ticket. I figured out that the code which needs to changed is in forms.py file as the collection_set_create.html is using crisply forms.

**Comment by lwrubel** [comment]
See credentials as an example.

**Comment by justinlittman** [comment]
OK as is for now.
