### ISSUE TITLE
Turn on/off, edit, export buttons on collection detail 

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#691]
The workflow for turning a collection on and off, and why/when things are disabled could be improved. 

* Remove the “Collection is active. Turn off to edit.” line from the gray box. 
* Move buttons from right side of page to below the gray collection name box, so that they’re in the main flow of user reading the page. Leave stacked initially, and put warnings next to them. 
  * Put a yellow caution flag and message next to a Turn on button: “This collection is disabled”. 
  * Message next to a disabled Edit button: "Turn off to edit".
  * Make the disabled blue button color a gray. 

Remove disabled buttons in Seeds panel when collection is on. Replace with a text “Turn off collection to add seeds.” where “turn off” is a link that does the same thing as the Turn off button.

**Comment by kerchner** [comment]
#752 is the predecessor for this

**Comment by justinlittman** [comment]
As things stand, #752 captures the core of what needs to be fixed, so closing this ticket.
