### ISSUE TITLE
Export gobbledygook

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#704]
As reported by Phil Waller (SMPA grad student):

Some lines in export end with gobbledygook:
```
RT @PostSports: One team's trash is another team's treasure: Raiders benefiting from Redskins' scraps and Jack Del Rio is loving it https:/â€¦
```

See attached export.
[SFM-fulltextartifact-Kim-Gross-philwaller.xlsx](https://github.com/gwu-libraries/sfm-ui/files/781228/SFM-fulltextartifact-Kim-Gross-philwaller.xlsx)

**Comment by Tanych** [comment]
@justinlittman  what the version does he use?
I can't reproduce this Unicode problem, I think we already solved this issue before.

**Comment by justinlittman** [comment]
I'm fairly sure it is from one of the Washington Post collections from
prod.  Please reach out to him to try to replicate.

**Comment by Tanych** [comment]
@justinlittman 
I am not sure whether it's a bug. When people export the records to CSV files and open the CSV file using MS Excel on Mac. In some cases, Excel can't decode the characters very well when importing as UTF-8.  It works fine for the xlsx format.

**Comment by Tanych** [comment]
The CSV file works for Ubuntu and Windows but Mac. It's generally painful experience with the MS excel on Mac.
https://rothmanshore.com/2013/10/29/solved-editing-a-csv-with-utf-8-encoding-on-a-mac/

**Comment by justinlittman** [comment]
@Tanych:  So to confirm -- Excel format export is OK, but CSV is problematic due to problems with Excel.

**Comment by Tanych** [comment]
@justinlittman Phillis told me that he transferred the xlsx file based on the CSV file exported. The xlsx which exports from sfm-ui works well for all the platforms.

**Comment by kerchner** [comment]
@justinlittman to add note in documentation

**Comment by justinlittman** [comment]
Added to troubleshooting docs: https://github.com/gwu-libraries/sfm-ui/commit/e6ef5d1cf4e4071940cb3d137adca209ee1f9e93
