### ISSUE TITLE
Notify user of dupe seeds

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#706]
There are cases in which updates from harvests can result in duplicate seeds for a collection (meaning that more than one seed has the same token or uid).

The user should be notified on the collection details page when there are duplicate seeds.  The warning should to at the seed level, not the overall collection level (to make figuring out which seeds to fix easier).

Related to #640 and ticket for putting harvest warnings inline with seeds.

**Comment by kerchner** [comment]
Fixed in #713.
