### ISSUE TITLE
Documentation on publishing dataset to Dataverse

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#708]
Provide detailed instructions on the steps for publishing a dataset to Dataverse.  The Women's March collection can be used as an example.

**Comment by lwrubel** [comment]
Also a short blog post on the context and use for the new documentation.

**Comment by justinlittman** [comment]
Here's the PR for the blog post: https://github.com/gwu-libraries/sfm-ui/pull/750
