### ISSUE TITLE
sfm-elk container "Too many open files" exception

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#709]
The ELK container for the POE collection eventually encountered this:

``` java.nio.file.FileSystemException: /sfm-data/elk/poe-elk/data/elasticsearch/nodes/0/indices/logstash-2016.06.14/2/index: Too many open files```

and a restart did not resolve it.  Based on https://github.com/spujadas/elk-docker/issues/56 , I implemented the *_VERY TEMPORARY_* solution of shelling inside the sfm-elk container, editing 
`/etc/init.d/elastisearch` and change the line that sets MAX_OPEN_FILES from 65536 to 131072.  Restarted elasticsearch with `sudo service elasticsearch restart`.

The container currently has about 900K tweets indexed in elasticsearch.   The elasticsearch heap size is now configured to 10240m (~10GB) in the container's docker-compose definition.

The task for this ticket is as follows:  Once the ELK container seems to remain stable for 1-2 weeks of usage (new tweets being indexed, user utilization of Kibana), update the docker files for sfm-elk so that new sfm-elk containers will contain the increased limit for MAX_OPEN_FILES.

**Comment by justinlittman** [comment]
Fixed.
