### ISSUE TITLE
seed duplicate problem in other collection type

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#714]
The seed duplicate and validation problem should do for the following collection type:
* Flickr user : checking the scree name and NSID, if possible, specify the NSID rules.
* Tumblr post: screen name should not  be number and empty.
* Twitter filter: track, follow, location as one seed.
* Twitter search: keyword should not be empty.

if possible, for 
* weibo search

**Comment by justinlittman** [comment]
Reconsider this ticket after suggestions from review of #640 are implemented.  I suspect most of this additional validation will prove unnecessary.

**Comment by Tanych** [comment]
@justinlittman  this tickets is not necessary, I will update an all in one check duplicate seed in #640.
closed!
