### ISSUE TITLE
Daily email info for harvests that are less frequent than daily

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#716]
Daily emails for harvests that are weekly (or less frequent than daily) show 0 for harvests "Yesterday" and "Previous day". This makes it look like there were no tweets collected or perhaps there was a problem, when in fact no harvest was scheduled for that day.  

```
Item	 Yesterday	Previous day	Last 7 days	
tweets	0	0	933	1,609	
```

Change 0 to N/A (or something similar) when there was no harvest scheduled that day.

**Comment by lwrubel** [comment]
Discuss with @justinlittman before working on this. Related improvement to include: changing how collections that are turned off appear in the email.

**Comment by justinlittman** [comment]
Also possibly showing when last update is.

**Comment by lwrubel** [comment]
For now, simply change 0 to N/A as noted initially.

**Comment by justinlittman** [comment]
Also, skip collections that are dormant (turned off and no harvests in last 60 days).

Also, show simple and complete dates for last and next harvests, e.g., "5 days ago (April 28, 2017).

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-ui/pull/799

I didn't implement dormant collections.
