### ISSUE TITLE
Login / home page tweaks

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#717]
Above the login section, add text conveying the purpose of SFM, per recommendation by Cory Lebson. Consider eye flow downward to login section.  

Update the text on the right to fix the missing space and add other information about SFM.

**Comment by lwrubel** [comment]
@lwrubel will write text and reassign to @adityadharne to implement. Also remove the log in and sign up links in the header.

**Comment by lwrubel** [comment]
Top text: 
Social Feed Manager empowers researchers and archivists to build collections of social media data from multiple platforms. 

Text on right:
Social Feed Manager can collect from Twitter, Tumblr, Flickr, and Sina Weibo. [Read more about Social Feed Manager](http://sfm.readthedocs.io/en/latest/quickstart.html). Link may need to be tweaked later depending on the work in #693.

**Comment by adityadharne** [comment]
PR https://github.com/gwu-libraries/sfm-ui/pull/731

**Comment by lwrubel** [comment]
Closed with #731.
