### ISSUE TITLE
Add credential needs pointer to docs and platform

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#719]
Come up with language for pointing user to docs' step-by-step and out to the platform for more info. See how long this is and whether it will be best implemented below the page header or on the right side of the screen.

**Comment by yonahbg** [comment]
If this format works, I think it would work best on the side, but I'd have to see it to confirm.

**Twitter**

Twitter credentials can be obtained from the [Twitter API](https://apps.twitter.com/).

- Sign in to Twitter 
- Create a new app on the credentials page
- Find the key and secret from the _Keys and Access Tokens_ tab

It is recommended to change the application permissions to read-only.
For detailed instructions, see [Adding Twitter Credentials](https://sfm.readthedocs.io/en/latest/credentials.html#id1).

**Flickr**

Flickr credentials can be obtained from the [Flickr API](https://www.flickr.com/services/api/keys/).

- Sign in to your Yahoo! account
- Get a non-commercial key
- Enter the key and secret in the correct boxes

For detailed instructions, see [Adding Flickr Credentials](https://sfm.readthedocs.io/en/latest/credentials.html#adding-flickr-credentials).

**Tumblr**

Tumblr credentials can be obtained from the [Tumblr API](https://www.tumblr.com/oauth/apps/).

- Sign in to Tumblr
- Register an application
- Enter the OAuth Consumer Key in the API key field

For detailed instructions, see [Adding Tumblr Credentials](https://sfm.readthedocs.io/en/latest/credentials.html#adding-tumblr-credentials)

**Comment by adityadharne** [comment]
@yonahbg are the steps for Weibo intentionally absent?

**Comment by yonahbg** [comment]
Only partially. I don't actually know how to get Weibo credentials, so I
have to figure out how to phrase that one.

**Comment by yonahbg** [comment]
**Weibo**

Weibo credentials can be obtained from the Weibo API.

Since the Weibo API is not available in English, see [this guide](https://gwu-libraries.github.io/sfm-ui/posts/2016-04-26-weibo-api-guide) for help.

**Comment by lwrubel** [comment]
Closed with #731.
