### ISSUE TITLE
Collection set detail, round 2

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#722]
Refinements to #675 based on follow-up conversation with Cory. 

* The "i" button should be a pop-up or modal, not link out to another page. Text of pop-up: 
"Collections connect to a social media platform’s APIs, or methods for retrieving data. Understanding what each collection type provides is important to ensure you collect what you need and are aware of any limitations. [More info.](http://sfm.readthedocs.io/en/latest/collections.html)." 
* Re-order collection type options to put Twitter first, and user timeline specifically. 
* Change drop down to two-line descriptions, rather than side hover pop-up, if possible. 
* Change the description of Twitter sample to be less similar to Twitter filter. Try: "A sample of all tweets available. Collects significant amounts of data."

**Comment by adityadharne** [comment]
PR https://github.com/gwu-libraries/sfm-ui/pull/731

**Comment by lwrubel** [comment]
Closed with #731.
