### ISSUE TITLE
Add recommended twitter screen name to ID converters to docs

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#730]
In the course of assisting a researcher with setting up a Twitter filter that included "follow" parameters, we realized that the user needs a way to look up a screen name's equivalent ID.  The Twitter UI doesn't provide a way to do this (though the API does).  One workaround is to create a Twitter User Timeline collection just for the purpose of looking up IDs.  However, there are web sites available to do this lookup, as discovered by @soominpark .  Consider adding a few recommended sites to the documentation for Twitter Filters (and maybe UX too).

**Comment by soominpark** [comment]
@lwrubel Could you review it in master

**Comment by Tanych** [comment]
fixed by f8892bed0207e777dc49229bd8be0e4bd724f5dc . It's less than two lines work. Just directly commit to the master branch.

**Comment by kerchner** [comment]
@lwrubel to review and close this issue when resolved (no PR)

**Comment by justinlittman** [comment]
Reviewed and edited: https://github.com/gwu-libraries/sfm-ui/commit/e784fa003547f34c2cfd98eeb940551cefe45e2f
