### ISSUE TITLE
Weibo API instructions - add advanced API content

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#736]
Ref PR #634  - this ticket is for only the doc on the project site (not the readthedocs site)

**Comment by Tanych** [comment]
@kerchner  the way to update expired access token has been posted, you can review the final draft on the same instance which host on my dev VM.

**Comment by lwrubel** [comment]
@kerchner have you been able to review this documentation?

**Comment by kerchner** [comment]
Closed in #634
