### ISSUE TITLE
Show all seeds when clicking "see all"

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#749]
"See all n seeds" link at bottom of seeds list on collection detail page should cause accordion to show all seeds. Currently it is only showing the next 10 seeds and shows ten more with each click.

**Comment by yonahbg** [comment]
@adityadharne Thanks, I didn't see this

**Comment by adityadharne** [comment]
PR: https://github.com/gwu-libraries/sfm-ui/pull/766
