### ISSUE TITLE
Weibo Search with multiple terms

### ISSUE THREAD

**Issue by Tanych** [gwu-libraries/sfm-ui#761]
Currently, the Weibo search collection only supports for one active seed. If someone has couples of seeds to collecting, they might need to build several collections for that.  The Weibo search API doesn't support the `OR` `AND` logical combine strings. It can only match one term at per request.
### Trade-off
* Remove the sfm-ui seed limitation for Weibo search, allows it can active several seeds at the same time. However, it will make the credential to reach the rate limit at a very short time.
* Building collection for each seeds, it will hard to manage when has more than 20 seeds.

**Comment by kerchner** [comment]
Suggest configure Weibo Search collection to allow 1+ seeds.  Weibo harvester would iterate through and make an API call for each seed.

**Comment by Tanych** [comment]
@kerchner @justinlittman 
Why not doing with search collection with 1+ seeds. When we doing the Warc iteration we can't know Weibo belongs to which topic. It's no fields to mark the topics. It's hard to do the count Stats.

**Comment by Tanych** [comment]
closed with implements functionality!
