### ISSUE TITLE
Export segmentation doesn't work for full JSON

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#763]
Steps to reproduce:
Export a dataset as full JSON that contains more records than the selected export segment.

Expected result:
Export will be segmented into multiple files.

Actual result:
One giant file.

**Comment by Tanych** [comment]
@justinlittman  how many records do you have, 
I can't reproduce it in a small amount records.

**Comment by justinlittman** [comment]
Here's the problematic export: http://gwsfm-prod2.wrlc.org/ui/exports/202/

**Comment by justinlittman** [comment]
I can't replicate in dev environment.
