### ISSUE TITLE
"Adding your user to the docker group" link is obsolete in Docker installation document 

### ISSUE THREAD

**Issue by rithvikmundra** [gwu-libraries/sfm-ui#765]
The link under the Ubuntu section of installing docker which elaborates on adding the user to the docker group is broken. Please provide with an updated link which explains the same.

**Comment by kerchner** [comment]
@rithvikmundra please add a link with the URL of the page containing the broken link

**Comment by rithvikmundra** [comment]
@kerchner Sure.
Here it is 
http://sfm.readthedocs.io/en/latest/docker.html#docker-installing
