### ISSUE TITLE
Docker instructions potential improvements

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#770]
@rithvikmundra ran into the issue we've encountered a few times whereby setting up docker tools seems to require creating a `docker` group, and adding the user(s) wanting to run docker-compose, etc. to that group.  Even though we aren't in the business of maintaining docker's instructions, it might be worth bringing this point out.

Another common issue seems to be that the `pip install` of docker tools seems to be less likely to succeed than the curl etc. install method.

**Comment by justinlittman** [comment]
@kerchner I believe both of these are already addressed in http://sfm.readthedocs.io/en/latest/docker.html#installing-docker. Let me know what you think.

**Comment by kerchner** [comment]
Concur.  Closing issue.
