### ISSUE TITLE
Clarify seed counts

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#773]
1. Where ever seed counts appear, it should be clarified if active, deleted or total.
2. If only displaying 1 number, I'd suggest that active makes the most sense.
3. On seed list, would be helpful to have breakdown of active/deleted.

<img width="506" alt="2017-04-06_0740" src="https://cloud.githubusercontent.com/assets/588335/24752608/ac4876f4-1a9c-11e7-8703-92dc6890ddc9.png">

**Comment by lwrubel** [comment]
Remove number of seeds from the panel heading. Put the appropriate number next to the words Active and Deleted. Check Bootstrap affordances (badges) for putting numbers on tabs
 
On collection set page, update column header to say "active seeds". Remove wording "seeds" in the  entries in the table.
