### ISSUE TITLE
Add "See all active seeds" button to the top of the collection

### ISSUE THREAD

**Issue by yonahbg** [gwu-libraries/sfm-ui#776]
For both the active and deleted lists of seeds in collections, add a button to show or hide seeds to the top of the collection in addition to having it at the bottom of the collection.

For example, if you show all in a long list just to get to a seed near the top, and then you want to add a new seed, you have to scroll all the way to the bottom to collapse the list, at which point you're already at the bottom. Adding a button at the top would help alleviate this problem.

**Comment by justinlittman** [comment]
Fixed by current paging approach for seeds.
