### ISSUE TITLE
Error when adding twitter filter seeds 

### ISSUE THREAD

**Issue by soominpark** [gwu-libraries/sfm-ui#781]
When I try to add a large amount of seeds into the Track box of a Twitter Filter collection, more than about 600, and click save button, a server error occurs as the picture below.

![image](https://cloud.githubusercontent.com/assets/21350419/25058319/104ba02c-2146-11e7-809a-3641d647a262.png)

![image](https://cloud.githubusercontent.com/assets/21350419/25058342/62ce7a2c-2146-11e7-988d-ef5cdf75584b.png)

Please note that Twitter filter API has its own limit to the number of seeds, around 400 keywords  according to Laura's search from the [Twitter Developers Forum](https://twittercommunity.com/t/streaming-api-filter-maximum-follow-name-and-how-much-data/7835) ("we can track up to 5,000 users and 400 keywords"), but I found that on the SFM UI I could add up to 600 keywords into the track box without any problem, although I got an error as below immediately after running the collection with 600 keywords. This should be considered when fixing the error, and I think a warning message preventing users from inputting more than 400 keywords should be added.
![image](https://cloud.githubusercontent.com/assets/21350419/25058840/e73f829c-214b-11e7-8ad0-2f1b5352e005.png)

**Comment by lwrubel** [comment]
Try to enforce limit on input area rather that after submission.
