### ISSUE TITLE
Additional scheduler work

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#79]
Follow-up work to #44 

* Persist schedules
* Make sure that scheduler starts up on app start
* Unique id in messages
* Correct path in messages
* Switch to Kombu for messages
* Set useful names on jobs
* Verify correct add/modify/delete of jobs

**Comment by dchud** [comment]
This looks like several tickets' worth of work.

**Comment by justinlittman** [comment]
I don't disagree.  We can amass the work that needs to be done in this ticket and decide later how to split into bit-size (fun-size?) tickets.

**Comment by kerchner** [comment]
Reconsider setting wsgi daemon processes back to 2, but find another solution for the fact that a value of 2 instantiates 2 processes for apscheduler.   add_job sometimes calls one, sometimes calls the other.

**Comment by justinlittman** [comment]
After testing and googling (e.g., https://groups.google.com/forum/#!topic/apscheduler/eBws2pvaLO8), I've concluded that multiple instances of APScheduler cannot be run concurrently and work in a coordinated fashion (e.g., only executing a job once).  In our case, multiple instances would run in separate processes if wsgi daemon processes are set with a value greater than 1.

The options are:
1. Leave wsgi daemon processes at 1, forcing APScheduler to only be run in one process.
2. Create some sort of a (singleton) scheduler service using APScheduler.
3. Use a different scheduler.

My recommendation is 1, as it is the simplest possible solution.  If scaling proves a problem and we need to use additional wsgi processes then we can consider one of the other options.

**Comment by kerchner** [comment]
Resolved in #104
