### ISSUE TITLE
Consider requirements.txt

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#80]
For consideration:
1. Creating separate development and production/release requirements.txt.  This will be useful for using dependencies that we do development on (e.g., warcprox and sfm-utils), but need to be pinned for releases.  See http://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments.
2.  Freeze all requirements in requirements.txt.  This will give us the most stable, reliable environment.  Something like http://www.pypi-notifier.org/ can be used to provide notification of updated dependencies.

**Comment by justinlittman** [comment]
For everyone to review, not just a single tester.

**Comment by justinlittman** [comment]
Following guidance from 5.5 and 21.7.2 of Two Scoops.

**Comment by justinlittman** [comment]
Waiting until PR backlog clears up to avoid creating a mess.

**Comment by kerchner** [comment]
Plan to do this after other 0.4 development has been completed, before release.

**Comment by justinlittman** [comment]
Hmm ... I couldn't get pypi-notifier to correctly authorize with Github Oauth.

https://github.com/sesh/piprot seems like an alternative.

**Comment by justinlittman** [comment]
Or to list outdated packages, and show the latest version available:
```
$ pip list --outdated
```

**Comment by justinlittman** [comment]
Here are the PRs:
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/4
* https://github.com/gwu-libraries/sfm-utils/pull/6

I accidentally committed everything directly to master for sfm-flickr-harvester:  https://github.com/gwu-libraries/sfm-flickr-harvester/commit/1deeb72ab9c9d3e3060c43ce8043a9301226ccc4

and then I made the same stupid mistake with sfm-ui:  https://github.com/gwu-libraries/sfm-ui/commit/e277322e6939116df67f11bd227a224288413083 and https://github.com/gwu-libraries/sfm-ui/commit/e277322e6939116df67f11bd227a224288413083

**Comment by kerchner** [comment]
Closing - the PRs above have now been merged (gwu-libraries/sfm-twitter-harvester#4 and gwu-libraries/sfm-utils#6)
