### ISSUE TITLE
Weibo search collection_detail page has errors

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#805]
@Tanych has identified problems with the UI for Weibo search that prevent it from loading properly.

**Comment by Tanych** [comment]
The Weibo search would like this:
![weibo_search](https://cloud.githubusercontent.com/assets/3956411/25592958/cacfa8c2-2e88-11e7-941b-ba6fcbc12b8e.png)
I will update it with all the stuff related to Weibo and make it fit all the harvester type including all the different names on three columns `link`(some of them might have, some would disappear) `uid` and `token`. It doesn't need to add so much code on HTML templates.
