### ISSUE TITLE
Consider removing prefetching in MessageConsumer

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#810]
Here is the current situation in production:
* Harvester 1: Running a really long harvest and prefetched another harvest request.
* Harvester 2 and 3: Waiting for harvest request.

The prefetched harvested is waiting for the long harvest, when it could be handled by one of the other harvesters.

I think the solution is to remove `consumer.qos(prefetch_count=1, apply_global=True)`.

This area of the consumer has been messed with multiple times, so make sure to consult earlier tickets.

**Comment by justinlittman** [comment]
It turns out there is no way to disable prefetching in Kombu. Setting it to 1 is the best possible.  See http://docs.celeryproject.org/en/latest/userguide/optimizing.html#optimizing-prefetch-limit.

An alternative is to have separate queues for Twitter REST harvests: a fast queue and a slow queue. Harvests would get assigned to queues based on their frequency, e.g., harvests scheduled every 30 minutes would get assigned to the fast queue. Separate pools of Twitter REST harvesters would be assigned to each of the queues.

**Comment by justinlittman** [comment]
PRs for this ticket:
* https://github.com/gwu-libraries/sfm-docker/pull/19
* https://github.com/gwu-libraries/sfm-utils/pull/35
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/39
* https://github.com/gwu-libraries/sfm-ui/pull/823

**Comment by justinlittman** [comment]
For testing:
* Add a twitter priority harvester to docker-compose.yml (see PR for sfm-docker).
* Change docker-compose.yml to build the Twitter REST and Twitter priority REST harvesters.
* Run the PR code for SFM UI.

To test:
1. Create and start a user timeline collection that is harvested every week.
2. Create and start a user timeline collection that is harvested every 30 minutes.
3. Verify that first collection is harvested by a Twitter REST harvester and second collection is harvested by a Twitter priority REST harvester.

**Comment by justinlittman** [comment]
@Tanych Can you test this ticket, please? Assigning PRs to you.

**Comment by Tanych** [comment]
Will do

**Comment by Tanych** [comment]
@justinlittman 
### Settings
PRIORITY_SCHEDULE_MINUTES= 60

### Test case 1
* create a twitter `user timeline 1` with 30 min.
* create a twitter `user timeline 2` with every week.
* run the two collections

### Results
- [x] `Timeline 1` sends message to `harvest.start.twitter.twitter_user_timeline.priority`. and `timeline 2` sends a message to `harvest.start.twitter.twitter_user_timeline`.
- [x] Twitter REST harvester runs the second and Twitter priority REST gets the first.

### Test case 2
* change `user timeline 1` from 30 min to every week.
* change `user timeline 2` from every week to 30 min.
* run the two collections

### Results
- [x] `Timeline 1` sends a harverster message to `harvest.start.twitter.twitter_user_timeline`. and `timeline 2` sends a harverster message to `harvest.start.twitter.twitter_user_timeline.priority`.
- [x] Twitter REST harvester runs the first and Twitter priority REST gets the second.

### Test case 3
* change `user timeline 1` from 30 min to 60 min.
* run the collection

### Results
- [x] `Timeline 1` sends a harvester message to  `harvest.start.twitter.twitter_user_timeline.priority`.
- [x]  Twitter priority REST gets the harvester.

### Test case 4
* change `user timeline 1` from 30 min to 4 hours.
* run the collection

### Results
- [x] `Timeline 1` sends a harvester message to  `harvest.start.twitter.twitter_user_timeline`.
- [x]  Twitter REST gets the harvester.

I have reviewed the codes and based on the different test cases, it's good to go for the PRs.
