### ISSUE TITLE
When bulk loading seeds, remove trailing spaces

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#811]

**Comment by justinlittman** [comment]
Actually 1 or more spaces.

**Comment by justinlittman** [comment]
I tracked it down. It was a space followed by a right-to-left mark (which indicates that text should go right to left). What I think we want to do is (1) remove leading spaces then (2) remove everything after and including the first space.

So " @foo bar" becomes "foo". So does "@foo ".

**Comment by rithvikmundra** [comment]
@justinlittman completed the ticket. Please let me know if the logic used is fine.
