### ISSUE TITLE
Geocode search doesn't work

### ISSUE THREAD

**Issue by yonahbg** [gwu-libraries/sfm-ui#815]
I've never collected anything based on a geocode within a Twitter Search, even when I have known for certain that there were tweets within the bounding radius. 
I tested a search parameter in SFM and got nothing; I tested the same parameter through the Twitter API Console and got back seven tweets.

**Comment by justinlittman** [comment]
@yonahbg Can you add the parameters that you used for your test?

**Comment by yonahbg** [comment]
38.899133,-77.048382,1mi

**Comment by Tanych** [comment]
@yonahbg 
I think it shouldn't consider as a bug, twitter search with query parameter only consider something related to the parameter `q=`. The `Geocode` is an additional parameter for the Twitter search API. If input the `geocode` on the `q` field, you get nothing.  To search tweets by place in `q` field, you can consider using the Twitter place ID, such as: http://twitter.com/search?q=place%3A07d9cd6afd884001
For details, check following:
https://dev.twitter.com/rest/public/search-by-place
https://dev.twitter.com/rest/public/search

**Comment by yonahbg** [comment]
@Tanych 
To make sure I understand what you mean, you think Geocode only works with another search query?

**Comment by Tanych** [comment]
@yonahbg 
The Twitter search API has two different parameters, `q=` and `geocode=`. Usually, API client only implements `q=`. Currently, all the values input on SFM-UI will feed into the `q=` field.

**Comment by yonahbg** [comment]
@Tanych 
Right, that's what I imagined the problem would be. Is there a way to add that in? Maybe by providing a separate field for additional parameters?

**Comment by Tanych** [comment]
@yonahbg 
Sure, It's simple to add!

**Comment by justinlittman** [comment]
Concur that this should be fixed as suggested.

**Comment by justinlittman** [comment]
Here's the correct format for a geocode: `38.899434,-77.036449,50mi`

To do a geocode only with Twarc, provide no q and this for a geocode, e.g., `twarc search --geocode 38.899434,-77.036449,50mi`

**Comment by justinlittman** [comment]
PRs for this ticket:
* https://github.com/gwu-libraries/sfm-ui/pull/844
* https://github.com/gwu-libraries/sfm-twitter-harvester/pull/40

**Comment by justinlittman** [comment]
Steps for testing:
1. Create a search collection that contains a query only.
2. Create a search collection that contains a geocode only.
3. Create a search collection that creates a query and geocode.
4. Run each of these collections once.
5. Export each of these collections.

Expected result:
Each export will contain tweets that satisfy the search criteria.

**Comment by Tanych** [comment]
@justinlittman 
all tests have been tested! It's good to go!
