### ISSUE TITLE
Change log for Twitter filter not displaying seed name

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#818]
@rithvikmundra noticed that since 1.8, the seed for a Twitter filter collection is not displaying properly in the Change log table. This is visible on the seed_detail page and the change log page.

Seed detail: 

![screen shot 2017-05-10 at 4 30 33 pm](https://cloud.githubusercontent.com/assets/1619369/25919944/4348e09a-359e-11e7-80c3-09a642ee36c2.png)

Change log:
![screen shot 2017-05-10 at 4 32 57 pm](https://cloud.githubusercontent.com/assets/1619369/25919980/5ac79f90-359e-11e7-9a54-66bcf933e79b.png)

**Comment by Tanych** [comment]
@lwrubel problem-related PR and issue:
https://github.com/gwu-libraries/sfm-ui/issues/683
https://github.com/gwu-libraries/sfm-ui/pull/788
The logic has a bug when returning a seed label.
