### ISSUE TITLE
Consider dormant collections

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#819]
As predicted by our use cases and born out by practical experience, we now have a significant number of collections that are dormant, i.e., collecting is completed but the collection is to be retained. An example of this is our election collections.

These dormant collections clutter up parts of the UI and harvest stats emails. It would be optimal to be able to treat dormant collection differently.

Possible approaches:
* A dormant flag for a collection or collection set.
* Automatically treating collection/collection sets as dormant based on inactivity.

**Comment by lwrubel** [comment]
Check with @reliztrent @save4use Vakil about terminology to use. Initial approach is to set manual flag at collection level. Collection set with no active collections is automatically dormant.

**Comment by justinlittman** [comment]
@lwrubel This will need a UI review to make sure implemented appropriately.
