### ISSUE TITLE
Add Tweet attributes to index in ElasticStack

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#832]
Having learned from the GW Program on Extremism that these fields are of analytical research value, add them to the Tweet attributes that are indexed in ElasticStack:

- user.followers_count
- user.friends_count
- .source
- Tweet type:  Retweet, Reply, Quote, Original.  This can utilize logic which @justinlittman has developed.  Also recommend considering an appropriate name for this calculated field.

**Comment by Tanych** [comment]
@justinlittman where is the logic for tweet type? Does it implement by `jq` or python? 
I am thinking to get rid of `jq` in elk-loading similar like Weibo PR https://github.com/gwu-libraries/sfm-elk/pull/12. You can take a look at the related PR first!

**Comment by justinlittman** [comment]
You can use this logic: https://github.com/justinlittman/beltway_reporters/blob/master/jupyter/utils.py#L57

**Comment by Tanych** [comment]
@justinlittman I didn't find an easy way to deal the conditional options in `jq`. if you have any idea about one or line solution to add the `tweet_type`, please let me know. If not, I will transfer to the python way.

**Comment by lwrubel** [comment]
Refs #878.
