### ISSUE TITLE
Duplicate seed allowed in bulk add

### ISSUE THREAD

**Issue by adityadharne** [gwu-libraries/sfm-ui#835]
Duplicate seeds with different capitalizations is allowed and the harvest completes. 
- Example: `adityadharne` and `AdityaDharne` both should not be added.
- Screenshot of the result:

![screen shot 2017-06-13 at 11 55 03 am](https://user-images.githubusercontent.com/15873333/27092194-8fe45978-5030-11e7-888a-cf1125e26b6c.png)

- Previously occurred in https://github.com/gwu-libraries/sfm-ui/issues/640

**Comment by lwrubel** [comment]
Merged with #836.
