### ISSUE TITLE
fix link to IIPC in presentation citation

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#840]
Link to IIPC (http://netpreserve.org/2016-WAC) in https://gwu-libraries.github.io/sfm-ui/resources/
needs to be corrected. The location of the link is in this citation:

Justin Littman, “Aligning Social Media Harvesting and Web Harvesting” at International Internet Preservation Consortium (IIPC) Web Archiving Conference, April 14, 2016 in Reykjavík, Iceland.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-ui/commit/ca42bc7fd27c3e9862040b794a5fe48aa2e3f93c
