### ISSUE TITLE
Home page rendering repetitive and incorrect number of active collection sets

### ISSUE THREAD

**Issue by adityadharne** [gwu-libraries/sfm-ui#843]
- Have not figured out how to recreate on a consistent basis but looks like this:

  <img width="451" alt="screen shot 2017-06-19 at 11 21 19 am" src="https://user-images.githubusercontent.com/15873333/27292439-71ae1768-54e1-11e7-85b6-30f392e9d0af.png">

**Comment by Tanych** [comment]
@adityadharne I also find the issue several days ago.
```python
CollectionSet.objects.filter(
            group__in=self.request.user.groups.all()).filter(collections__is_active=True).order_by('name')
```
break it down,
``set_objs=CollectionSet.objects.filter(group__in=self.request.user.groups.all())`` return 1 object. It's no problem while ``set_objs.filter(collections__is_active=True).order_by('name')`` return 4. 

The SQL for above is：
```
SELECT "ui_collectionset"."id", "ui_collectionset"."collection_set_id", "ui_collectionset"."group_id", "ui_collectionset"."name", "ui_collectionset"."description", "ui_collectionset"."is_visible", "ui_collectionset"."date_added", "ui_collectionset"."date_updated", "ui_collectionset"."history_note" 
FROM "ui_collectionset"
 INNER JOIN "ui_collection" 
ON ( "ui_collectionset"."id" = "ui_collection"."collection_set_id" ) 
WHERE (
        "ui_collectionset"."group_id" IN (
          SELECT U0."id" FROM "auth_group" U0 
           INNER JOIN "ui_user_groups" U1 ON ( U0."id" = U1."group_id" ) 
    WHERE U1."user_id" = 4) AND "ui_collection"."is_active" = True) 
ORDER BY "ui_collectionset"."name" ASC

```
For solution and discussion:
https://stackoverflow.com/questions/8164675/chaining-multiple-filter-in-django-is-this-a-bug
