### ISSUE TITLE
Improved UX for tables in UI

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#853]
See @Tanych's t798-ui-tweaks branch and consider DataTables and django-tables2 plug-ins as libraries to improve functionality. This ticket also includes pagination for those tables, since in some cases it looks like it's related to the table library. 

Make sure that the column widths are optimized for the content within them. For example, the icon with the link to the platform should be a narrower width than the other columns. 

Pages affected:
* collection_set_list
* collection_set_detail
* collection_detail
* export_list
* credential_list
* monitor
 (add any I missed)

**Comment by Tanych** [comment]
@lwrubel 
For `DataTables` or `django-tables2`, it depends on how much coding changes on the UI templates or views.py.
* If we take the `datatables`, most coding work will rely on the UI html templates, javascript, a little Ajax and views.py. It's kind of front-end improvement. 
* if we take the `django-tables2`, we need to make lots of change on the views.py, also the UI templates.
 We also need to add additional coding for the table.py and filter.py to implement the functions.  It depends on the [django-table2](https://github.com/bradleyayers/django-tables2) and [django-filter](https://github.com/carltongibson/django-filter).

**Comment by lwrubel** [comment]
I'll leave the final decision to @justinlittman, who's evaluating the technical side of this work, but my sense is that a python/Django approach (django-tables2 and django-filter) is more in line with what we will be able to best support going forward with SFM, even if it's more work right now. I'd be interested in yours and @adityadharne's sense of the work involved with that approach, however.

**Comment by justinlittman** [comment]
@adityadharne @Tanych For work on the seed table and the other tables, please make sure to coordinate your work so that the tables look, sort, page, and filter the same.
