### ISSUE TITLE
ProgrammingError at /ui/collection_sets/*

### ISSUE THREAD

**Issue by liuqingli** [gwu-libraries/sfm-ui#861]
Hello, when I upgraded SFM from 1.8.0 to 1.9.0 and restarted it, a programming error occurred.
The detailed message is shown below:

![screen shot 2017-07-05 at 7 04 48 pm](https://user-images.githubusercontent.com/17070112/27888587-deb60796-61b4-11e7-859d-87bb0c2464c2.png)

**Comment by justinlittman** [comment]
Hmmm ... try:
```
docker-compose stop ui
docker-compose up -d
```

**Comment by liuqingli** [comment]
I have tried but failed. For the upgrade, I just followed the document [https://sfm.readthedocs.io/en/latest/install.html#upgrading](url). The error might show that there is a non-existing column (is_on) in the table.

**Comment by justinlittman** [comment]
In the latest release, there was a minor change to the db schema. Django is supposed to automagically perform the migration but seems not to for you.

Can you try the following?
```
docker-compose stop ui uiconsumer
docker-compose rm -vf ui uiconsumer
```
then do a `docker ps -a` to make sure there are no ui or ui consumer containers left. (Look for any container that has ui or uiconsumer in the name.)

Followed by:
```
docker-compose up -d
docker-compose logs -f ui
```
Look for anything askew in the logs and/or the section of the log that shows a migration being performed.

**Comment by liuqingli** [comment]
It seems that SFM tries to run the migration but failed. The log info is shown below:

ui_1                      | Check 1
ui_1                      | /opt/sfm-ui exists.
ui_1                      | db:5432 is available.
ui_1                      | /sfm-data/collection_set exists.
ui_1                      | Check 2
ui_1                      | Check 3
ui_1                      | mq:5672 is available.
ui_1                      | Check 4
ui_1                      | Migrating db
ui_1                      | Operations to perform:
ui_1                      |   Synchronize unmigrated apps: weibo, simple_history, apscheduler, staticfiles, datetimewidget, twitter, api, messages, tumblr, allauth, humanize, finalware, rest_framework, message_consumer, crispy_forms
ui_1                      |   Apply all migrations: account, sessions, admin, sites, auth, contenttypes, ui, socialaccount
ui_1                      | Synchronizing apps without migrations:
ui_1                      |   Creating tables...
ui_1                      |     Running deferred SQL...
ui_1                      |   Installing custom SQL...
ui_1                      | Running migrations:
ui_1                      |   Rendering model states... DONE
ui_1                      | Traceback (most recent call last):
ui_1                      |   File "/opt/sfm-ui/sfm/manage.py", line 10, in <module>
ui_1                      |     execute_from_command_line(sys.argv)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
ui_1                      |     utility.execute()
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
ui_1                      |     self.fetch_command(subcommand).run_from_argv(self.argv)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
ui_1                      |     self.execute(*args, **cmd_options)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
ui_1                      |     output = self.handle(*args, **options)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 222, in handle
ui_1                      |     executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
ui_1                      |     self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
ui_1                      |     state = migration.apply(state, schema_editor)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
ui_1                      |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 359, in database_forwards
ui_1                      |     getattr(new_model._meta, self.option_name, set()),
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 324, in alter_unique_together
ui_1                      |     self.execute(self._create_unique_sql(model, columns))
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
ui_1                      |     cursor.execute(sql, params)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
ui_1                      |     return self.cursor.execute(sql, params)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
ui_1                      |     six.reraise(dj_exc_type, dj_exc_value, traceback)
ui_1                      |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
ui_1                      |     return self.cursor.execute(sql, params)
ui_1                      | django.db.utils.IntegrityError: could not create unique index "ui_seed_collection_id_5a9ae0d72334738_uniq"
ui_1                      | DETAIL:  Key (collection_id, uid, token)=(10, , {}) is duplicated.

**Comment by justinlittman** [comment]
Now I know what is going on. In the past, our deduplication of seeds hasn't worked quite right. Our attempt to apply a new unique index is failing.

To solve this, you need to get rid of the duplicate seeds (i.e., having the same collection_id, uid, and token). This can be done directly from the db or from the admin ui. I'd suggest starting with the admin ui:
1. Bring up a previous version of SFM.
2. Go the to admin interface and view the list of seeds.
3. Sort by token.
4. Scan through and look for duplicates.
5. Delete one instance of every duplicate.
6. Retry bringing up the new version of SFM looking for errors.

If you get stuck on any of this, let me know and we can work through the process.

**Comment by liuqingli** [comment]
Thanks very much! Now it works well after I deleted the deplicated seeds.
