### ISSUE TITLE
Excel downloads as html

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#904]
As seen by at least two students in the SFM library workshop, clicking on the link for the .xlsx exported file downloads the file as html.

**Comment by justinlittman** [comment]
I went through the last 8 excel exports created on the sandbox and cannot replicate. @lwrubel Do you know which exports were problematic or which browsers/OSes the students were using?

**Comment by lwrubel** [comment]
I don't think it was an issue with the file, but how the browser was interpreting the download link. They were both on Macs, if I remember correctly. I'm not sure if they were using Safari or Chrome.

**Comment by justinlittman** [comment]
I can reproduce this problem on Safari.
