### ISSUE TITLE
Switch to using twarc json2csv for export

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#909]
The fields are better thought out than our export fields.

Also will need to update data dictionary docs.

**Comment by kerchner** [comment]
Consider "deprecating" existing CSV/Excel export to give current users some lead time in advance of any significant reshuffling of export fields.

**Comment by justinlittman** [comment]
Fixed by https://github.com/gwu-libraries/sfm-twitter-harvester/commit/202333378d124aef7844b30f28c869d43c7cec73
