### ISSUE TITLE
Scheduler improvements

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#92]
In support of #79

**Comment by justinlittman** [comment]
How the scheduler should work:  Choices for harvest intervals should be every hour, every day, every week, every 4 weeks.  In development, it should also be possible to add an every 5 minutes.  If a harvest start date is set, the harvest should start on that date and repeat at the specified interval.  If a harvest start date is not set, the harvest should start 15 seconds from now (to allow the job to be scheduled).

This is based on my experience doing development of SFM with the current scheduler and speculation about the needs of users.

**Comment by kerchner** [comment]
Resolved in #104
