### ISSUE TITLE
Failed smoke tests after install

### ISSUE THREAD

**Issue by Miranda-C-Smith** [gwu-libraries/sfm-ui#922]
After installing and running sfm for the first time I tried to run the smoke tests to verify that it was working and I got the following error

```
/sfm-docker$ docker-compose -f docker-compose.yml -f smoketests.docker-compose.yml run --rm smoketests python -m unittest discover
Starting sfm_data_1
Starting sfm_processingdata_1
F.Ehttp://mq:15672/api/whoami
http://mq:15672/api/aliveness-test/%2F
http://mq:15672/api/exchanges
.http://mq:15672/api/whoami
http://mq:15672/api/aliveness-test/%2F
http://mq:15672/api/queues
.
======================================================================
ERROR: test_login (smoke_tests.test_ui.UiSmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/sfm-test/smoke_tests/test_ui.py", line 16, in test_login
    browser.fill("login", "testuser")
  File "/usr/local/lib/python2.7/site-packages/splinter/driver/webdriver/__init__.py", line 413, in fill
    field = self.find_by_name(name).first
  File "/usr/local/lib/python2.7/site-packages/splinter/element_list.py", line 53, in first
    return self[0]
  File "/usr/local/lib/python2.7/site-packages/splinter/element_list.py", line 44, in __getitem__
    self.find_by, self.query))
ElementDoesNotExist: no elements could be found with name "login"

======================================================================
FAIL: test_admin_login (smoke_tests.test_ui.UiSmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/sfm-test/smoke_tests/test_ui.py", line 25, in test_admin_login
    self.assertTrue(browser.find_by_text("Django administration"))
AssertionError: [] is not true

----------------------------------------------------------------------
Ran 5 tests in 17.010s

FAILED (failures=1, errors=1)

```

Do you know what could be causing this or how to fix it?

**Comment by justinlittman** [comment]
Hmmm ...  we continue to run the smoke tests in our CI environment so let me see what I can figure out.

**Comment by justinlittman** [comment]
OK. I can verify the problem and suspect I know what is causing it. To run smoke tests, you need to use `example.docker-compose.yml` not `example.prod.docker-compose.yml`.

The non-production docker-compose (1) automatically creates accounts that are needed for testing and (2) runs the UI in a testing mode where it can be accessed by the smoke test container.

Can you verify if this works? Also, can you point me to the docs you were using for the smoke tests so that I can make the appropriate clarifications?

Thanks @Miranda-C-Smith!

**Comment by Miranda-C-Smith** [comment]
I tried substituting 
`docker-compose -f docker-compose.yml -f smoketests.docker-compose.yml run --rm smoketests python -m unittest discover`
with 
`docker-compose -f example.docker-compose.yml -f smoketests.docker-compose.yml run --rm smoketests python -m unittest discover`

because during install 
`cp example.prod.docker-compose.yml docker-compose.yml` 

and got the following output

```
Starting sfm_data_1
Starting sfm_processingdata_1
F.Ehttp://mq:15672/api/whoami
http://mq:15672/api/aliveness-test/%2F
http://mq:15672/api/exchanges
.http://mq:15672/api/whoami
http://mq:15672/api/aliveness-test/%2F
http://mq:15672/api/queues
.
======================================================================
ERROR: test_login (smoke_tests.test_ui.UiSmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/sfm-test/smoke_tests/test_ui.py", line 16, in test_login
    browser.fill("login", "testuser")
  File "/usr/local/lib/python2.7/site-packages/splinter/driver/webdriver/__init__.py", line 413, in fill
    field = self.find_by_name(name).first
  File "/usr/local/lib/python2.7/site-packages/splinter/element_list.py", line 53, in first
    return self[0]
  File "/usr/local/lib/python2.7/site-packages/splinter/element_list.py", line 44, in __getitem__
    self.find_by, self.query))
ElementDoesNotExist: no elements could be found with name "login"

======================================================================
FAIL: test_admin_login (smoke_tests.test_ui.UiSmokeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/sfm-test/smoke_tests/test_ui.py", line 25, in test_admin_login
    self.assertTrue(browser.find_by_text("Django administration"))
AssertionError: [] is not true

----------------------------------------------------------------------
Ran 5 tests in 11.202s

FAILED (failures=1, errors=1)
```

So that did not fix it for me. Can I provide any more info that would be helpful?
The documentation is at http://sfm.readthedocs.io/en/latest/development.html#smoke-tests

**Comment by justinlittman** [comment]
Hmmm ... Can you try reproducing with these steps?
1. Stop all containers.
2. Clone: `git clone https://github.com/gwu-libraries/sfm-docker.git`
3. `cd sfm-docker`
4. `cp example.env .env`
5. `docker-compose -f example.docker-compose.yml -f smoketests.docker-compose.yml pull`
6. `docker-compose -f example.docker-compose.yml -f smoketests.docker-compose.yml up -d`
7. `sleep 45`
8. `docker-compose -f example.docker-compose.yml -f smoketests.docker-compose.yml run --rm smoketests /bin/bash -c "appdeps.py --port-wait mq:5672 --port-wait ui:8080 && python -m unittest discover"`

What OS are you running this on?

Thanks for your assistance in tracking this down.

**Comment by Miranda-C-Smith** [comment]
Following those instructions here are the results for 8.

```
$ docker-compose -f example.docker-compose.yml -f smoketests.docker-compose.yml run --rm smoketests /bin/bash -c "appdeps.py --port-wait mq:5672 --port-wait ui:8080 && python -m unittest discover"
Starting sfm_processingdata_1
Starting sfm_data_1
Check 1
mq:5672 is available.
ui:8080 is available.
Check 2
...http://mq:15672/api/whoami
http://mq:15672/api/aliveness-test/%2F
http://mq:15672/api/exchanges
.http://mq:15672/api/whoami
http://mq:15672/api/aliveness-test/%2F
http://mq:15672/api/queues
.
----------------------------------------------------------------------
Ran 5 tests in 9.320s

OK
```
Seems to work.
OS is Ubuntu 16.04.4

**Comment by justinlittman** [comment]
Thanks. Adding this ticket to our next milestone to make the docs clearer. Let me know if you have any other questions or encounter other problems.
