### ISSUE TITLE
“text” field is empty in the exported csv/xlsx files of harvest.

### ISSUE THREAD

**Issue by fishfree** [gwu-libraries/sfm-ui#937]
I followed the official installation documentation, but “text” field is empty in the exported csv/xlsx files of harvest. Very very confusing.

**Comment by justinlittman** [comment]
Duplicate of #935.

@fishtree - to fix:
1. `docker-compose stop twitterrestexporter twitterstreamexporter`
2. Change the version of the Twitter rest exporter and Twitter stream exporter to 1.12.1 in your docker-compose.yml.
3. `docker-compose up -d`.

Please re-open if this doesn't correct the problem. Sorry about that!

**Comment by fishfree** [comment]
Problem solved, thank you!
