### ISSUE TITLE
/ui/monitor (Harvester Status) shows many harvesters

### ISSUE THREAD

**Issue by dchud** [gwu-libraries/sfm-ui#956]
Hi, I am an adjunct lecturer at GWU and am using SFM to collect data to support an upcoming lecture. I was keeping an eye on my twitter filter and visited `/ui/monitor` to see what it had to say, and was surprised to find it showed a list of 30-40 harvesters running along with the harvest names.  Most of these names are not very revealing (e.g. a hurricane name) but perhaps some of them are.  It might be best to restrict the monitor view somewhat more.

One other thing... and sorry not to write a separate ticket for this, but I noticed on my collection export  page (`/ui/exports/EXPORT_ID/`) it reported an export segment size of 1,000,000, but I had requested 100,000.  The export files themselves were correct, at exactly 100,000 each, so perhaps there's a hard-coded message in there somewhere.

Thank you for providing this service! It's great to have this available, and I will be telling our students about it in case they are looking to study social media data.

**Comment by justinlittman** [comment]
Probably user error ...

**Comment by lwrubel** [comment]
Thanks for the useful suggestions @dchud, and glad SFM was useful in supporting your class. We're aiming to do a small release with feature improvements before the end of the year, so I hope we can roll these into it.
