### ISSUE TITLE
"error" request message in JSON causes exception when exporting tweets

### ISSUE THREAD

**Issue by lwrubel** [gwu-libraries/sfm-ui#958]
Exception occurs when twitter_rest_warc_iter.py is exporting JSON that contains:

{'request': '/1.1/statuses/user_timeline.json', 'error': 'Not authorized.'}

Add handling for "error" in JSON. 

Example WARC with error is available at:
/sfm-data/collection_set/920479b0f74e46fe8371c92f3941d461/da3e0585442b4b06857c82fc4db2599c/2018/06/11/19/77b57484f6994397883512f1f62a6d55-20180611195926580-00001-6547-d042b25bef1e-8436.warc.gz

**Comment by justinlittman** [comment]
You found it! Nice.

**Comment by lwrubel** [comment]
twitter_rest_warc_iter.py can already handle errors from the Twitter API that look like: 

```{'errors': [{'code': 88, 'message': 'Rate limit exceeded'}]}```

The line in the JSON response that showed up in some WARCs from June 2018 looks like:

```{'request': '/1.1/statuses/user_timeline.json', 'error': 'Not authorized.'}```

**Comment by lwrubel** [comment]
PR: https://github.com/gwu-libraries/sfm-twitter-harvester/pull/43

**Comment by kerchner** [comment]
Fixed in https://github.com/gwu-libraries/sfm-twitter-harvester/pull/43
