### ISSUE TITLE
Support AWS Elastic Load Balancer

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#960]
This is based on our experience deploying SFM at Stanford Libraries.

To have AWS manage certificates, SFM must be deployed behind an Elastic Load Balancer. (The ELB acts as an HTTPS proxy, just as Nginx does within the SFM docker environment.)

An ELB performs regular health checks. However, those health checks fail with:
```
ui_1_d69f931286be               | [Thu Dec 13 10:46:19.990901 2018] [wsgi:error] [pid 68:tid 139935178061568] [remote 10.0.2.228:52162] ERROR 2018-12-13 10:46:19,990 68 django.security.DisallowedHost Invalid HTTP_HOST header: '10.0.0.120'. You may need to add '10.0.0.120' to ALLOWED_HOSTS.
```

Thus, ALLOWED_HOSTS has to be modified to permit these health check requests.

**Comment by kerchner** [comment]
Closed in #961
