### ISSUE TITLE
SFM UI Queued Requests

### ISSUE THREAD

**Issue by liuqingli** [gwu-libraries/sfm-ui#962]
Hi,
Recently, our SFM (v2.0.2) got a huge number of UI requests. When we try to turn on some collections, it will take quite a long time to wait for update. I tried to purge messages through RabbitMQ, but the number increased again for some time. I wonder if someone could give me some suggestions on checking or resolving the problem. Thanks very much!

**screenshot 1:**
![screen shot 2018-12-13 at 9 37 08 pm](https://user-images.githubusercontent.com/17070112/49979943-4dd9f980-ff1f-11e8-8731-15c24b9880c0.png)
**screenshot 2:**
![screen shot 2018-12-13 at 9 40 15 pm](https://user-images.githubusercontent.com/17070112/49980159-5121b500-ff20-11e8-90ff-2e0886cfdd51.png)
**screenshot 3:**
![screen shot 2018-12-13 at 9 46 04 pm](https://user-images.githubusercontent.com/17070112/49980211-83331700-ff20-11e8-814a-f9c8db5b144b.png)

**Comment by lwrubel** [comment]
Hi @liuqingli. A long SFM_UI can get created when a lot of harvesters start up at once (for example if you stopped SFM to upgrade and restarted). The queue should slowly go down. Do you see the queue going down on its own over time? Or is something else happening?

**Comment by lwrubel** [comment]
So, the queue would normally go down as SFM UI updates the records for harvests and exports. I'm wondering if you would see anything in the docker logs for sfm_ui that might be useful? 

```docker logs sfm_ui_1``` 

The multiple twitter_harvester queues have to do with each harvester needing to each get stop messages and check them against their harvest to see if the stop message is for it.

**Comment by liuqingli** [comment]
I think my SFM UI has got some errors, as shown below.

![screen shot 2018-12-14 at 3 06 47 pm](https://user-images.githubusercontent.com/17070112/50024924-e4ef9180-ffb1-11e8-83cd-ccf7f5afc6a9.png)

**Comment by liuqingli** [comment]
I once restarted the service and now everything looks good :)

**Comment by lwrubel** [comment]
Glad to hear that! I'll close the issue, but if you observe this again, please let us know.
