### ISSUE TITLE
Allow for separate mail from address

### ISSUE THREAD

**Issue by justinlittman** [gwu-libraries/sfm-ui#967]
Currently, mail from is set to the EMAIL_HOST_USER. While this works for Gmail, it does not work for AWS SES, in which the EMAIL_HOST_USER is separate from the mail from address.

**Comment by justinlittman** [comment]
Accidentally committed https://github.com/gwu-libraries/sfm-docker/commit/0b4b618a4a9f53e8288d498f663851d0e9571abe directly to master. If you'd like me to undo or make changes, let me know.

Sorry!

**Comment by kerchner** [comment]
@justinlittman No problem, looks good.

**Comment by kerchner** [comment]
Closed in https://github.com/gwu-libraries/sfm-docker/commit/0b4b618a4a9f53e8288d498f663851d0e9571abe
