### ISSUE TITLE
Dependency upgrades to messaging etc. libraries

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#973]
Ref #959 - these and #971 were left over from #959.

The following set of libraries was not upgraded due risk of and/or observation of potential problems that may require changes in SFM in order to upgrade:

- in sfm-ui:
  - APScheduler (currently 3.5.1, latest release is 3.5.3)
  - django-filter (currently 1.1.10, latest release is 2.0.0)
  - djangorestframework (currently 3.8.2, latest release is 3.9.0)
- in sfm-utils:
  - kombu (currently 4.0.2, latest release is 4.2.2)

**Comment by lwrubel** [comment]
Closed with #986
