### ISSUE TITLE
Upgrade bootstrap version

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#987]
Ref:

* https://github.com/gwu-libraries/sfm-ui/blob/master/sfm/ui/templates/base.html
* https://getbootstrap.com/docs/4.3/migration/?origin_team=T08AFN77V

**Comment by dolsysmith** [comment]
- `change_log.html`
  - `pager` class deprecated
- `collection_create.html`
  - `breadcrumb` class now requires `.breadcrumb-item` on descendants
- `collection_detail.html`
  - see above for `breadcrumb` class
  - `.panel` deprecated in favor of `.card` classes
  - `.glyphicon` no longer included (?)
  - changes to `.dropdown-menu` implementation
  - `.btn-default` --> `.btn-secondary`
  - changes to `.nav` implementation
- `collection_set_create.html` 
  - see above for `.breadcrumb`
- `collection_set_detail.html`
  - see above: `.breadcrumb`, `.panel`, `.dropdown-menu`, '.glyphicon`

**Comment by lwrubel** [comment]
Note that we use django-crispy-forms for forms creation and formatting. We're currently on 1.7.2 but should likely upgrade to 1.9.0 for bootstrap 4 support. However, upgrading to any version beyond the current one makes the seed choice fields in the export form not work. ([Release notes](https://github.com/django-crispy-forms/django-crispy-forms/releases)). 

This part will need attention: https://github.com/gwu-libraries/sfm-ui/blob/master/sfm/ui/forms.py#L950

**Comment by dolsysmith** [comment]
Glyphicons is no longer part of Bootstrap as of V4. The migration guide recommends the [upstream version](https://glyphicons.com/), but that appears to have an associated cost (albeit low).

**Comment by dolsysmith** [comment]
Bootstrap 4 uses flexbox instead of floats for alignment, which affects the placement of many items.

**Comment by dolsysmith** [comment]
The dropdown menu for Add Collection is dropping **up** in Bootstrap 4. I can't quite figure out why, except that it seems to have something to do with the behavior of Popper.js (which Bootstrap 4 uses for dropdowns).

**Comment by lwrubel** [comment]
Looks like it is popping up because the menu is so long there is not enough room on the screen below the button. I'm looking at making it a little more compact since it seems like there is too much spacing in the menu after the upgrade.
