### ISSUE TITLE
Django and related dependency upgrades

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/sfm-ui#993]
Followon to #973:
- in sfm-ui:
    - django (currentl 2.0.13, latest is 2.3.0)
         - This will require upgrading to Postgresql 9.5
    - django-filter (currently 1.1.0, latest release is 2.2.0)

Remove datetime widget.  This will be added back in #1011

**Comment by kerchner** [comment]
Ref https://docs.google.com/document/d/1uhoZKgOgSTrNE-6HiKgA50NIiwdyhPm9Iu5dWcFErR4/edit?usp=drive_web&ouid=110561461825583468817

**Comment by lwrubel** [comment]
Focus on Django and related dependencies.
